import type { Question, QuestionOption } from "./questions";

const numericOptions = (values: string[]): QuestionOption[] =>
  values.map((value, index) => ({
    label: String.fromCharCode(65 + index) as QuestionOption["label"],
    valueZh: value,
  }));

const sourceUrl = "https://live.poshenloh.com/past-contests/amc8/2018";

export const questions2018: Question[] = [
  {
    id: "2018-01", year: 2018, number: 1, status: "published",
    primaryTopic: "算术", skills: ["比例", "四舍五入"], formats: ["文字应用题"], difficulty: 1,
    promptZh: "某游乐园按 1:20 的比例制作各地建筑模型。美国国会大厦高 289 英尺，其模型高度取最接近的整数是多少英尺？",
    promptEn: "An amusement park uses a 1:20 scale for building models. The U.S. Capitol is 289 feet tall. What is the replica's height, rounded to the nearest foot?",
    options: numericOptions(["14", "15", "16", "18", "20"]), answer: "A",
    solutionZh: ["模型高度为 289÷20=14.45 英尺，四舍五入为 14 英尺。"],
    solutionEn: ["The model is 289/20=14.45 feet tall, which rounds to 14."], sourceUrl,
  },
  {
    id: "2018-02", year: 2018, number: 2, status: "published",
    primaryTopic: "算术", skills: ["连乘约分", "分数"], formats: ["算式"], difficulty: 1,
    promptZh: "求下列连乘式的值。", promptEn: "What is the value of the following product?",
    expression: ["(1+1/1)(1+1/2)(1+1/3)(1+1/4)(1+1/5)(1+1/6)"],
    options: numericOptions(["7/6", "4/3", "7/2", "7", "8"]), answer: "D",
    solutionZh: ["每项 1+1/n=(n+1)/n，连乘后中间因子全部约掉。", "结果为 2/1×3/2×⋯×7/6=7。"],
    solutionEn: ["Each factor is (n+1)/n, so the product telescopes.", "It becomes 2/1·3/2·…·7/6=7."], sourceUrl,
  },
  {
    id: "2018-03", year: 2018, number: 3, status: "published",
    primaryTopic: "计数与组合", secondaryTopics: ["数论"], skills: ["循环淘汰", "按规则模拟"], formats: ["逻辑排列题"], difficulty: 2,
    promptZh: "Arn、Bob、Cyd、Dan、Eve、Fon 按此顺序围成一圈报数。报到含数字 7 或 7 的倍数时，该人离开，报数继续。最后留下谁？",
    promptEn: "Arn, Bob, Cyd, Dan, Eve, and Fon count in a circle. A person leaves whenever the number contains a 7 or is a multiple of 7. Who remains last?",
    options: [
      { label: "A", valueZh: "Arn" }, { label: "B", valueZh: "Bob" }, { label: "C", valueZh: "Cyd" }, { label: "D", valueZh: "Dan" }, { label: "E", valueZh: "Eve" },
    ], answer: "D",
    solutionZh: ["前五个淘汰数为 7、14、17、21、27，对应依次淘汰 Arn、Cyd、Fon、Bob、Eve。", "因此最后留下 Dan。"],
    solutionEn: ["The first five removal numbers are 7, 14, 17, 21, and 27, removing Arn, Cyd, Fon, Bob, and Eve.", "Dan is last."], sourceUrl,
  },
  {
    id: "2018-04", year: 2018, number: 4, status: "published",
    primaryTopic: "几何", skills: ["方格面积", "图形分割"], formats: ["方格图"], difficulty: 1,
    promptZh: "图中的十二边形画在 1 厘米×1 厘米方格纸上，面积是多少平方厘米？",
    promptEn: "The twelve-sided figure is drawn on 1 cm by 1 cm graph paper. What is its area?",
    figure: { src: "/questions/2018/q04.png", altZh: "画在单位方格上的十二边形。", altEn: "A twelve-sided polygon on a unit grid." },
    options: numericOptions(["12", "12.5", "13", "13.5", "14"]), answer: "C",
    solutionZh: ["图形可分成中心 3×3 正方形和四个底为 2、高为 1 的三角形。", "面积为 9+4×(2×1÷2)=13。"],
    solutionEn: ["Split the figure into a 3-by-3 square and four triangles of base 2 and height 1.", "The area is 9+4·1=13."], sourceUrl,
  },
  {
    id: "2018-05", year: 2018, number: 5, status: "published",
    primaryTopic: "算术", skills: ["配对求和", "数列"], formats: ["算式"], difficulty: 1,
    promptZh: "求 1+3+5+⋯+2017+2019-2-4-6-⋯-2016-2018 的值。",
    promptEn: "Evaluate 1+3+5+⋯+2017+2019−2−4−6−⋯−2016−2018.",
    expression: ["1 + 3 + 5 + ⋯ + 2019 − 2 − 4 − 6 − ⋯ − 2018"],
    options: numericOptions(["−1010", "−1009", "1008", "1009", "1010"]), answer: "E",
    solutionZh: ["整理为 1+(3-2)+(5-4)+⋯+(2019-2018)。", "共有 1010 个值为 1 的项，所以结果为 1010。"],
    solutionEn: ["Regroup as 1+(3-2)+(5-4)+⋯+(2019-2018).", "There are 1010 terms equal to 1, so the sum is 1010."], sourceUrl,
  },
  {
    id: "2018-06", year: 2018, number: 6, status: "published",
    primaryTopic: "算术", secondaryTopics: ["代数"], skills: ["速度", "比例"], formats: ["文字应用题"], difficulty: 2,
    promptZh: "Anh 去海滩时在高速公路行驶 50 英里，在沿海道路行驶 10 英里。高速速度是沿海道路的 3 倍；沿海道路用时 30 分钟。全程共用多少分钟？",
    promptEn: "Anh drives 50 highway miles and 10 coastal-road miles. His highway speed is three times his coastal speed, and the coastal portion takes 30 minutes. How long is the whole trip?",
    options: numericOptions(["50", "70", "80", "90", "100"]), answer: "C",
    solutionZh: ["沿海道路速度为 10/30=1/3 英里/分钟，高速速度为 1 英里/分钟。", "高速用时 50 分钟，总用时 50+30=80 分钟。"],
    solutionEn: ["The coastal speed is 1/3 mile per minute, so the highway speed is 1 mile per minute.", "The highway takes 50 minutes, for 80 minutes total."], sourceUrl,
  },
  {
    id: "2018-07", year: 2018, number: 7, status: "published",
    primaryTopic: "数论", skills: ["整除规则", "余数"], formats: ["整数题"], difficulty: 2,
    promptZh: "五位数 2018U 能被 9 整除，其中 U 为一位数字。这个数除以 8 的余数是多少？",
    promptEn: "The five-digit number 2018U is divisible by 9. What is its remainder when divided by 8?",
    options: numericOptions(["1", "3", "5", "6", "7"]), answer: "B",
    solutionZh: ["数字和为 11+U，需为 9 的倍数，因此 U=7，原数为 20187。", "20187=2523×8+3，余数为 3。"],
    solutionEn: ["The digit sum 11+U must be divisible by 9, so U=7.", "20187=2523·8+3, so the remainder is 3."], sourceUrl,
  },
  {
    id: "2018-08", year: 2018, number: 8, status: "published",
    primaryTopic: "数据与统计", skills: ["加权平均数", "条形图"], formats: ["条形图"], difficulty: 2,
    promptZh: "条形图显示 Garcia 老师班级中学生上周锻炼至少 30 分钟的天数。学生报告的平均锻炼天数是多少？结果保留到百分位。",
    promptEn: "The bar graph shows how many days students exercised at least 30 minutes last week. What was the mean number of days, rounded to the nearest hundredth?",
    figure: { src: "/questions/2018/q08.png", altZh: "横轴为锻炼天数、纵轴为学生人数的条形图。", altEn: "A bar graph of number of exercise days versus number of students." },
    options: numericOptions(["3.50", "3.57", "4.36", "4.50", "5.00"]), answer: "C",
    solutionZh: ["1 至 7 天对应人数为 1、3、2、6、8、3、2，共 25 人。", "总天数为 109，因此平均数为 109/25=4.36。"],
    solutionEn: ["The frequencies are 1, 3, 2, 6, 8, 3, and 2, totaling 25 students.", "The weighted total is 109, so the mean is 109/25=4.36."], sourceUrl,
  },
  {
    id: "2018-09", year: 2018, number: 9, status: "published",
    primaryTopic: "几何", secondaryTopics: ["算术"], skills: ["边框面积", "铺砖计数"], formats: ["文字应用题"], difficulty: 2,
    promptZh: "一个 12×16 英尺房间的边缘用 1×1 英尺砖铺一圈，内部用 2×2 英尺砖铺满。共需多少块砖？",
    promptEn: "A 12-by-16-foot room gets a one-tile-wide border of 1-by-1 tiles, with the interior filled by 2-by-2 tiles. How many tiles are used?",
    options: numericOptions(["48", "87", "91", "96", "120"]), answer: "B",
    solutionZh: ["边框有 2×16+2×12-4=52 块 1×1 砖。", "内部为 10×14，需 10×14÷4=35 块 2×2 砖，总数 52+35=87。"],
    solutionEn: ["The border uses 2·16+2·12-4=52 unit tiles.", "The 10-by-14 interior uses 35 larger tiles, for 87 total."], sourceUrl,
  },
  {
    id: "2018-10", year: 2018, number: 10, status: "published",
    primaryTopic: "算术", skills: ["调和平均数", "倒数"], formats: ["定义题"], difficulty: 2,
    promptZh: "一组非零数的调和平均数定义为这些数的倒数的平均数再取倒数。1、2、4 的调和平均数是多少？",
    promptEn: "The harmonic mean is the reciprocal of the average of the reciprocals. What is the harmonic mean of 1, 2, and 4?",
    options: numericOptions(["3/7", "7/12", "12/7", "7/4", "7/3"]), answer: "C",
    solutionZh: ["倒数平均数为 (1+1/2+1/4)/3=7/12。", "再取倒数得到 12/7。"],
    solutionEn: ["The average reciprocal is (1+1/2+1/4)/3=7/12.", "Its reciprocal is 12/7."], sourceUrl,
  },
  {
    id: "2018-11", year: 2018, number: 11, status: "published",
    primaryTopic: "概率", secondaryTopics: ["计数与组合"], skills: ["分类计数", "相邻位置"], formats: ["座位图"], difficulty: 2,
    promptZh: "6 人随机坐在 2 行 3 列的位置中。Abby 与 Bridget 在同一行相邻或同一列相邻的概率是多少？",
    promptEn: "Six people are randomly seated in two rows of three. What is the probability that Abby and Bridget are adjacent in the same row or column?",
    options: numericOptions(["1/3", "2/5", "7/15", "1/2", "2/3"]), answer: "C",
    solutionZh: ["Abby 在两个中间位置的概率为 1/3，此时 Bridget 有 3 个相邻位置；在四个外侧位置的概率为 2/3，此时有 2 个相邻位置。", "所求概率为 (1/3)(3/5)+(2/3)(2/5)=7/15。"],
    solutionEn: ["If Abby is in a middle seat (probability 1/3), Bridget has 3 adjacent choices; otherwise she has 2.", "Thus the probability is (1/3)(3/5)+(2/3)(2/5)=7/15."], sourceUrl,
  },
  {
    id: "2018-12", year: 2018, number: 12, status: "published",
    primaryTopic: "代数", skills: ["时钟快慢", "比例"], formats: ["文字应用题"], difficulty: 2,
    promptZh: "Sri 开始购物时，准确手表和快钟都显示 12:00。30 分钟后，快钟显示 12:35。后来快钟显示 7:00 时，实际时间是多少？",
    promptEn: "Sri's fast car clock and accurate watch both show 12:00. After 30 actual minutes, the car clock shows 12:35. When it later shows 7:00, what is the actual time?",
    options: [
      { label: "A", valueZh: "5:50" }, { label: "B", valueZh: "6:00" }, { label: "C", valueZh: "6:30" }, { label: "D", valueZh: "6:55" }, { label: "E", valueZh: "8:10" },
    ], answer: "B",
    solutionZh: ["快钟走 35 分钟时实际过 30 分钟，所以实际时间是快钟经过时间的 6/7。", "快钟从 12:00 到 7:00 走 420 分钟，实际过 420×6/7=360 分钟，即 6:00。"],
    solutionEn: ["Thirty actual minutes correspond to 35 clock minutes, so actual elapsed time is 6/7 of the clock's elapsed time.", "420 clock minutes correspond to 360 actual minutes, making the time 6:00."], sourceUrl,
  },
  {
    id: "2018-13", year: 2018, number: 13, status: "published",
    primaryTopic: "代数", secondaryTopics: ["数论"], skills: ["平均数", "同余", "整数解"], formats: ["文字应用题"], difficulty: 3,
    promptZh: "Laila 五次考试平均 82 分，前四次得分相同且为整数，最后一次分数更高且不超过 100。最后一次成绩可能有多少个不同值？",
    promptEn: "Laila averages 82 on five tests. The first four equal integer scores are lower than the final integer score, which is at most 100. How many final scores are possible?",
    options: numericOptions(["4", "5", "9", "10", "18"]), answer: "A",
    solutionZh: ["设前四次为 f、末次为 l，则 4f+l=410，且 82<l≤100。又因 4f 为 4 的倍数，l≡2（模 4）。", "可能的 l 为 86、90、94、98，共 4 个。"],
    solutionEn: ["With 4f+l=410 and l>f, we get 82<l≤100; also l≡2 mod 4.", "The values are 86, 90, 94, and 98, so there are 4."], sourceUrl,
  },
  {
    id: "2018-14", year: 2018, number: 14, status: "published",
    primaryTopic: "数论", secondaryTopics: ["计数与组合"], skills: ["数字乘积", "位值", "最值构造"], formats: ["整数题"], difficulty: 3,
    promptZh: "设 N 是各位数字乘积为 120 的最大五位数。N 的各位数字之和是多少？",
    promptEn: "Let N be the greatest five-digit number whose digits have product 120. What is the sum of the digits of N?",
    options: numericOptions(["15", "16", "17", "18", "20"]), answer: "D",
    solutionZh: ["要使五位数最大，应从最高位开始尽量取大，同时把 120 分成 5 个一位数的乘积。", "最优数字按降序为 8、5、3、1、1，得到 N=85311，数字和为 18。"],
    solutionEn: ["Maximize the leading digits while factoring 120 into five one-digit factors.", "The optimal descending digits are 8, 5, 3, 1, and 1, giving 85311 and digit sum 18."], sourceUrl,
  },
  {
    id: "2018-15", year: 2018, number: 15, status: "published",
    primaryTopic: "几何", skills: ["圆面积", "半径关系"], formats: ["几何图"], difficulty: 2,
    promptZh: "图中每个小圆的直径都等于大圆的半径。若两个小圆的面积之和为 1 平方单位，阴影部分的面积是多少平方单位？",
    promptEn: "In the diagram, a diameter of each smaller circle is a radius of the larger circle. If the two smaller circles have combined area 1, what is the shaded area?",
    figure: { src: "/questions/2018/q15.png", altZh: "一个大圆内有两个相切的小圆，阴影为大圆内、小圆外的区域。", altEn: "Two tangent smaller circles inside a larger circle, with the region outside them shaded." },
    options: numericOptions(["1/4", "1/3", "1/2", "1", "π/2"]), answer: "D",
    solutionZh: ["设小圆半径为 r，则大圆半径为 2r，所以大圆面积是一个小圆面积的 4 倍。", "两个小圆总面积为 1，因此大圆面积为 2，阴影面积为 2-1=1。"],
    solutionEn: ["If a smaller radius is r, the larger radius is 2r, so the large circle has four times one small circle's area.", "The two small circles total 1, so the large circle has area 2 and the shaded area is 1."], sourceUrl,
  },
  {
    id: "2018-16", year: 2018, number: 16, status: "published",
    primaryTopic: "计数与组合", skills: ["捆绑法", "排列"], formats: ["排列题"], difficulty: 3,
    promptZh: "Chang 教授把 9 本互不相同的语言书排在书架上：2 本阿拉伯语、3 本德语、4 本西班牙语。若阿拉伯语书必须相邻，西班牙语书也必须相邻，共有多少种排法？",
    promptEn: "Professor Chang has nine different language books: two Arabic, three German, and four Spanish. How many arrangements keep the Arabic books together and the Spanish books together?",
    options: numericOptions(["1440", "2880", "5760", "182,440", "362,880"]), answer: "C",
    solutionZh: ["把 2 本阿拉伯语书看成一组，4 本西班牙语书看成一组，再加上 3 本德语书，共 5 个对象。", "排法数为 5!×2!×4!=5760。"],
    solutionEn: ["Treat the Arabic books as one block and the Spanish books as one block, along with the three German books: five objects total.", "The count is 5!·2!·4!=5760."], sourceUrl,
  },
  {
    id: "2018-17", year: 2018, number: 17, status: "published",
    primaryTopic: "算术", secondaryTopics: ["代数"], skills: ["相遇问题", "速度比", "单位换算"], formats: ["文字应用题"], difficulty: 3,
    promptZh: "Bella 从家步行去 Ella 家，同时 Ella 骑车去 Bella 家。两人速度恒定，Ella 的速度是 Bella 的 5 倍。两家相距 2 英里（10,560 英尺），Bella 每步走 2.5 英尺。相遇前 Bella 走了多少步？",
    promptEn: "Bella walks toward Ella's house while Ella cycles toward Bella's. Ella travels five times as fast. Their homes are 2 miles (10,560 feet) apart, and Bella covers 2.5 feet per step. How many steps does Bella take before they meet?",
    options: numericOptions(["704", "845", "1056", "1760", "3520"]), answer: "A",
    solutionZh: ["两人速度比为 1:5，因此 Bella 走全程的 1/(1+5)=1/6，即 10,560÷6=1760 英尺。", "步数为 1760÷2.5=704。"],
    solutionEn: ["Their speeds are in ratio 1:5, so Bella covers 1/6 of 10,560 feet, or 1760 feet.", "At 2.5 feet per step, she takes 1760/2.5=704 steps."], sourceUrl,
  },
  {
    id: "2018-18", year: 2018, number: 18, status: "published",
    primaryTopic: "数论", skills: ["质因数分解", "约数个数"], formats: ["整数题"], difficulty: 3,
    promptZh: "23,232 有多少个正因数？",
    promptEn: "How many positive factors does 23,232 have?",
    options: numericOptions(["9", "12", "28", "36", "42"]), answer: "E",
    solutionZh: ["质因数分解得 23,232=2^6×3×11^2。", "正因数个数为 (6+1)(1+1)(2+1)=42。"],
    solutionEn: ["Prime factorization gives 23,232=2^6·3·11^2.", "Therefore it has (6+1)(1+1)(2+1)=42 positive factors."], sourceUrl,
  },
  {
    id: "2018-19", year: 2018, number: 19, status: "published",
    primaryTopic: "计数与组合", secondaryTopics: ["代数"], skills: ["奇偶性", "分类计数", "递推"], formats: ["规则图"], difficulty: 4,
    promptZh: "在符号金字塔中，若正下方两个格子的符号相同，上方格子填“+”；若不同，则填“-”。底层四格有多少种填法能使顶端为“+”？",
    promptEn: "In a sign pyramid, a cell is + when the two cells below have the same sign and − otherwise. How many fillings of the four bottom cells produce + at the top?",
    figure: { src: "/questions/2018/q19.png", altZh: "四层符号金字塔及其由下向上的生成规则示例。", altEn: "A four-level sign pyramid illustrating the rule used to generate each higher cell." },
    options: numericOptions(["2", "4", "8", "12", "16"]), answer: "C",
    solutionZh: ["把“-”看作 1、“+”看作 0，则生成规则等价于异或。四层金字塔顶端为“+”恰好对应底层负号个数为偶数。", "共有 C(4,0)+C(4,2)+C(4,4)=1+6+1=8 种。"],
    solutionEn: ["Encode − as 1 and + as 0; the rule becomes XOR. The top is + exactly when the bottom row has an even number of minus signs.", "The count is C(4,0)+C(4,2)+C(4,4)=8."], sourceUrl,
  },
  {
    id: "2018-20", year: 2018, number: 20, status: "published",
    primaryTopic: "几何", skills: ["相似三角形", "面积比", "平行线"], formats: ["几何图"], difficulty: 4,
    promptZh: "在△ABC 中，点 E 在 AB 上，AE=1、EB=2。点 D 在 AC 上且 DE∥BC；点 F 在 BC 上且 EF∥AC。四边形 CDEF 与△ABC 的面积之比是多少？",
    promptEn: "In triangle ABC, E lies on AB with AE=1 and EB=2. Point D lies on AC with DE parallel to BC, and F lies on BC with EF parallel to AC. What is the ratio [CDEF]/[ABC]?",
    figure: { src: "/questions/2018/q20.png", altZh: "三角形 ABC 内由过 E 的两条平行线形成四边形 CDEF。", altEn: "Triangle ABC with two parallels through E forming quadrilateral CDEF." },
    options: numericOptions(["4/9", "1/2", "5/9", "3/5", "2/3"]), answer: "A",
    solutionZh: ["AE/AB=1/3，所以相似三角形 ADE 的面积是 △ABC 的 1/9；EB/AB=2/3，所以相似三角形 EBF 的面积是 △ABC 的 4/9。", "四边形面积占比为 1-1/9-4/9=4/9。"],
    solutionEn: ["Since AE/AB=1/3, triangle ADE has 1/9 of the total area. Since EB/AB=2/3, triangle EBF has 4/9.", "The remaining quadrilateral has ratio 1-1/9-4/9=4/9."], sourceUrl,
  },
  {
    id: "2018-21", year: 2018, number: 21, status: "published",
    primaryTopic: "数论", skills: ["中国剩余定理", "最小公倍数", "同余"], formats: ["整数题"], difficulty: 4,
    promptZh: "有多少个三位正整数，除以 6 余 2、除以 9 余 5、除以 11 余 7？",
    promptEn: "How many positive three-digit integers leave remainder 2 when divided by 6, remainder 5 when divided by 9, and remainder 7 when divided by 11?",
    options: numericOptions(["1", "2", "3", "4", "5"]), answer: "E",
    solutionZh: ["三个条件都等价于 x+4 分别被 6、9、11 整除，所以 x+4 是 lcm(6,9,11)=198 的倍数。", "三位数范围内 x+4 可为 198、396、594、792、990，共 5 个。"],
    solutionEn: ["Each condition says x+4 is divisible by 6, 9, and 11, so x+4 is a multiple of 198.", "The possible values are 198, 396, 594, 792, and 990, giving 5 integers."], sourceUrl,
  },
  {
    id: "2018-22", year: 2018, number: 22, status: "published",
    primaryTopic: "几何", secondaryTopics: ["代数"], skills: ["坐标法", "面积分割", "中点"], formats: ["几何图"], difficulty: 4,
    promptZh: "点 E 是正方形 ABCD 的边 CD 的中点，BE 与对角线 AC 交于 F。四边形 AFED 的面积为 45，正方形 ABCD 的面积是多少？",
    promptEn: "Point E is the midpoint of CD in square ABCD, and BE meets diagonal AC at F. Quadrilateral AFED has area 45. What is the area of ABCD?",
    figure: { src: "/questions/2018/q22.png", altZh: "正方形 ABCD 中，E 为 CD 中点，BE 与 AC 交于 F。", altEn: "Square ABCD with E the midpoint of CD and BE intersecting AC at F." },
    options: numericOptions(["100", "108", "120", "135", "144"]), answer: "B",
    solutionZh: ["设正方形边长为 s。用坐标或相似关系可得 F 把相关线段按 2:1 分割，四边形 AFED 的面积为 5s²/12。", "由 5s²/12=45，得 s²=108。"],
    solutionEn: ["Let the side length be s. Coordinates or similarity show that quadrilateral AFED has area 5s²/12.", "From 5s²/12=45, we get s²=108."], sourceUrl,
  },
  {
    id: "2018-23", year: 2018, number: 23, status: "published",
    primaryTopic: "概率", secondaryTopics: ["计数与组合", "几何"], skills: ["补集", "圆排列", "组合计数"], formats: ["几何概率题"], difficulty: 4,
    promptZh: "从正八边形的 8 个顶点中随机选 3 个连成三角形。该三角形至少有一条边也是正八边形边的概率是多少？",
    promptEn: "Three vertices of a regular octagon are chosen at random to form a triangle. What is the probability that at least one side of the triangle is also a side of the octagon?",
    figure: { src: "/questions/2018/q23.png", altZh: "标有八个顶点的正八边形。", altEn: "A regular octagon with its eight vertices marked." },
    options: numericOptions(["2/7", "5/42", "11/14", "5/7", "6/7"]), answer: "D",
    solutionZh: ["全部三角形有 C(8,3)=56 个。补集是所选三点中没有相邻顶点；在圆周上选 3 个互不相邻顶点共有 16 种。", "所求概率为 1-16/56=5/7。"],
    solutionEn: ["There are C(8,3)=56 triangles. The complement has no adjacent chosen vertices; there are 16 such triples on an 8-cycle.", "Thus the probability is 1-16/56=5/7."], sourceUrl,
  },
  {
    id: "2018-24", year: 2018, number: 24, status: "published",
    primaryTopic: "几何", secondaryTopics: ["代数"], skills: ["空间几何", "截面", "勾股定理", "菱形面积"], formats: ["立体几何图"], difficulty: 5,
    promptZh: "在立方体 ABCDEFGH 中，C 与 E 为相对顶点，I、J 分别是 FB、HD 的中点。设截面 EJCI 的面积与立方体一个面的面积之比为 R，求 R²。",
    promptEn: "In cube ABCDEFGH, C and E are opposite vertices, and I and J are the midpoints of FB and HD. Let R be the ratio of the area of cross-section EJCI to a face. What is R²?",
    figure: { src: "/questions/2018/q24.png", altZh: "立方体内经过 E、J、C、I 的菱形截面。", altEn: "A cube with rhombus cross-section EJCI." },
    options: numericOptions(["5/4", "4/3", "3/2", "25/16", "9/4"]), answer: "C",
    solutionZh: ["设立方体边长为 s。截面 EJCI 是菱形，两条对角线分别为 s√2 和 s√3。", "截面面积为 (s√2)(s√3)/2=s²√6/2，所以 R=√6/2，R²=3/2。"],
    solutionEn: ["Let the cube edge be s. The rhombus EJCI has diagonals s√2 and s√3.", "Its area is s²√6/2, so R=√6/2 and R²=3/2."], sourceUrl,
  },
  {
    id: "2018-25", year: 2018, number: 25, status: "published",
    primaryTopic: "数论", skills: ["完全立方数", "指数范围", "计数"], formats: ["整数题"], difficulty: 4,
    promptZh: "在 2^8+1 与 2^18+1 之间（含端点）有多少个完全立方数？",
    promptEn: "How many perfect cubes lie between 2^8+1 and 2^18+1, inclusive?",
    options: numericOptions(["4", "9", "10", "57", "58"]), answer: "E",
    solutionZh: ["2^8+1=257，而 6³=216<257<7³=343；2^18+1=262145，而 64³=262144。", "因此符合条件的是 7³ 到 64³，共 64-7+1=58 个。"],
    solutionEn: ["The lower bound lies between 6³ and 7³, while 64³=262144 is below the upper bound 262145.", "Thus the cubes run from 7³ through 64³, for 64-7+1=58."], sourceUrl,
  },
];
