import type { Question, QuestionOption } from "./questions";

const numericOptions = (values: string[]): QuestionOption[] =>
  values.map((value, index) => ({
    label: String.fromCharCode(65 + index) as QuestionOption["label"],
    valueZh: value,
  }));

const sourceUrl = "https://live.poshenloh.com/past-contests/amc8/2025";

export const questions2025: Question[] = [
  {
    id: "2025-01",
    year: 2025,
    number: 1,
    status: "published",
    primaryTopic: "几何",
    skills: ["面积计算", "对称性"],
    formats: ["几何图"],
    difficulty: 1,
    promptZh: "下图所示的八角星是一种常见的拼布图案。整个 4×4 方格中有百分之多少被星形覆盖？",
    promptEn: "The eight-pointed star, shown in the figure below, is a popular quilting pattern. What percent of the entire 4-by-4 grid is covered by the star?",
    figure: {
      src: "/questions/2025/q01.png",
      altZh: "一个 4×4 方格中的八角星阴影图案。",
      altEn: "An eight-pointed shaded star inside a 4-by-4 grid.",
    },
    options: numericOptions(["40%", "50%", "60%", "75%", "80%"]),
    answer: "B",
    solutionZh: [
      "图案关于水平线和竖直线都对称，因此只需观察左上角的 2×2 区域。",
      "把该区域中的一个三角形平移后，可以看出阴影恰好占这一部分的一半，因此整个方格的阴影比例也是 50%。",
    ],
    solutionEn: [
      "By symmetry, it is enough to examine the upper-left quarter of the grid.",
      "Rearranging one triangular piece shows that exactly half of that quarter is shaded, so the whole grid is 50% shaded.",
    ],
    sourceUrl,
  },
  {
    id: "2025-02",
    year: 2025,
    number: 2,
    status: "published",
    primaryTopic: "算术",
    skills: ["位值", "读图"],
    formats: ["符号表"],
    difficulty: 1,
    promptZh: "古埃及人用图中的象形符号表示不同的数。根据符号表、示例和最后一组象形符号，最后一组表示哪个数？",
    promptEn: "The table shows the ancient Egyptian hieroglyphs used for different place values. What number is represented by the final combination of hieroglyphs?",
    figure: {
      src: "/questions/2025/q02.png",
      altZh: "古埃及数字符号表：不同符号分别表示 100000、10000、1000、100、10、1；下方给出 32 的示例和待识别符号。",
      altEn: "An Egyptian numeral key for 100000, 10000, 1000, 100, 10, and 1, followed by an example and the numeral to decode.",
    },
    options: numericOptions(["1,423", "10,423", "14,023", "14,203", "14,230"]),
    answer: "B",
    solutionZh: [
      "待识别图案中有 1 个表示 10,000 的符号、4 个表示 100 的符号、2 个表示 10 的符号和 3 个表示 1 的符号。",
      "所以它表示 10,000 + 400 + 20 + 3 = 10,423。",
    ],
    solutionEn: [
      "There is one 10,000 glyph, four 100 glyphs, two 10 glyphs, and three 1 glyphs.",
      "The value is 10,000 + 400 + 20 + 3 = 10,423.",
    ],
    sourceUrl,
  },
  {
    id: "2025-03",
    year: 2025,
    number: 3,
    status: "published",
    primaryTopic: "算术",
    skills: ["比例", "乘除法"],
    formats: ["文字应用题"],
    difficulty: 1,
    promptZh: "在 Buffalo Shuffle-o 纸牌游戏中，所有牌会平均分给玩家。Annika 和她的 3 位朋友游戏时，每人得到 15 张牌。下一局又加入 2 位朋友，每人会得到多少张牌？",
    promptEn: "In Buffalo Shuffle-o, all cards are distributed evenly. When Annika and 3 friends play, each gets 15 cards. If 2 more friends join, how many cards will each player get?",
    options: numericOptions(["8", "9", "10", "11", "12"]),
    answer: "C",
    solutionZh: [
      "原来共有 4 人，所以牌的总数为 4×15=60。",
      "加入 2 人后共有 6 人，每人得到 60÷6=10 张。",
    ],
    solutionEn: [
      "Originally there are 4 players and 4·15 = 60 cards.",
      "With 6 players, each receives 60÷6 = 10 cards.",
    ],
    sourceUrl,
  },
  {
    id: "2025-04",
    year: 2025,
    number: 4,
    status: "published",
    primaryTopic: "算术",
    secondaryTopics: ["代数"],
    skills: ["数列", "计算"],
    formats: ["文字题"],
    difficulty: 1,
    promptZh: "Lucius 从 100 开始每次倒数 7。他的前三个数是 100、93、86。第 10 个数是多少？",
    promptEn: "Lucius is counting backward by 7s. His first three numbers are 100, 93, and 86. What is his 10th number?",
    options: numericOptions(["30", "37", "42", "44", "47"]),
    answer: "B",
    solutionZh: [
      "从第 1 个数到第 10 个数之间有 9 个间隔。",
      "因此第 10 个数是 100-9×7=37。",
    ],
    solutionEn: [
      "There are 9 gaps from the first term to the tenth term.",
      "The tenth number is 100 - 9·7 = 37.",
    ],
    sourceUrl,
  },
  {
    id: "2025-05",
    year: 2025,
    number: 5,
    status: "published",
    primaryTopic: "几何",
    secondaryTopics: ["算术"],
    skills: ["曼哈顿距离", "读图"],
    formats: ["方格路线图"],
    difficulty: 2,
    promptZh: "Betty 从工厂 F 出发，依次到 A、B、C，最后返回 F。她完成这条路线至少要行驶多少个街区？",
    promptEn: "Betty starts at factory F and drives to A, then B, then C, before returning to F. What is the shortest distance, in blocks, she can drive?",
    figure: {
      src: "/questions/2025/q05.png",
      altZh: "方格街道图，标有地点 F、A、B、C，每个方格边长为一个街区。",
      altEn: "A rectangular street grid with locations F, A, B, and C marked; each grid edge is one block.",
    },
    options: numericOptions(["20", "22", "24", "26", "28"]),
    answer: "C",
    solutionZh: [
      "方格街道上的最短距离等于横向街区数与纵向街区数之和。",
      "F→A、A→B、B→C、C→F 的最短距离依次为 3、10、6、5。",
      "总距离为 3+10+6+5=24 个街区。",
    ],
    solutionEn: [
      "On a street grid, the shortest distance is the horizontal change plus the vertical change.",
      "The four legs have lengths 3, 10, 6, and 5, for a total of 24 blocks.",
    ],
    sourceUrl,
  },
  {
    id: "2025-06",
    year: 2025,
    number: 6,
    status: "published",
    primaryTopic: "数论",
    secondaryTopics: ["算术"],
    skills: ["整除", "模运算"],
    formats: ["数字列表"],
    difficulty: 2,
    promptZh: "Sekou 写下 15、16、17、18、19。擦去其中一个数后，其余四个数的和是 4 的倍数。他擦去了哪个数？",
    promptEn: "Sekou writes 15, 16, 17, 18, and 19. After erasing one number, the sum of the remaining four is a multiple of 4. Which number did he erase?",
    options: numericOptions(["15", "16", "17", "18", "19"]),
    answer: "C",
    solutionZh: [
      "五个数的总和是 85，除以 4 余 1。",
      "要让剩余的和能被 4 整除，必须擦去一个除以 4 也余 1 的数，即 17。",
    ],
    solutionEn: [
      "The five numbers sum to 85, which is 1 modulo 4.",
      "The erased number must also be 1 modulo 4, so it is 17.",
    ],
    sourceUrl,
  },
  {
    id: "2025-07",
    year: 2025,
    number: 7,
    status: "published",
    primaryTopic: "数据与统计",
    skills: ["集合差", "读数据"],
    formats: ["数据列表"],
    difficulty: 1,
    promptZh: "Xochi 教授最近一次考试中，有 5 人至少得 95%，13 人至少得 90%，27 人至少得 85%，50 人至少得 80%。有多少人的成绩至少为 80% 但低于 90%？",
    promptEn: "On Prof. Xochi’s exam, 5 students scored at least 95%, 13 at least 90%, 27 at least 85%, and 50 at least 80%. How many scored at least 80% but less than 90%?",
    options: numericOptions(["8", "14", "22", "37", "45"]),
    answer: "D",
    solutionZh: [
      "至少得 80% 的 50 人中包含至少得 90% 的 13 人。",
      "所求人数为 50-13=37。",
    ],
    solutionEn: [
      "The 50 students scoring at least 80% include the 13 scoring at least 90%.",
      "The requested number is 50 - 13 = 37.",
    ],
    sourceUrl,
  },
  {
    id: "2025-08",
    year: 2025,
    number: 8,
    status: "published",
    primaryTopic: "几何",
    skills: ["立体展开图", "体积计算"],
    formats: ["立体展开图"],
    difficulty: 2,
    promptZh: "Isaiah 沿纸板正方体的一些棱剪开，得到图中的展开图。展开图的面积是 18 平方厘米。原正方体的体积是多少立方厘米？",
    promptEn: "Isaiah cuts open a cardboard cube along some edges to form the shown net, which has area 18 square centimeters. What was the cube’s volume?",
    figure: {
      src: "/questions/2025/q08.png",
      altZh: "由六个全等正方形组成的正方体展开图。",
      altEn: "A cube net made of six congruent squares.",
    },
    options: numericOptions(["3√3", "6", "9", "6√3", "9√3"]),
    answer: "A",
    solutionZh: [
      "展开图由 6 个全等正方形组成，所以每个面的面积为 18÷6=3。",
      "正方体棱长为 √3，体积为 (√3)³=3√3。",
    ],
    solutionEn: [
      "The net has six congruent faces, so each face has area 18÷6 = 3.",
      "The edge length is √3, and the volume is (√3)³ = 3√3.",
    ],
    sourceUrl,
  },
  {
    id: "2025-09",
    year: 2025,
    number: 9,
    status: "published",
    primaryTopic: "数据与统计",
    secondaryTopics: ["算术"],
    skills: ["平均数", "等差数列"],
    formats: ["钟面图"],
    difficulty: 2,
    promptZh: "Ningli 把钟面上彼此正对的 6 对数字分别求平均。所得 6 个数的平均数是多少？",
    promptEn: "Ningli takes the average of each of the 6 pairs of numbers directly across from each other on a clock. What is the average of the resulting 6 numbers?",
    figure: {
      src: "/questions/2025/q09.png",
      altZh: "标有 1 到 12 的钟面，其中一条虚线连接一对相对数字。",
      altEn: "A clock face labeled 1 through 12 with a dashed diameter joining an opposite pair.",
    },
    options: numericOptions(["5", "6.5", "8", "9.5", "12"]),
    answer: "B",
    solutionZh: [
      "先对每一对求平均，再对这 6 个平均数求平均，与直接求 1 到 12 的平均数相同。",
      "1 到 12 是等差数列，平均数为 (1+12)÷2=6.5。",
    ],
    solutionEn: [
      "Averaging the six pair averages gives the same result as averaging all twelve numbers.",
      "The mean of 1 through 12 is (1 + 12)÷2 = 6.5.",
    ],
    sourceUrl,
  },
  {
    id: "2025-10",
    year: 2025,
    number: 10,
    status: "published",
    primaryTopic: "几何",
    skills: ["旋转", "容斥原理", "面积计算"],
    formats: ["几何图"],
    difficulty: 3,
    promptZh: "长方形 ABCD 的边长 AB=5 英寸、AD=3 英寸。把它绕边 DC 的中点顺时针旋转 90°，得到第二个长方形。两个重叠长方形覆盖的总面积是多少平方英寸？",
    promptEn: "Rectangle ABCD has AB = 5 and AD = 3. It is rotated 90° clockwise about the midpoint of DC. What total area is covered by the two overlapping rectangles?",
    figure: {
      src: "/questions/2025/q10.png",
      altZh: "一个 5×3 长方形绕底边中点顺时针旋转 90 度后与原图重叠。",
      altEn: "A 5-by-3 rectangle and its 90-degree rotation about the midpoint of the lower side.",
    },
    options: numericOptions(["21", "22.25", "23", "23.75", "25"]),
    answer: "D",
    solutionZh: [
      "两个长方形的面积都为 5×3=15。",
      "重叠部分是边长 2.5 的正方形，面积为 6.25。",
      "用容斥原理得总覆盖面积 15+15-6.25=23.75。",
    ],
    solutionEn: [
      "Each rectangle has area 15.",
      "Their overlap is a 2.5-by-2.5 square of area 6.25.",
      "The union has area 15 + 15 - 6.25 = 23.75.",
    ],
    sourceUrl,
  },
  {
    id: "2025-11",
    year: 2025,
    number: 11,
    status: "published",
    primaryTopic: "几何",
    secondaryTopics: ["计数与组合"],
    skills: ["拼图", "空间想象"],
    formats: ["几何图"],
    difficulty: 3,
    promptZh: "四连方由 4 个沿边相连的小正方形组成，共有图示的 I、O、L、T、S 五种形状，可旋转或翻转。用 3 块四连方恰好铺满一个 3×4 长方形，其中至少一块是 S。另两块是什么？",
    promptEn: "Three tetrominoes tile a 3-by-4 rectangle. At least one tile is an S tetromino. What are the other two tiles?",
    figure: {
      src: "/questions/2025/q11.png",
      altZh: "I、O、L、T、S 五种四连方的形状。",
      altEn: "The five tetromino shapes I, O, L, T, and S.",
    },
    options: [
      { label: "A", valueZh: "I 和 L", valueEn: "I and L" },
      { label: "B", valueZh: "I 和 T", valueEn: "I and T" },
      { label: "C", valueZh: "L 和 L", valueEn: "L and L" },
      { label: "D", valueZh: "L 和 S", valueEn: "L and S" },
      { label: "E", valueZh: "O 和 T", valueEn: "O and T" },
    ],
    answer: "C",
    solutionZh: [
      "先把 S 形放在 3×4 长方形的一侧，使它不把剩余区域分断。",
      "剩余的 8 个小方格可以恰好分成两个 L 形四连方，因此另两块都是 L。",
    ],
    solutionEn: [
      "Place the S tetromino so that it does not disconnect the remaining region.",
      "The remaining eight cells split into two L tetrominoes, so the other tiles are L and L.",
    ],
    sourceUrl,
  },
  {
    id: "2025-12",
    year: 2025,
    number: 12,
    status: "published",
    primaryTopic: "几何",
    skills: ["勾股定理", "圆面积"],
    formats: ["方格几何图"],
    difficulty: 3,
    promptZh: "图中区域由 24 个边长为 1 厘米的正方形组成。能放入该区域、且可以与边界相切的最大圆的面积是多少平方厘米？",
    promptEn: "The region consists of 24 unit squares. What is the area of the largest circle that can fit inside the region, possibly touching its boundaries?",
    figure: {
      src: "/questions/2025/q12.png",
      altZh: "由 24 个单位正方形组成、近似圆形的对称方格区域。",
      altEn: "A symmetric region of 24 unit squares arranged in a roughly circular shape.",
    },
    options: numericOptions(["3π", "4π", "5π", "6π", "8π"]),
    answer: "C",
    solutionZh: [
      "距离中心最近的凹角与中心横向相差 1、纵向相差 2。",
      "最大圆的半径为 √(1²+2²)=√5，所以面积为 π(√5)²=5π。",
    ],
    solutionEn: [
      "The nearest inward corners are one unit horizontally and two units vertically from the center.",
      "The maximum radius is √(1²+2²) = √5, so the area is 5π.",
    ],
    sourceUrl,
  },
  {
    id: "2025-13",
    year: 2025,
    number: 13,
    status: "published",
    primaryTopic: "数论",
    secondaryTopics: ["数据与统计"],
    skills: ["找规律", "逻辑推理"],
    formats: ["统计图"],
    difficulty: 3,
    promptZh: "将偶数 2、4、6、…、50 分别除以 7，并记录所得余数。下列哪幅直方图表示每种余数出现的次数？",
    promptEn: "Each of the even numbers 2, 4, 6, …, 50 is divided by 7. The remainders are recorded. Which histogram displays the number of times each remainder occurs?",
    options: [
      { label: "A", valueZh: "图 A", histogram: [3, 4, 4, 3, 4, 3, 4] },
      { label: "B", valueZh: "图 B", histogram: [3, 4, 4, 4, 3, 3, 4] },
      { label: "C", valueZh: "图 C", histogram: [3, 4, 4, 4, 4, 3, 3] },
      { label: "D", valueZh: "图 D", histogram: [4, 3, 4, 3, 4, 3, 4] },
      { label: "E", valueZh: "图 E", histogram: [4, 4, 3, 4, 3, 4, 3] },
    ],
    answer: "A",
    solutionZh: [
      "余数按 2、4、6、1、3、5、0 的顺序循环。",
      "25 个偶数包含 3 个完整循环，另有余数 2、4、6、1，所以这四种余数各出现 4 次，其余各出现 3 次，对应图 A。",
    ],
    solutionEn: [
      "The remainders repeat as 2, 4, 6, 1, 3, 5, 0.",
      "After three full cycles, the four extras are 2, 4, 6, and 1, giving option A.",
    ],
    sourceUrl,
  },
  {
    id: "2025-14",
    year: 2025,
    number: 14,
    status: "published",
    primaryTopic: "数据与统计",
    secondaryTopics: ["代数"],
    skills: ["平均数", "中位数", "列方程"],
    formats: ["数字列表"],
    difficulty: 3,
    promptZh: "把一个数 N 插入列表 2、6、7、7、28 后，新的平均数恰好是中位数的 2 倍。N 是多少？",
    promptEn: "A number N is inserted into the list 2, 6, 7, 7, 28. The mean is now twice the median. What is N?",
    options: numericOptions(["7", "14", "20", "28", "34"]),
    answer: "E",
    solutionZh: [
      "所有选项都不小于 7，插入后中间两个数仍是 7 和 7，所以中位数为 7。",
      "平均数应为 14，六个数的总和应为 6×14=84。原列表和为 50，因此 N=84-50=34。",
    ],
    solutionEn: [
      "Every choice is at least 7, so the two middle values remain 7 and 7; the median is 7.",
      "The mean is 14, so the total is 84. Since the original sum is 50, N = 34.",
    ],
    sourceUrl,
  },
  {
    id: "2025-15",
    year: 2025,
    number: 15,
    status: "published",
    primaryTopic: "计数与组合",
    skills: ["极值", "配对"],
    formats: ["方格图"],
    difficulty: 3,
    promptZh: "Kei 在 6×6 方格中把 13 个单位方格涂成银色，其余涂成金色，再沿竖直中线对折，形成 18 对重叠方格。设金色与金色重叠的最少、最多对数分别为 m、M。m+M 等于多少？",
    promptEn: "Kei colors 13 squares silver in a 6-by-6 grid and the rest gold, then folds it vertically. If m and M are the least and greatest possible numbers of gold-on-gold pairs, what is m+M?",
    figure: {
      src: "/questions/2025/q15.png",
      altZh: "一个 6×6 方格，竖直虚线标出对折线。",
      altEn: "A 6-by-6 grid with a dashed vertical fold line.",
    },
    options: numericOptions(["12", "14", "16", "18", "20"]),
    answer: "C",
    solutionZh: [
      "共有 23 个金色方格和 18 对位置。要使金金对最少，先让 18 对各放一个金色，余下 5 个只能与金色重叠，所以 m=5。",
      "要使金金对最多，把金色尽量两两配对，得到 M=⌊23/2⌋=11。",
      "因此 m+M=5+11=16。",
    ],
    solutionEn: [
      "There are 23 gold squares and 18 pairs. Spreading one gold square into every pair leaves 5 forced gold-gold pairs, so m = 5.",
      "Pairing gold squares together as much as possible gives M = floor(23/2) = 11. Thus m+M = 16.",
    ],
    sourceUrl,
  },
  {
    id: "2025-16",
    year: 2025,
    number: 16,
    status: "published",
    primaryTopic: "计数与组合",
    secondaryTopics: ["数论"],
    skills: ["配对", "补集"],
    formats: ["文字题"],
    difficulty: 3,
    promptZh: "从 1 到 10 中选 5 个不同整数，再从 11 到 20 中选 5 个不同整数，且任意两数之差都不等于 10。所选 10 个数的和是多少？",
    promptEn: "Five distinct integers from 1 to 10 and five from 11 to 20 are chosen. No two numbers differ by exactly 10. What is the sum of the ten chosen numbers?",
    options: numericOptions(["95", "100", "105", "110", "115"]),
    answer: "C",
    solutionZh: [
      "把数配成 (1,11)、(2,12)、…、(10,20)。限制条件说明每一对最多选一个。",
      "总共要选 10 个数，因此每一对恰选一个。若选上半区的数，它比对应下半区的数大 10；恰有 5 个上半区数。",
      "所以总和为 (1+2+…+10)+5×10=55+50=105。",
    ],
    solutionEn: [
      "Pair the numbers as (1,11), …, (10,20). At most one number may be chosen from each pair, and ten choices force exactly one from every pair.",
      "Five choices are from the upper range, each 10 above its partner, so the sum is 55 + 5·10 = 105.",
    ],
    sourceUrl,
  },
  {
    id: "2025-17",
    year: 2025,
    number: 17,
    status: "published",
    primaryTopic: "算术",
    secondaryTopics: ["数据与统计"],
    skills: ["比例", "信息整合"],
    formats: ["有向图"],
    difficulty: 3,
    promptZh: "Markovia 有 A、B、C 三座城市，分别居住 100、120、160 人。图中从一座城市指向另一座的箭头标出前者居民中到后者工作的人数比例。共有多少人在 A 城工作？",
    promptEn: "Markovia has cities A, B, and C with 100, 120, and 160 residents. Each arrow gives the fraction of residents of one city who work in another. How many people work in A?",
    figure: {
      src: "/questions/2025/q17.png",
      altZh: "城市 A、B、C 构成的有向图，六条箭头分别标有 1/4、1/3、1/5、1/8、1/10、1/6。",
      altEn: "A directed graph among cities A, B, and C with arrows labeled 1/4, 1/3, 1/5, 1/8, 1/10, and 1/6.",
    },
    options: numericOptions(["55", "60", "85", "115", "160"]),
    answer: "D",
    solutionZh: [
      "A 城居民中留在 A 工作的有 100-100×1/4-100×1/5=55 人。",
      "B 城居民中有 120×1/3=40 人在 A 工作，C 城居民中有 160×1/8=20 人在 A 工作。",
      "总人数为 55+40+20=115。",
    ],
    solutionEn: [
      "Among A residents, 100 - 25 - 20 = 55 work in A.",
      "Also, 120·(1/3) = 40 residents of B and 160·(1/8) = 20 residents of C work in A.",
      "The total is 55 + 40 + 20 = 115.",
    ],
    sourceUrl,
  },
  {
    id: "2025-18",
    year: 2025,
    number: 18,
    status: "published",
    primaryTopic: "几何",
    skills: ["相似", "面积缩放"],
    formats: ["几何图"],
    difficulty: 3,
    promptZh: "左图圆的半径为 1，圆与内接正方形之间的全部区域被涂色。右图只涂了圆与内接正方形之间区域的四分之一，且两图涂色面积相同。右图圆的半径 R 是多少？",
    promptEn: "The left circle has radius 1 and all the area outside its inscribed square is shaded. On the right, one quarter of that gap is shaded. The shaded areas are equal. What is radius R?",
    figure: {
      src: "/questions/2025/q18.png",
      altZh: "两个带内接正方形的圆；左图四周全部涂色，右图只涂右侧四分之一。",
      altEn: "Two circles with inscribed squares; the full gap is shaded on the left and one quarter on the right.",
    },
    options: numericOptions(["√2", "2", "2√2", "4", "4√2"]),
    answer: "B",
    solutionZh: [
      "右图只取整体空隙的四分之一，要与左图整个空隙等面积，右图完整空隙面积必须是左图的 4 倍。",
      "相似图形面积按半径平方缩放，所以 R²=4×1²，得到 R=2。",
    ],
    solutionEn: [
      "Since only one quarter is shaded on the right, its whole gap must have four times the area of the left gap.",
      "Areas of similar figures scale with the square of radius, so R² = 4 and R = 2.",
    ],
    sourceUrl,
  },
  {
    id: "2025-19",
    year: 2025,
    number: 19,
    status: "published",
    primaryTopic: "算术",
    secondaryTopics: ["代数"],
    skills: ["速度时间路程", "分段分析"],
    formats: ["线段示意图"],
    difficulty: 4,
    promptZh: "A、B 两镇之间的直路长 15 英里。从 A 到 B，每 5 英里限速依次为 25、40、20 英里/时。两辆车同时从 A、B 相向出发，并始终按所在路段限速行驶。它们在距 A 多少英里处相遇？",
    promptEn: "A 15-mile road has successive 5-mile speed limits of 25, 40, and 20 mph from A to B. Cars start simultaneously from A and B toward each other. How far from A do they meet?",
    figure: {
      src: "/questions/2025/q19.png",
      altZh: "从 A 到 B 的 15 英里道路分成三段，每段 5 英里，限速依次为 25、40、20 英里每小时。",
      altEn: "A 15-mile road from A to B split into three 5-mile sections with limits 25, 40, and 20 mph.",
    },
    options: numericOptions(["7.75", "8", "8.25", "8.5", "8.75"]),
    answer: "D",
    solutionZh: [
      "A 车用 5/25=1/5 小时进入中段；B 车用 5/20=1/4 小时进入中段。",
      "当 B 车进入中段时，A 车已在中段行驶 1/20 小时，走了 2 英里，因此两车在中段还相距 3 英里。",
      "两车在中段速度相同，各走 1.5 英里后相遇。相遇点距 A 为 5+2+1.5=8.5 英里。",
    ],
    solutionEn: [
      "The A car reaches the middle section in 1/5 hour; the B car reaches it in 1/4 hour.",
      "By then the A car has traveled 2 miles into the middle, leaving 3 miles between them.",
      "At equal speeds they each cover 1.5 miles, so the meeting point is 5 + 2 + 1.5 = 8.5 miles from A.",
    ],
    sourceUrl,
  },
  {
    id: "2025-20",
    year: 2025,
    number: 20,
    status: "published",
    primaryTopic: "代数",
    secondaryTopics: ["算术"],
    skills: ["等比数列", "无限级数"],
    formats: ["文字应用题"],
    difficulty: 4,
    promptZh: "Sarika、Dev、Rajiv 轮流吃一大块奶酪，每次吃掉剩余部分的一半，顺序不断重复。直到奶酪小到看不见为止，Sarika 总共大约吃了原来奶酪的几分之几？",
    promptEn: "Sarika, Dev, and Rajiv repeatedly take turns eating half of the remaining cheese. About what fraction of the original block does Sarika eat in total?",
    options: numericOptions(["4/7", "3/5", "2/3", "3/4", "7/8"]),
    answer: "A",
    solutionZh: [
      "Sarika 吃到的份额为 1/2+1/16+1/128+…，相邻两项比为 1/8。",
      "无限等比级数的和为 (1/2)÷(1-1/8)=4/7。",
    ],
    solutionEn: [
      "Sarika’s shares are 1/2 + 1/16 + 1/128 + …, a geometric series with ratio 1/8.",
      "Its sum is (1/2)/(1 - 1/8) = 4/7.",
    ],
    sourceUrl,
  },
  {
    id: "2025-21",
    year: 2025,
    number: 21,
    status: "published",
    primaryTopic: "计数与组合",
    skills: ["图论", "约束推理", "分类讨论"],
    formats: ["网络图"],
    difficulty: 5,
    promptZh: "学校把 1 到 7 年级分别安排给 A 到 G 七个舱室。图中相连的两个舱室所分配年级至少相差 2。舱室 C、E、F 的年级之和是多少？",
    promptEn: "Grades 1 through 7 are assigned to pods A through G. Connected pods must differ by at least 2 grade levels. What is the sum of the grades assigned to C, E, and F?",
    figure: {
      src: "/questions/2025/q21.png",
      altZh: "A 到 G 七个顶点组成的网络图，边表示舱室间的步道。",
      altEn: "A graph of seven pods A through G, with edges representing walkways.",
    },
    options: numericOptions(["12", "13", "14", "15", "16"]),
    answer: "A",
    solutionZh: [
      "A、B、C、F 两两相连，只能分配彼此至少相差 2 的四个数 {1,3,5,7}；D、E、G 因而取 {2,4,6}。",
      "G 不能取 4，否则其相邻点 A、F 被迫取 1、7，剩余约束使 E 无法分配。",
      "若 G=2，约束推出 F=7、C=1、E=4；若 G=6 则对称地得到 F=1、C=7、E=4。两种情形都有 C+E+F=12。",
    ],
    solutionEn: [
      "A, B, C, and F are pairwise adjacent, so they must receive {1,3,5,7}; D, E, and G receive {2,4,6}.",
      "G cannot be 4. If G = 2, the constraints force F = 7, C = 1, E = 4; the G = 6 case is symmetric.",
      "In either case C + E + F = 12.",
    ],
    sourceUrl,
  },
  {
    id: "2025-22",
    year: 2025,
    number: 22,
    status: "published",
    primaryTopic: "数论",
    secondaryTopics: ["计数与组合"],
    skills: ["因数个数", "建模"],
    formats: ["文字应用题"],
    difficulty: 4,
    promptZh: "教室里一排有 35 个挂钩。Paulina 要求第一件外套前、最后一件外套后以及相邻外套之间的空挂钩数都相同，并且至少有 1 件外套、每段至少有 1 个空挂钩。符合要求的外套数量共有多少种？",
    promptEn: "A row has 35 hooks. Coats are equally spaced with the same positive number of empty hooks before, after, and between coats. How many different numbers of coats are possible?",
    options: numericOptions(["2", "4", "5", "7", "9"]),
    answer: "D",
    solutionZh: [
      "在末尾再想象增加一个挂着外套的挂钩，就得到 36 个位置组成的重复区块。设每块长度为 b、区块数为 d，则 bd=36，且 b,d≥2。",
      "36=2²×3² 有 (2+1)(2+1)=9 个正因数。去掉 b=1 和 d=1 两种情形，剩 7 种，对应 7 种外套数量。",
    ],
    solutionEn: [
      "Add one imaginary occupied hook at the end. The 36 positions split into d equal blocks of length b, so bd = 36 with b,d ≥ 2.",
      "Since 36 has 9 positive divisors, excluding the two factorizations using 1 leaves 7 possible coat counts.",
    ],
    sourceUrl,
  },
  {
    id: "2025-23",
    year: 2025,
    number: 23,
    status: "published",
    primaryTopic: "数论",
    skills: ["质数", "平方差", "分类枚举"],
    formats: ["条件列表"],
    difficulty: 4,
    promptZh: "有多少个四位数同时满足：十位和个位都是 9；它比某个完全平方数小 1；它恰好是两个质数的乘积？",
    promptEn: "How many four-digit numbers end in 99, are one less than a perfect square, and are the product of exactly two primes?",
    options: numericOptions(["0", "1", "2", "3", "4"]),
    answer: "B",
    solutionZh: [
      "若该数为 a²-1 且末两位是 99，则 a² 末两位是 00，所以 a 是 40、50、60、70、80、90、100 之一。",
      "又有 a²-1=(a-1)(a+1)。要恰为两个质数的乘积，a-1 与 a+1 都必须是质数。",
      "只有 a=60 时得到质数 59 和 61，因此只有一个数 59×61=3599。",
    ],
    solutionEn: [
      "If the number is a² - 1 and ends in 99, then a is one of 40, 50, 60, 70, 80, 90, 100.",
      "Because a² - 1 = (a-1)(a+1), both neighboring numbers must be prime.",
      "Only a = 60 works, giving 59·61 = 3599, so there is one number.",
    ],
    sourceUrl,
  },
  {
    id: "2025-24",
    year: 2025,
    number: 24,
    status: "published",
    primaryTopic: "几何",
    secondaryTopics: ["数论"],
    skills: ["等边三角形", "整数方程", "分类枚举"],
    formats: ["几何图"],
    difficulty: 5,
    promptZh: "梯形 ABCD 中，∠B=∠C=60°，且 AB=DC。四条边长均为正整数，周长为 30。满足条件且不全等的梯形有多少个？",
    promptEn: "In trapezoid ABCD, angles B and C are 60° and AB = DC. All side lengths are positive integers and the perimeter is 30. How many noncongruent trapezoids satisfy the conditions?",
    figure: {
      src: "/questions/2025/q24.png",
      altZh: "等腰梯形 ABCD，两腰相等，两个下底角均为 60 度。",
      altEn: "An isosceles trapezoid ABCD with equal legs and both lower angles equal to 60 degrees.",
    },
    options: numericOptions(["0", "1", "2", "3", "4"]),
    answer: "E",
    solutionZh: [
      "过 A 作与 CD 平行的线交 BC 于 E，可得三角形 ABE 为等边三角形。设等腰及 BE 为 x，平行四边形部分的边为 y。",
      "梯形周长为 3x+2y=30，其中 x、y 为正整数。",
      "x 必须是小于 10 的正偶数，即 2、4、6、8，每个都唯一确定正整数 y，所以共有 4 个不全等梯形。",
    ],
    solutionEn: [
      "A parallel construction creates an equilateral triangle of side x and a parallelogram portion with side y.",
      "The perimeter condition becomes 3x + 2y = 30 for positive integers x,y.",
      "The valid x values are 2, 4, 6, and 8, giving four noncongruent trapezoids.",
    ],
    sourceUrl,
  },
  {
    id: "2025-25",
    year: 2025,
    number: 25,
    status: "published",
    primaryTopic: "计数与组合",
    secondaryTopics: ["几何"],
    skills: ["对称性", "二项式系数", "路径计数"],
    formats: ["路径图"],
    difficulty: 5,
    promptZh: "在 5×5 菱形方格中，从底端到顶端每步只能向东北或西北走一格。对每条路径，计算路径与方格右边界之间区域的面积。图中给出两个例子。所有可能路径对应面积的总和是多少？",
    promptEn: "In a 5-by-5 diamond grid, paths go from bottom to top using northeast or northwest steps. For each path, find the area between it and the right side. What is the sum over all paths?",
    figure: {
      src: "/questions/2025/q25.png",
      altZh: "两个 5×5 菱形方格路径示例，路径右侧区域分别涂色并标注面积 11 和 13。",
      altEn: "Two sample paths in a 5-by-5 diamond grid with right-side regions shaded and labeled area 11 and 13.",
    },
    options: numericOptions(["2520", "3150", "3840", "4730", "5050"]),
    answer: "B",
    solutionZh: [
      "设所有路径右侧面积之和为 X。由左右对称，所有路径左侧面积之和也为 X。",
      "每条路径左右两侧面积之和为 25。每条路径包含 5 次左上和 5 次右上，共有 C(10,5)=252 条。",
      "因此 2X=25×252，得到 X=3150。",
    ],
    solutionEn: [
      "Let X be the sum of the right-side areas. By reflection, the sum of the left-side areas is also X.",
      "For every path the two areas total 25. There are C(10,5) = 252 paths.",
      "Thus 2X = 25·252, so X = 3150.",
    ],
    sourceUrl,
  },
];
