import type { Question, QuestionOption } from "./questions";

const numericOptions = (values: string[]): QuestionOption[] =>
  values.map((value, index) => ({
    label: String.fromCharCode(65 + index) as QuestionOption["label"],
    valueZh: value,
  }));

const sourceUrl = "https://live.poshenloh.com/past-contests/amc8/2020";

export const questions2020: Question[] = [
  {
    id: "2020-01",
    year: 2020,
    number: 1,
    status: "published",
    primaryTopic: "算术",
    skills: ["倍数关系", "比例计算"],
    formats: ["文字应用题"],
    difficulty: 1,
    promptZh: "Luka 为学校募款活动制作柠檬水。配方要求水是糖的 4 倍，糖是柠檬汁的 2 倍。他用了 3 杯柠檬汁，需要多少杯水？",
    promptEn: "Luka is making lemonade for a school fundraiser. His recipe uses 4 times as much water as sugar and twice as much sugar as lemon juice. If he uses 3 cups of lemon juice, how many cups of water does he need?",
    options: numericOptions(["6", "8", "12", "18", "24"]),
    answer: "E",
    solutionZh: ["糖需要 2×3=6 杯。", "水需要 4×6=24 杯。"],
    solutionEn: ["He needs 2·3=6 cups of sugar.", "He then needs 4·6=24 cups of water."],
    sourceUrl,
  },
  {
    id: "2020-02",
    year: 2020,
    number: 2,
    status: "published",
    primaryTopic: "算术",
    secondaryTopics: ["数据与统计"],
    skills: ["平均数", "等额分配"],
    formats: ["文字应用题"],
    difficulty: 1,
    promptZh: "四位朋友周末帮邻居做院子里的活，分别赚了 15、20、25 和 40 美元。他们决定把收入平均分配。赚了 40 美元的朋友总共要给其他人多少美元？",
    promptEn: "Four friends earn $15, $20, $25, and $40 doing yardwork and split the earnings equally. In total, how many dollars will the friend who earned $40 give to the others?",
    options: numericOptions(["5", "10", "15", "20", "25"]),
    answer: "C",
    solutionZh: ["总收入是 15+20+25+40=100 美元，每人应得 100÷4=25 美元。", "赚 40 美元的人要拿出 40-25=15 美元。"],
    solutionEn: ["The total is $100, so each friend should receive $25.", "The friend who earned $40 gives away $40-$25=$15."],
    sourceUrl,
  },
  {
    id: "2020-03",
    year: 2020,
    number: 3,
    status: "published",
    primaryTopic: "算术",
    secondaryTopics: ["几何"],
    skills: ["面积计算", "单位率", "多步计算"],
    formats: ["文字应用题"],
    difficulty: 1,
    promptZh: "Carrie 的长方形花园长 8 英尺、宽 6 英尺。每平方英尺种 4 株草莓，每株平均收获 10 颗草莓。她预计能收获多少颗草莓？",
    promptEn: "Carrie has a 6-foot by 8-foot rectangular garden. She plants 4 strawberry plants per square foot and harvests an average of 10 strawberries per plant. How many strawberries can she expect?",
    options: numericOptions(["560", "960", "1120", "1920", "3840"]),
    answer: "D",
    solutionZh: ["花园面积为 6×8=48 平方英尺，因此可种 48×4=192 株。", "预计收获 192×10=1920 颗草莓。"],
    solutionEn: ["The area is 6·8=48 square feet, allowing 48·4=192 plants.", "At 10 strawberries per plant, the expected harvest is 1920."],
    sourceUrl,
  },
  {
    id: "2020-04",
    year: 2020,
    number: 4,
    status: "published",
    primaryTopic: "计数与组合",
    secondaryTopics: ["几何"],
    skills: ["图形规律", "数列递增"],
    formats: ["图形规律"],
    difficulty: 1,
    promptZh: "图中三个正六边形的点阵逐渐增大，每个新六边形都比前一个多一圈点。按此规律，下一个六边形有多少个点？",
    promptEn: "Three hexagons of increasing size are shown. Each successive hexagon contains one more band of dots. How many dots are in the next hexagon?",
    figure: {
      src: "/questions/2020/q04.png",
      altZh: "由 1 个点、7 个点和 19 个点组成的三层六边形点阵。",
      altEn: "Three hexagonal dot patterns containing 1, 7, and 19 dots.",
    },
    options: numericOptions(["35", "37", "39", "43", "49"]),
    answer: "B",
    solutionZh: ["前三个图形分别有 1、7、19 个点；新增的一圈依次增加 6、12 个点。", "下一圈增加 18 个点，所以共有 19+18=37 个点。"],
    solutionEn: ["The first three patterns contain 1, 7, and 19 dots; the added bands contribute 6 and 12 dots.", "The next band contributes 18 dots, giving 19+18=37."],
    sourceUrl,
  },
  {
    id: "2020-05",
    year: 2020,
    number: 5,
    status: "published",
    primaryTopic: "算术",
    skills: ["分数", "百分数", "平均分配"],
    formats: ["文字应用题"],
    difficulty: 1,
    promptZh: "一个水壶装了其容量的 3/4 的菠萝汁。把这些果汁平均倒入 5 个杯子，每杯得到的果汁占水壶总容量的百分之几？",
    promptEn: "A pitcher is three-fourths full of pineapple juice. The juice is divided equally among 5 cups. What percent of the pitcher's total capacity does each cup receive?",
    options: numericOptions(["5", "10", "15", "20", "25"]),
    answer: "C",
    solutionZh: ["每杯得到水壶总容量的 (3/4)÷5=3/20。", "3/20=15%。"],
    solutionEn: ["Each cup receives (3/4)÷5=3/20 of the pitcher's capacity.", "Since 3/20=15%, the answer is 15."],
    sourceUrl,
  },
  {
    id: "2020-06",
    year: 2020,
    number: 6,
    status: "published",
    primaryTopic: "计数与组合",
    skills: ["顺序约束", "逻辑推理"],
    formats: ["逻辑排列题"],
    difficulty: 2,
    promptZh: "Aaron、Darren、Karen、Maren 和 Sharon 乘坐一列有 5 节单人车厢的小火车。Maren 坐最后一节；Aaron 紧跟在 Sharon 后面；Darren 坐在 Aaron 前面；Karen 与 Darren 之间至少隔一人。谁坐在正中间的车厢？",
    promptEn: "Aaron, Darren, Karen, Maren, and Sharon ride in five one-person train cars. Maren is last, Aaron is directly behind Sharon, Darren is ahead of Aaron, and at least one person is between Karen and Darren. Who is in the middle car?",
    options: [
      { label: "A", valueZh: "Aaron" },
      { label: "B", valueZh: "Darren" },
      { label: "C", valueZh: "Karen" },
      { label: "D", valueZh: "Maren" },
      { label: "E", valueZh: "Sharon" },
    ],
    answer: "A",
    solutionZh: ["Maren 固定在第 5 节。Sharon 与 Aaron 必须相邻且依次排列。", "排除不满足 Darren 在 Aaron 前面或 Karen 与 Darren 不相邻的情况，唯一顺序为 Darren、Sharon、Aaron、Karen、Maren，因此中间是 Aaron。"],
    solutionEn: ["Maren is fixed in car 5, and Sharon must sit immediately before Aaron.", "The only ordering satisfying the remaining conditions is Darren, Sharon, Aaron, Karen, Maren, so Aaron is in the middle."],
    sourceUrl,
  },
  {
    id: "2020-07",
    year: 2020,
    number: 7,
    status: "published",
    primaryTopic: "计数与组合",
    secondaryTopics: ["数论"],
    skills: ["组合计数", "数字构造"],
    formats: ["整数题"],
    difficulty: 2,
    promptZh: "2020 与 2400 之间有多少个四位数，其 4 个数字互不相同且从左到右严格递增？例如 2357 满足条件。",
    promptEn: "How many integers between 2020 and 2400 have four distinct digits in increasing order? For example, 2357 is one such integer.",
    options: numericOptions(["9", "10", "15", "21", "28"]),
    answer: "C",
    solutionZh: ["千位必须是 2，数字严格递增又要求小于 2400，所以百位必须是 3。", "最后两位从 4、5、6、7、8、9 中选 2 个，顺序唯一，共 C(6,2)=15 个。"],
    solutionEn: ["The thousands digit must be 2, and the increasing condition together with the upper bound forces the hundreds digit to be 3.", "Choose the final two digits from 4 through 9; their order is forced, so there are C(6,2)=15 numbers."],
    sourceUrl,
  },
  {
    id: "2020-08",
    year: 2020,
    number: 8,
    status: "published",
    primaryTopic: "算术",
    secondaryTopics: ["数论"],
    skills: ["极值", "硬币问题"],
    formats: ["文字应用题"],
    difficulty: 2,
    promptZh: "Ricardo 有 2020 枚硬币，其中一部分是 1 美分硬币，其余是 5 美分硬币，并且两种至少各有一枚。他所能拥有的最大金额与最小金额相差多少美分？",
    promptEn: "Ricardo has 2020 coins, some pennies and the rest nickels, with at least one of each. What is the difference in cents between the greatest and least possible total values?",
    options: numericOptions(["8062", "8068", "8072", "8076", "8082"]),
    answer: "C",
    solutionZh: ["最大金额含 2019 枚 5 分硬币和 1 枚 1 分硬币；最小金额则相反。", "两种情况之间有 2018 枚硬币由 1 分变为 5 分，差为 2018×4=8072 美分。"],
    solutionEn: ["The maximum uses 2019 nickels and 1 penny; the minimum uses 1 nickel and 2019 pennies.", "Between the cases, 2018 coins gain 4 cents each, for a difference of 8072 cents."],
    sourceUrl,
  },
  {
    id: "2020-09",
    year: 2020,
    number: 9,
    status: "published",
    primaryTopic: "几何",
    skills: ["立体几何", "表面计数", "分类计数"],
    formats: ["立体图"],
    difficulty: 2,
    promptZh: "一个 4×4×4 英寸的立方体蛋糕，顶部和四个侧面有糖霜，底部没有。把它切成 64 个 1×1×1 英寸的小立方体，恰好有两个面带糖霜的小块有多少个？",
    promptEn: "A 4×4×4-inch cube cake has icing on the top and four side faces, but not the bottom. It is cut into 64 unit cubes. How many pieces have icing on exactly two faces?",
    figure: {
      src: "/questions/2020/q09.png",
      altZh: "一个分成 4×4×4 个单位小立方体的蛋糕。",
      altEn: "A cube divided into a 4-by-4-by-4 array of unit cubes.",
    },
    options: numericOptions(["12", "16", "18", "20", "24"]),
    answer: "D",
    solutionZh: ["顶层四条边上除角块外，每边有 2 块恰好两面带糖霜，共 4×2=8 块。", "下面 3 层中，每层 4 个竖直棱角块恰好两面带糖霜，共 3×4=12 块；总数为 20。"],
    solutionEn: ["On the top layer, the two non-corner cubes on each of four edges contribute 8 pieces.", "In each of the lower three layers, the four corner cubes contribute 12 more, for a total of 20."],
    sourceUrl,
  },
  {
    id: "2020-10",
    year: 2020,
    number: 10,
    status: "published",
    primaryTopic: "计数与组合",
    skills: ["排列", "补集计数", "捆绑法"],
    formats: ["排列题"],
    difficulty: 2,
    promptZh: "Zara 有 4 颗不同的弹珠：Aggie、Bumblebee、Steelie 和 Tiger。她把它们排成一行，但不希望 Steelie 与 Tiger 相邻。共有多少种排法？",
    promptEn: "Zara has four distinct marbles: an Aggie, a Bumblebee, a Steelie, and a Tiger. How many row arrangements keep the Steelie and Tiger from being adjacent?",
    options: numericOptions(["6", "8", "12", "18", "24"]),
    answer: "C",
    solutionZh: ["所有排列有 4!=24 种。", "把 Steelie 与 Tiger 捆成一块，相邻排列有 3!×2=12 种，所以不相邻的有 24-12=12 种。"],
    solutionEn: ["There are 4!=24 total arrangements.", "Treating Steelie and Tiger as a block gives 3!·2=12 adjacent arrangements, leaving 12 valid arrangements."],
    sourceUrl,
  },
  {
    id: "2020-11",
    year: 2020,
    number: 11,
    status: "published",
    primaryTopic: "数据与统计",
    secondaryTopics: ["算术"],
    skills: ["折线图", "平均速度", "单位换算"],
    formats: ["折线图"],
    difficulty: 2,
    promptZh: "放学后 Maya 骑自行车、Naomi 坐公交车前往 6 英里外的海滩。图中给出她们的路程和时间。Naomi 与 Maya 的平均速度相差多少英里/小时？",
    promptEn: "Maya bikes and Naomi takes a bus to a beach 6 miles away. The graph shows their journeys. What is the difference between their average speeds, in miles per hour?",
    figure: {
      src: "/questions/2020/q11.png",
      altZh: "Maya 与 Naomi 的时间—路程折线图；两人均行进 6 英里。",
      altEn: "A distance-versus-time graph for Maya and Naomi, each traveling 6 miles.",
    },
    options: numericOptions(["6", "12", "18", "20", "24"]),
    answer: "E",
    solutionZh: ["Naomi 用 10 分钟走 6 英里，平均速度为 6÷(10/60)=36 英里/小时。", "Maya 用 30 分钟，平均速度为 12 英里/小时；两者相差 36-12=24。"],
    solutionEn: ["Naomi travels 6 miles in 10 minutes, averaging 36 miles per hour.", "Maya travels 6 miles in 30 minutes, averaging 12 miles per hour, so the difference is 24."],
    sourceUrl,
  },
  {
    id: "2020-12",
    year: 2020,
    number: 12,
    status: "published",
    primaryTopic: "数论",
    secondaryTopics: ["代数"],
    skills: ["阶乘", "约分", "方程求解"],
    formats: ["算式"],
    difficulty: 2,
    promptZh: "正整数 n 的阶乘 n! 表示从 n 乘到 1。若 5!×9!=12×N!，求 N。",
    promptEn: "For positive integer n, n! is the product from n down to 1. What value of N satisfies 5!×9!=12×N!?",
    expression: ["5! × 9! = 12 × N!"],
    options: numericOptions(["10", "11", "12", "13", "14"]),
    answer: "A",
    solutionZh: ["因为 5!=120=12×10，原式化为 12×10×9!=12×N!。", "约去 12 得 N!=10×9!=10!，所以 N=10。"],
    solutionEn: ["Since 5!=120=12·10, the equation becomes 12·10·9!=12·N!.", "Canceling 12 gives N!=10!, so N=10."],
    sourceUrl,
  },
  {
    id: "2020-13",
    year: 2020,
    number: 13,
    status: "published",
    primaryTopic: "概率",
    secondaryTopics: ["代数"],
    skills: ["概率建模", "列方程"],
    formats: ["文字应用题"],
    difficulty: 2,
    promptZh: "抽屉里有 6 只绿色袜子、18 只紫色袜子和 12 只橙色袜子。再加入一些紫色袜子后，随机抽到紫色袜子的概率变为 60%。加入了多少只紫色袜子？",
    promptEn: "A drawer contains 6 green, 18 purple, and 12 orange socks. After adding more purple socks, the probability of selecting a purple sock is 60%. How many purple socks were added?",
    options: numericOptions(["6", "9", "12", "18", "24"]),
    answer: "B",
    solutionZh: ["设加入 x 只紫袜，则紫袜数为 18+x，总数为 36+x。", "由 (18+x)/(36+x)=0.6，解得 x=9。"],
    solutionEn: ["Let x purple socks be added. Then the purple count is 18+x and the total is 36+x.", "Solving (18+x)/(36+x)=0.6 gives x=9."],
    sourceUrl,
  },
  {
    id: "2020-14",
    year: 2020,
    number: 14,
    status: "published",
    primaryTopic: "数据与统计",
    skills: ["条形图", "平均数", "估算"],
    formats: ["条形图"],
    difficulty: 2,
    promptZh: "Newton 县有 20 个城市，图中条形图给出各城市人口，水平虚线表示平均人口。以下哪一个最接近 20 个城市的总人口？",
    promptEn: "A bar chart shows the populations of 20 cities in Newton County, with a dashed line marking the average. Which choice is closest to the total population?",
    figure: {
      src: "/questions/2020/q14.png",
      altZh: "20 个城市的人口条形图，平均线约位于 4750。",
      altEn: "A bar chart of 20 city populations with the average near 4,750.",
    },
    options: numericOptions(["65,000", "75,000", "85,000", "95,000", "105,000"]),
    answer: "D",
    solutionZh: ["虚线显示平均人口约为 4750。", "总人口约为 20×4750=95,000。"],
    solutionEn: ["The dashed line places the average near 4,750.", "Thus the total is about 20·4,750=95,000."],
    sourceUrl,
  },
  {
    id: "2020-15",
    year: 2020,
    number: 15,
    status: "published",
    primaryTopic: "代数",
    secondaryTopics: ["算术"],
    skills: ["百分数", "比例方程"],
    formats: ["文字应用题"],
    difficulty: 2,
    promptZh: "若 x 的 15% 等于 y 的 20%，那么 y 是 x 的百分之几？",
    promptEn: "Suppose 15% of x equals 20% of y. What percentage of x is y?",
    options: numericOptions(["5", "35", "75", "133 1/3", "300"]),
    answer: "C",
    solutionZh: ["由 0.15x=0.20y，得 y=(0.15/0.20)x=0.75x。", "所以 y 是 x 的 75%。"],
    solutionEn: ["From 0.15x=0.20y, we get y=(0.15/0.20)x=0.75x.", "Therefore y is 75% of x."],
    sourceUrl,
  },
  {
    id: "2020-16",
    year: 2020,
    number: 16,
    status: "published",
    primaryTopic: "代数",
    secondaryTopics: ["计数与组合"],
    skills: ["加权计数", "不变量"],
    formats: ["几何图"],
    difficulty: 3,
    promptZh: "图中 A、B、C、D、E、F 分别代表 1 到 6 中互不相同的数字。五条直线各经过若干点，把每条线上的数字相加所得的五个和总计为 47。B 代表哪个数字？",
    promptEn: "Points A through F represent the distinct digits 1 through 6. Summing the digits on each of the five shown lines gives five line sums whose total is 47. What digit is represented by B?",
    figure: {
      src: "/questions/2020/q16.png",
      altZh: "六个标记点分布在五条相交直线上，其中 B 位于三条直线的交点。",
      altEn: "Six labeled points on five intersecting lines, with B lying on three lines.",
    },
    options: numericOptions(["1", "2", "3", "4", "5"]),
    answer: "E",
    solutionZh: ["除 B 外，每个点在五个线和中被计算 2 次；B 被计算 3 次。", "1+2+3+4+5+6=21，所以 47=2×21+B，得 B=5。"],
    solutionEn: ["Every point except B is counted twice among the five line sums, while B is counted three times.", "Since 1+2+3+4+5+6=21, we have 47=2·21+B, so B=5."],
    sourceUrl,
  },
  {
    id: "2020-17",
    year: 2020,
    number: 17,
    status: "published",
    primaryTopic: "数论",
    skills: ["质因数分解", "因数个数", "分类排除"],
    formats: ["整数题"],
    difficulty: 3,
    promptZh: "2020 的因数中，有多少个因数本身拥有超过 3 个正因数？例如 12 有 1、2、3、4、6、12 共 6 个正因数。",
    promptEn: "How many factors of 2020 themselves have more than 3 positive factors? For example, 12 has 6 positive factors.",
    options: numericOptions(["6", "7", "8", "9", "10"]),
    answer: "B",
    solutionZh: ["2020=2²×5×101，因此共有 (2+1)(1+1)(1+1)=12 个正因数。", "其中 1 和质数 2、5、101 的因数少于 3 个，4 恰有 3 个；其余 12-5=7 个都超过 3 个。"],
    solutionEn: ["Since 2020=2²·5·101, it has 12 positive factors.", "Exclude 1, the primes 2, 5, and 101, and 4, which has exactly three factors. The remaining 7 qualify."],
    sourceUrl,
  },
  {
    id: "2020-18",
    year: 2020,
    number: 18,
    status: "published",
    primaryTopic: "几何",
    secondaryTopics: ["代数"],
    skills: ["半圆", "勾股定理", "长方形面积"],
    formats: ["几何图"],
    difficulty: 3,
    promptZh: "长方形 ABCD 内接于以 FE 为直径的半圆。已知 DA=16，FD=AE=9，求长方形 ABCD 的面积。",
    promptEn: "Rectangle ABCD is inscribed in a semicircle with diameter FE. If DA=16 and FD=AE=9, what is the area of ABCD?",
    figure: {
      src: "/questions/2020/q18.png",
      altZh: "半圆内接长方形 ABCD，直径被分成 9、16、9 三段。",
      altEn: "A rectangle inscribed in a semicircle whose diameter is divided into lengths 9, 16, and 9.",
    },
    options: numericOptions(["240", "248", "256", "264", "272"]),
    answer: "A",
    solutionZh: ["直径 FE=9+16+9=34，所以半径为 17。圆心到 D 的水平距离是 17-9=8。", "由直角三角形得矩形高为 √(17²-8²)=15，面积为 16×15=240。"],
    solutionEn: ["The diameter is 34, so the radius is 17. The horizontal distance from the center to D is 17-9=8.", "The rectangle's height is √(17²-8²)=15, so its area is 16·15=240."],
    sourceUrl,
  },
  {
    id: "2020-19",
    year: 2020,
    number: 19,
    status: "published",
    primaryTopic: "数论",
    secondaryTopics: ["计数与组合"],
    skills: ["整除规则", "数字构造", "分类计数"],
    formats: ["整数题"],
    difficulty: 3,
    promptZh: "若一个数的各位数字在两个不同数字之间交替，就称它为“交替数”。例如 2020 和 37373 是交替数，3883 和 123123 不是。能被 15 整除的五位交替数有多少个？",
    promptEn: "A number is flippy if its digits alternate between two distinct digits. How many five-digit flippy numbers are divisible by 15?",
    options: numericOptions(["3", "4", "5", "6", "8"]),
    answer: "B",
    solutionZh: ["五位交替数形如 ABABA。能被 5 整除要求末位 A 为 0 或 5；首位不能为 0，所以 A=5。", "数字和为 15+2B，要被 3 整除，B 可为 0、3、6、9，共 4 个。"],
    solutionEn: ["A five-digit flippy number has form ABABA. Divisibility by 5 and a nonzero first digit force A=5.", "Its digit sum is 15+2B, divisible by 3 for B=0, 3, 6, or 9, giving 4 numbers."],
    sourceUrl,
  },
  {
    id: "2020-20",
    year: 2020,
    number: 20,
    status: "published",
    primaryTopic: "代数",
    secondaryTopics: ["数据与统计"],
    skills: ["数列重建", "倍数关系", "平均数"],
    formats: ["表格"],
    difficulty: 4,
    promptZh: "一排 5 棵树的高度都是整数，相邻两棵中左边一棵的高度总是右边一棵的 2 倍或一半。笔记中只剩 T₂=11 米，并显示平均高度的小数部分为 .2。根据图中残留数据，平均高度是多少米？",
    promptEn: "Five integer tree heights are arranged so each tree is twice or half the height of the tree to its right. The surviving notes show T₂=11 m and that the average ends in .2. What was the average height?",
    figure: {
      src: "/questions/2020/q20.png",
      altZh: "树高记录表：T₂ 为 11 米，其余树高缺失，平均数只剩末尾 0.2 米。",
      altEn: "A damaged table showing T₂=11 m, missing other heights, and an average ending in 0.2 m.",
    },
    options: numericOptions(["22.2", "24.2", "33.2", "35.2", "37.2"]),
    answer: "B",
    solutionZh: ["因高度为整数且相邻相差 2 倍，T₁=T₃=22，前三棵合计 55。", "(T₄,T₅) 可能为 (11,22)、(44,22) 或 (44,88)，相应平均数为 17.6、24.2、37.4；只有 24.2 的小数部分为 .2。"],
    solutionEn: ["Integer heights force T₁=T₃=22, so the first three total 55.", "The possible pairs (T₄,T₅) are (11,22), (44,22), and (44,88), yielding averages 17.6, 24.2, and 37.4. Only 24.2 matches the note."],
    sourceUrl,
  },
  {
    id: "2020-21",
    year: 2020,
    number: 21,
    status: "published",
    primaryTopic: "计数与组合",
    skills: ["路径计数", "动态规划", "递推"],
    formats: ["方格图"],
    difficulty: 4,
    promptZh: "一个 8×8 棋盘的格子深浅交替。标记从底行的 P 出发，每一步移动到上一行中与当前格相邻的浅色格。到顶行 Q 的 7 步路径共有多少条？图中画出了一条示例路径。",
    promptEn: "On an 8-by-8 alternating board, a marker starts at P. Each step moves to an adjoining unshaded square in the row above. How many 7-step paths lead from P to Q?",
    figure: {
      src: "/questions/2020/q21.png",
      altZh: "8×8 深浅相间棋盘，底行标有 P，顶行标有 Q，并画出一条示例路径。",
      altEn: "An 8-by-8 alternating board with P in the bottom row, Q in the top row, and a sample path.",
    },
    options: numericOptions(["28", "30", "32", "33", "35"]),
    answer: "A",
    solutionZh: ["从 P 开始逐行计数：每个可达浅色格的路径数，等于它下方两个相邻可达格的路径数之和。", "按此递推到顶行，Q 处得到 28。"],
    solutionEn: ["Work upward from P. The count at each reachable square is the sum of the counts at the two adjacent reachable squares below it.", "Continuing for seven rows gives 28 at Q."],
    sourceUrl,
  },
  {
    id: "2020-22",
    year: 2020,
    number: 22,
    status: "published",
    primaryTopic: "数论",
    secondaryTopics: ["代数", "计数与组合"],
    skills: ["逆向推理", "奇偶性", "迭代函数"],
    formats: ["流程图"],
    difficulty: 4,
    promptZh: "把正整数 N 输入机器：N 为偶数时输出 N/2，N 为奇数时输出 3N+1。连续执行 6 次后输出 1。所有可能的初始正整数 N 之和是多少？",
    promptEn: "A machine outputs N/2 when N is even and 3N+1 when N is odd. After applying the process 6 times, the final output is 1. What is the sum of all possible starting positive integers N?",
    figure: {
      src: "/questions/2020/q22.png",
      altZh: "机器规则图：偶数输出 N/2，奇数输出 3N+1。",
      altEn: "A machine diagram showing output N/2 for even N and 3N+1 for odd N.",
    },
    options: numericOptions(["73", "74", "75", "82", "83"]),
    answer: "E",
    solutionZh: ["从 1 逆推：每个值 m 一定可由偶数 2m 得到；若 (m-1)/3 是正奇数，也可由该奇数得到。", "六步逆推得到初始值 1、8、10、64，和为 83。"],
    solutionEn: ["Work backward from 1. A value m always has even predecessor 2m, and also has odd predecessor (m-1)/3 when that is a positive odd integer.", "After six backward steps, the possible starts are 1, 8, 10, and 64, whose sum is 83."],
    sourceUrl,
  },
  {
    id: "2020-23",
    year: 2020,
    number: 23,
    status: "published",
    primaryTopic: "计数与组合",
    skills: ["容斥原理", "分配计数"],
    formats: ["分配题"],
    difficulty: 4,
    promptZh: "把 5 个互不相同的奖项发给 3 名学生，每名学生至少获得 1 个奖项。共有多少种发法？",
    promptEn: "Five different awards are distributed to three students, with each student receiving at least one award. How many distributions are possible?",
    options: numericOptions(["120", "150", "180", "210", "240"]),
    answer: "B",
    solutionZh: ["不加限制时，每个奖项有 3 个去向，共 3⁵=243 种。", "用容斥排除有人没得奖：243-3×2⁵+3=150。"],
    solutionEn: ["Without restrictions there are 3⁵=243 assignments.", "By inclusion-exclusion, subtract 3·2⁵ assignments missing a chosen student and add back the 3 single-recipient cases: 243-96+3=150."],
    sourceUrl,
  },
  {
    id: "2020-24",
    year: 2020,
    number: 24,
    status: "published",
    primaryTopic: "几何",
    secondaryTopics: ["代数"],
    skills: ["面积比例", "几何建模", "方程求解"],
    formats: ["几何图"],
    difficulty: 4,
    promptZh: "一个大正方形由 n² 块边长为 s 的阴影正方形瓷砖铺成，每块瓷砖四周有宽 d 的边框。图示为 n=3。当 n=24 时，576 块阴影瓷砖占大正方形面积的 64%。求 d/s。",
    promptEn: "A large square contains n² shaded square tiles of side s, with borders of width d around the tiles. For n=24, the 576 tiles cover 64% of the large square. What is d/s?",
    figure: {
      src: "/questions/2020/q24.png",
      altZh: "n=3 时的九块方形瓷砖及其周围等宽边框。",
      altEn: "A 3-by-3 example of square tiles separated and surrounded by equal-width borders.",
    },
    options: numericOptions(["6/25", "1/4", "9/25", "7/16", "9/16"]),
    answer: "A",
    solutionZh: ["n=24 时阴影总面积为 24²s²，大正方形边长为 24s+25d。", "由 24²s²/(24s+25d)²=16/25，开正根并整理得 120s=96s+100d，所以 d/s=6/25。"],
    solutionEn: ["For n=24, the shaded area is 24²s² and the large square has side 24s+25d.", "Using 24²s²/(24s+25d)²=16/25 and taking positive square roots gives d/s=6/25."],
    sourceUrl,
  },
  {
    id: "2020-25",
    year: 2020,
    number: 25,
    status: "published",
    primaryTopic: "几何",
    secondaryTopics: ["代数"],
    skills: ["图形分割", "线性方程", "边长关系"],
    formats: ["几何图"],
    difficulty: 5,
    promptZh: "长方形 R₁、R₂ 与正方形 S₁、S₂、S₃ 拼成一个宽 3322、高 2020 的长方形。求正方形 S₂ 的边长。",
    promptEn: "Rectangles R₁ and R₂ and squares S₁, S₂, and S₃ form a rectangle 3322 units wide and 2020 units high. What is the side length of S₂?",
    figure: {
      src: "/questions/2020/q25.png",
      altZh: "由两个长方形和三个正方形拼成的大长方形示意图。",
      altEn: "A large rectangle partitioned into rectangles R₁, R₂ and squares S₁, S₂, S₃.",
    },
    options: numericOptions(["651", "655", "656", "662", "666"]),
    answer: "A",
    solutionZh: ["设三个正方形边长为 s₁、s₂、s₃。横向总宽为 s₁+s₂+s₃=3322。", "R₂ 的高为 s₁-s₂，所以总高为 (s₁-s₂)+s₃=2020。两式相减得 2s₂=1302，因此 s₂=651。"],
    solutionEn: ["Let the square side lengths be s₁, s₂, and s₃. Across the width, s₁+s₂+s₃=3322.", "Since R₂ has height s₁-s₂, the total height is s₁-s₂+s₃=2020. Subtracting gives 2s₂=1302, so s₂=651."],
    sourceUrl,
  },
];
