import type { Question, QuestionOption } from "./questions";

const numericOptions = (values: string[]): QuestionOption[] =>
  values.map((value, index) => ({
    label: String.fromCharCode(65 + index) as QuestionOption["label"],
    valueZh: value,
  }));

const sourceUrl = "https://live.poshenloh.com/past-contests/amc8/2023";

export const questions2023: Question[] = [
  {
    id: "2023-01",
    year: 2023,
    number: 1,
    status: "published",
    primaryTopic: "算术",
    skills: ["计算", "运算顺序"],
    formats: ["算式"],
    difficulty: 1,
    promptZh: "下面算式的值是多少？",
    promptEn: "What is the value of the following expression?",
    expression: ["(8 × 4 + 2) − (8 + 4 × 2)"],
    options: numericOptions(["0", "6", "10", "18", "24"]),
    answer: "D",
    solutionZh: ["先做乘法：左括号为 32+2=34，右括号为 8+8=16。", "所以原式等于 34-16=18。"],
    solutionEn: ["Evaluate multiplication first: the two parentheses are 34 and 16.", "Therefore the value is 34-16=18."],
    sourceUrl,
  },
  {
    id: "2023-02",
    year: 2023,
    number: 2,
    status: "published",
    primaryTopic: "几何",
    skills: ["空间想象", "对称"],
    formats: ["操作或路径图"],
    difficulty: 2,
    promptZh: "一张正方形纸按图折叠两次，成为四个相等的四分之一，再沿虚线剪开。展开后会得到哪一种图形？",
    promptEn: "A square piece of paper is folded twice into four equal quarters, then cut along the dashed line. Which figure results when the paper is unfolded?",
    figure: {
      src: "/questions/2023/q02.png",
      altZh: "正方形纸折成四分之一后沿斜虚线剪开，以及五个展开图选项。",
      altEn: "A square folded into quarters and cut along a diagonal dashed line, followed by five possible unfolded figures.",
    },
    options: [
      { label: "A", valueZh: "四边形成交叉形缺口", valueEn: "Cross-shaped edge cutouts" },
      { label: "B", valueZh: "上下形成 V 形缺口", valueEn: "V-shaped cutouts at top and bottom" },
      { label: "C", valueZh: "中央为正方形孔", valueEn: "A square hole in the center" },
      { label: "D", valueZh: "中央为三角形孔", valueEn: "A triangular hole in the center" },
      { label: "E", valueZh: "中央为菱形孔", valueEn: "A diamond-shaped hole in the center" },
    ],
    answer: "E",
    solutionZh: ["每展开一次，剪口会关于一条折痕镜像。", "连续关于两条互相垂直的折痕对称后，四个斜切边围成中央菱形，因此选 E。"],
    solutionEn: ["Each unfolding reflects the cut across a fold line.", "Reflecting across both perpendicular folds produces a central diamond, so the answer is E."],
    sourceUrl,
  },
  {
    id: "2023-03",
    year: 2023,
    number: 3,
    status: "published",
    primaryTopic: "代数",
    secondaryTopics: ["算术"],
    skills: ["代入计算", "估算"],
    formats: ["文字应用题"],
    difficulty: 1,
    promptZh: "风寒温度可用 W=T-0.7S 估算，其中 T 是华氏气温，S 是每小时英里数表示的风速。当 T=36、S=18 时，最接近的风寒温度是多少？",
    promptEn: "Wind chill can be estimated by W=T-0.7S, where T is the Fahrenheit temperature and S is wind speed in miles per hour. If T=36 and S=18, which choice is closest to W?",
    expression: ["W = T − 0.7S"],
    options: numericOptions(["18", "23", "28", "32", "35"]),
    answer: "B",
    solutionZh: ["代入得到 W=36-0.7×18=36-12.6=23.4。", "最接近的选项是 23。"],
    solutionEn: ["Substitution gives W=36-0.7·18=23.4.", "The closest choice is 23."],
    sourceUrl,
  },
  {
    id: "2023-04",
    year: 2023,
    number: 4,
    status: "published",
    primaryTopic: "数论",
    secondaryTopics: ["算术"],
    skills: ["找规律", "质数判断"],
    formats: ["方格图"],
    difficulty: 2,
    promptZh: "整数 1 到 49 从中心开始按图中的方形螺旋排列。与数字 7 位于同一条对角线上的四个阴影方格中，有多少个数是质数？",
    promptEn: "The integers 1 through 49 are arranged in a square spiral beginning at the center. How many of the four shaded entries on the same diagonal as 7 are prime?",
    figure: {
      src: "/questions/2023/q04.png",
      altZh: "7×7 方格中的方形螺旋，中心填有 1 到 7，并标出四个阴影格。",
      altEn: "A square spiral in a 7-by-7 grid with 1 through 7 shown near the center and four shaded cells.",
    },
    options: numericOptions(["0", "1", "2", "3", "4"]),
    answer: "D",
    solutionZh: ["沿螺旋补全数字后，四个阴影格中的质数是 19、23、47。", "因此共有 3 个质数。"],
    solutionEn: ["Completing the spiral shows that the prime shaded entries are 19, 23, and 47.", "Thus there are 3 primes."],
    sourceUrl,
  },
  {
    id: "2023-05",
    year: 2023,
    number: 5,
    status: "published",
    primaryTopic: "算术",
    secondaryTopics: ["数据与统计"],
    skills: ["比例建模", "计算"],
    formats: ["文字应用题"],
    difficulty: 2,
    promptZh: "某湖里有 250 条鳟鱼和其他鱼。生物学家捕捞并放回 180 条鱼的样本，其中 30 条是鳟鱼。假设样本与全湖的鳟鱼比例相同，湖里共有多少条鱼？",
    promptEn: "A lake contains 250 trout. In a sample of 180 fish, 30 are trout. Assuming the sample ratio matches the lake, how many fish are in the lake?",
    options: numericOptions(["1250", "1500", "1750", "1800", "2000"]),
    answer: "B",
    solutionZh: ["样本中鳟鱼占 30/180=1/6。", "所以总鱼数是鳟鱼数的 6 倍，即 250×6=1500。"],
    solutionEn: ["Trout make up 30/180=1/6 of the sample.", "The lake therefore has 6·250=1500 fish."],
    sourceUrl,
  },
  {
    id: "2023-06",
    year: 2023,
    number: 6,
    status: "published",
    primaryTopic: "算术",
    skills: ["指数运算", "最值"],
    formats: ["算式", "操作或路径图"],
    difficulty: 2,
    promptZh: "把数字 2、0、2、3 分别放入图中四个方框，组成两个幂的乘积。这个乘积的最大可能值是多少？",
    promptEn: "Place the digits 2, 0, 2, and 3 into the four boxes, one per box, to form a product of two powers. What is the maximum possible value?",
    figure: {
      src: "/questions/2023/q06.png",
      altZh: "两个底数和两个指数均为空格的幂相乘。",
      altEn: "A product of two powers with blank boxes for both bases and exponents.",
    },
    options: numericOptions(["0", "8", "9", "16", "18"]),
    answer: "C",
    solutionZh: ["0 不能作底数，否则乘积为 0，所以让它作指数；相应一项取 2⁰=1。", "剩下的数字组成 3²=9，比 2³=8 大，所以最大值是 2⁰×3²=9。"],
    solutionEn: ["Zero should be an exponent, not a base, so one factor can be 2⁰=1.", "The other factor is maximized as 3²=9 rather than 2³=8, giving 9."],
    sourceUrl,
  },
  {
    id: "2023-07",
    year: 2023,
    number: 7,
    status: "published",
    primaryTopic: "代数",
    secondaryTopics: ["几何"],
    skills: ["直线方程", "坐标推理"],
    formats: ["坐标图"],
    difficulty: 3,
    promptZh: "一个边平行于坐标轴的长方形有两个对角顶点 (15,3) 和 (16,5)。一条直线经过 A(0,0)、B(3,1)，另一条经过 C(0,10)、D(2,9)。长方形边界上有多少个点位于至少一条直线上？",
    promptEn: "An axis-parallel rectangle has opposite vertices (15,3) and (16,5). One line passes through A(0,0), B(3,1), and another through C(0,10), D(2,9). How many points on the rectangle lie on at least one line?",
    figure: {
      src: "/questions/2023/q07.png",
      altZh: "坐标平面上标出 A、B、C、D 以及顶点为 (15,3)、(16,5) 的小长方形。",
      altEn: "A coordinate plane showing A, B, C, D and the small rectangle with corners at x=15,16 and y=3,5.",
    },
    options: numericOptions(["0", "1", "2", "3", "4"]),
    answer: "B",
    solutionZh: ["第一条直线方程是 y=x/3，它在 x=15 时经过 (15,5)，即长方形左上角。", "第二条直线方程是 y=10-x/2；在 x=15 到 16 时，y 在 2 到 2.5 之间，不与长方形相交。因此只有 1 个点。"],
    solutionEn: ["The first line is y=x/3 and passes through the rectangle at (15,5).", "The second line is y=10-x/2 and lies below the rectangle for 15≤x≤16, so there is only 1 point."],
    sourceUrl,
  },
  {
    id: "2023-08",
    year: 2023,
    number: 8,
    status: "published",
    primaryTopic: "计数与组合",
    secondaryTopics: ["数据与统计"],
    skills: ["逻辑推理", "补全表格"],
    formats: ["表格"],
    difficulty: 2,
    promptZh: "Lola、Lolo、Tiya、Tiyo 参加乒乓球循环赛，每人和其余三人各比赛两次。表中 1 表示胜、0 表示负。Tiyo 的胜负记录是什么？",
    promptEn: "Four players each play every other player exactly twice. In the table, 1 is a win and 0 is a loss. What was Tiyo's record?",
    figure: {
      src: "/questions/2023/q08.png",
      altZh: "胜负记录表：Lola 为 111011，Lolo 为 101010，Tiya 为 010100，Tiyo 未知。",
      altEn: "A results table with records 111011, 101010, 010100, and Tiyo's unknown record.",
    },
    options: numericOptions(["000101", "001001", "010000", "010101", "011000"]),
    answer: "A",
    solutionZh: ["每一轮有两场比赛，因此每列恰好有两个 1 和两个 0。", "逐列补上使胜场总数达到 2 的数字，得到 Tiyo 的记录 000101。"],
    solutionEn: ["Each round has two matches, so every column contains exactly two 1s and two 0s.", "Completing the columns gives Tiyo the record 000101."],
    sourceUrl,
  },
  {
    id: "2023-09",
    year: 2023,
    number: 9,
    status: "published",
    primaryTopic: "数据与统计",
    secondaryTopics: ["算术"],
    skills: ["读图", "区间计时"],
    formats: ["统计图"],
    difficulty: 2,
    promptZh: "图中曲线表示 Malaika 滑雪时相对山脚的海拔。她总共有多少秒处于 4 米到 7 米之间的海拔？",
    promptEn: "The graph shows Malaika's elevation above the mountain base as she skis. In total, how many seconds is her elevation between 4 and 7 meters?",
    figure: {
      src: "/questions/2023/q09.png",
      altZh: "海拔随时间变化曲线，横轴 0 到 16 秒，纵轴 0 到 16 米。",
      altEn: "An elevation-versus-time curve from 0 to 16 seconds and 0 to 16 meters.",
    },
    options: numericOptions(["6", "8", "10", "12", "14"]),
    answer: "B",
    solutionZh: ["曲线处在 4 到 7 米之间的三个时间段分别是 2–4 秒、6–10 秒、12–14 秒。", "总时间为 2+4+2=8 秒。"],
    solutionEn: ["The relevant intervals are 2–4, 6–10, and 12–14 seconds.", "Their total length is 2+4+2=8 seconds."],
    sourceUrl,
  },
  {
    id: "2023-10",
    year: 2023,
    number: 10,
    status: "published",
    primaryTopic: "算术",
    skills: ["分数乘法", "连续变化"],
    formats: ["文字应用题"],
    difficulty: 2,
    promptZh: "Harold 吃了李子派的 1/4，把其余留给朋友。一只驼鹿吃了剩余部分的 1/3，之后一只豪猪又吃了驼鹿所剩部分的 1/3。最后还剩原来整张派的多少？",
    promptEn: "Harold ate 1/4 of a pie. A moose ate 1/3 of what remained, and then a porcupine ate 1/3 of what the moose left. What fraction of the original pie remained?",
    options: numericOptions(["1/12", "1/6", "1/4", "1/3", "5/12"]),
    answer: "D",
    solutionZh: ["Harold 吃后剩 3/4；驼鹿吃掉其中 1/3 后，剩下 (3/4)×(2/3)=1/2。", "豪猪再吃掉剩余的 1/3，所以最后为 (1/2)×(2/3)=1/3。"],
    solutionEn: ["After Harold and the moose, the remaining fraction is (3/4)(2/3)=1/2.", "After the porcupine, it is (1/2)(2/3)=1/3."],
    sourceUrl,
  },
  {
    id: "2023-11",
    year: 2023,
    number: 11,
    status: "published",
    primaryTopic: "算术",
    skills: ["单位换算", "估算"],
    formats: ["文字应用题"],
    difficulty: 2,
    promptZh: "NASA 的毅力号火星车飞行了 292,526,838 英里，约 6.5 个月后着陆。下列哪一个最接近它的平均星际飞行速度（英里/小时）？",
    promptEn: "NASA's Perseverance Rover traveled 292,526,838 miles in about 6.5 months. Which choice is closest to its average interplanetary speed in miles per hour?",
    options: numericOptions(["6,000", "12,000", "60,000", "120,000", "600,000"]),
    answer: "C",
    solutionZh: ["把路程估为 3 亿英里，把 6.5 个月估为 200 天。", "每天约 1,500,000 英里，每小时约 1,500,000÷24=62,500 英里，最接近 60,000。"],
    solutionEn: ["Approximate the distance by 300 million miles and the time by 200 days.", "This is about 1,500,000 miles per day, or 62,500 mph, closest to 60,000."],
    sourceUrl,
  },
  {
    id: "2023-12",
    year: 2023,
    number: 12,
    status: "published",
    primaryTopic: "几何",
    secondaryTopics: ["算术"],
    skills: ["圆面积", "图形分割"],
    formats: ["几何图"],
    difficulty: 3,
    promptZh: "大空心圆内部有若干阴影圆和空心圆。大圆内部的阴影面积占几分之几？",
    promptEn: "A large unshaded circle contains several smaller shaded and unshaded circles. What fraction of the large circle's interior is shaded?",
    figure: {
      src: "/questions/2023/q12.png",
      altZh: "半径关系由方格显示的大圆，左侧有一个大阴影圆及两个空心圆，右侧有三个小阴影圆。",
      altEn: "A gridded large circle containing one large shaded circle with two holes and three small shaded circles.",
    },
    options: numericOptions(["1/4", "11/36", "1/3", "19/36", "5/9"]),
    answer: "B",
    solutionZh: ["令最小圆半径为 1。三个小阴影圆面积共 3π；半径 4 的阴影圆扣掉两个半径 2 的空心圆，面积为 16π-8π=8π。", "阴影总面积为 11π，大圆半径为 6、面积 36π，所以比例是 11/36。"],
    solutionEn: ["Let each smallest circle have radius 1. The three small circles have area 3π, and the radius-4 shaded circle minus two radius-2 holes has area 8π.", "The shaded area is 11π out of the large circle's 36π, giving 11/36."],
    sourceUrl,
  },
  {
    id: "2023-13",
    year: 2023,
    number: 13,
    status: "published",
    primaryTopic: "代数",
    secondaryTopics: ["算术"],
    skills: ["比例建模", "分数运算"],
    formats: ["路径图"],
    difficulty: 3,
    promptZh: "自行车赛起点与终点之间有 7 个等距饮水站，另有 2 个等距维修站。第 3 个饮水站在第 1 个维修站之后 2 英里。比赛全程多少英里？",
    promptEn: "Seven water stations and two repair stations are evenly spaced between a race's start and finish. The third water station is 2 miles after the first repair station. How long is the race?",
    figure: {
      src: "/questions/2023/q13.png",
      altZh: "从起点到终点的路线，标出七个等距饮水站的位置。",
      altEn: "A start-to-finish route showing seven evenly spaced water stations.",
    },
    options: numericOptions(["8", "16", "24", "48", "96"]),
    answer: "D",
    solutionZh: ["第 3 个饮水站在全程的 3/8 处，第 1 个维修站在 1/3 处。", "两者相距全程的 3/8-1/3=1/24；这段是 2 英里，因此全程是 48 英里。"],
    solutionEn: ["The third water station is at 3/8 of the course, and the first repair station is at 1/3.", "Their separation is 1/24 of the course and equals 2 miles, so the course is 48 miles."],
    sourceUrl,
  },
  {
    id: "2023-14",
    year: 2023,
    number: 14,
    status: "published",
    primaryTopic: "数论",
    secondaryTopics: ["代数"],
    skills: ["整数规划", "最值"],
    formats: ["文字应用题"],
    difficulty: 4,
    promptZh: "Nicolas 有 5 分、10 分、25 分邮票各 20 枚。要恰好支付 7.10 美元邮资，他最多能用多少枚邮票？",
    promptEn: "Nicolas has exactly twenty each of 5-cent, 10-cent, and 25-cent stamps. What is the greatest number of stamps he can use to make exactly $7.10?",
    options: numericOptions(["45", "46", "51", "54", "55"]),
    answer: "E",
    solutionZh: ["若 5 分、10 分、25 分邮票分别用 a、b、c 枚，则 a+2b+5c=142，且每个数不超过 20。", "取 a=19、b=19、c=17 可得 710 分，共 55 枚。若至少 56 枚，由 a≤20 与 b,c≤20 可推出矛盾，因此最大值是 55。"],
    solutionEn: ["Let a,b,c be the counts. Then a+2b+5c=142 with each count at most 20.", "The choice (19,19,17) gives 710 cents and 55 stamps; the constraints rule out 56 or more, so 55 is maximal."],
    sourceUrl,
  },
  {
    id: "2023-15",
    year: 2023,
    number: 15,
    status: "published",
    primaryTopic: "算术",
    skills: ["速度计算", "单位换算"],
    formats: ["文字应用题"],
    difficulty: 3,
    promptZh: "Visvam 每天步行半英里上学，正常路线有 10 个等长街区，每个街区走 1 分钟。今天走完 5 个街区后，他必须用 3 个等长街区绕行，代替原来的 1 个街区。从开始绕行起，他要以多少英里/小时的速度行走，才能仍按平时的时间到校？",
    promptEn: "Visvam's half-mile route has 10 equal blocks, one minute each. After 5 blocks he must walk a 3-block detour instead of 1 block. From the detour, what speed in miles per hour lets him arrive at the usual time?",
    options: numericOptions(["4", "4.2", "4.5", "4.8", "5"]),
    answer: "B",
    solutionZh: ["每个街区长 1/20 英里。开始绕行后要走 3+4=7 个街区，即 7/20 英里，但只剩正常的 5 分钟。", "5 分钟是 1/12 小时，所以速度为 (7/20)÷(1/12)=4.2 英里/小时。"],
    solutionEn: ["Each block is 1/20 mile. From the detour he must cover 7 blocks, or 7/20 mile, in the usual 5 minutes.", "Since 5 minutes is 1/12 hour, the speed is (7/20)/(1/12)=4.2 mph."],
    sourceUrl,
  },
  {
    id: "2023-16",
    year: 2023,
    number: 16,
    status: "published",
    primaryTopic: "计数与组合",
    secondaryTopics: ["数论"],
    skills: ["周期规律", "计数"],
    formats: ["表格"],
    difficulty: 3,
    promptZh: "字母 P、Q、R 按图中的周期规律填入 20×20 表格。填完后 P、Q、R 各有多少个？",
    promptEn: "The letters P, Q, and R fill a 20-by-20 table according to the shown pattern. How many of each letter appear?",
    figure: {
      src: "/questions/2023/q16.png",
      altZh: "P、Q、R 以三格为周期、相邻行错位的方格表。",
      altEn: "A grid in which P, Q, and R repeat every three cells with shifted adjacent rows.",
    },
    options: [
      { label: "A", valueZh: "132 个 P，134 个 Q，134 个 R" },
      { label: "B", valueZh: "133 个 P，133 个 Q，134 个 R" },
      { label: "C", valueZh: "133 个 P，134 个 Q，133 个 R" },
      { label: "D", valueZh: "134 个 P，132 个 Q，134 个 R" },
      { label: "E", valueZh: "134 个 P，133 个 Q，133 个 R" },
    ],
    answer: "C",
    solutionZh: ["因为 20=3×6+2，每列有两个字母出现 7 次，另一个出现 6 次。结合行的错位规律，P 和 R 各出现 13×7+7×6=133 次。", "剩余格数给 Q：400-2×133=134。因此为 133 个 P、134 个 Q、133 个 R。"],
    solutionEn: ["Since 20=3·6+2, two letters occur 7 times in a column and the third occurs 6 times. The shifted pattern gives 133 each for P and R.", "The remaining 400-266=134 cells contain Q."],
    sourceUrl,
  },
  {
    id: "2023-17",
    year: 2023,
    number: 17,
    status: "published",
    primaryTopic: "几何",
    skills: ["空间想象", "展开图"],
    formats: ["几何图"],
    difficulty: 4,
    promptZh: "Jun 将图中的展开图折成正八面体。哪一个编号面会位于阴影面 Q 的右侧？",
    promptEn: "Jun folds the shown net into a regular octahedron. Which numbered face ends up to the right of shaded face Q?",
    figure: {
      src: "/questions/2023/q17.png",
      altZh: "标有 1 到 7 和 Q 的正八面体展开图，以及折叠后的八面体示意图。",
      altEn: "A regular-octahedron net labeled 1 through 7 and Q, plus the folded octahedron.",
    },
    options: numericOptions(["1", "2", "3", "4", "5"]),
    answer: "A",
    solutionZh: ["折叠后，2、3、4、5 构成八面体的下半部，因此上半部由 1、6、7、Q 构成。", "面 6 在 Q 左侧，面 7 又在 6 左侧，所以 Q 右侧只能是面 1。"],
    solutionEn: ["Faces 2,3,4,5 form the lower half, leaving 1,6,7,Q for the upper half.", "Face 6 is left of Q and 7 is left of 6, so face 1 is to the right of Q."],
    sourceUrl,
  },
  {
    id: "2023-18",
    year: 2023,
    number: 18,
    status: "published",
    primaryTopic: "数论",
    secondaryTopics: ["代数"],
    skills: ["线性丢番图方程", "模运算", "最值"],
    formats: ["文字应用题"],
    difficulty: 4,
    promptZh: "蚱蜢 Greta 每次可以向右跳 5 个荷叶，或向左跳 3 个荷叶。要到达起点右侧第 2023 个荷叶，最少需要跳多少次？",
    promptEn: "Greta can jump 5 lily pads right or 3 pads left. What is the fewest number of jumps needed to reach the pad 2023 places to the right?",
    options: numericOptions(["405", "407", "409", "411", "413"]),
    answer: "D",
    solutionZh: ["设向右跳 r 次、向左跳 l 次，则 5r-3l=2023。模 5 可得 l≡4 (mod 5)。", "为使总次数最少，取最小的 l=4，此时 r=(2023+12)/5=407，总次数为 411。"],
    solutionEn: ["Let r and l be right and left jumps. Then 5r-3l=2023, so modulo 5, l≡4.", "The smallest possible l is 4, giving r=407 and 411 total jumps."],
    sourceUrl,
  },
  {
    id: "2023-19",
    year: 2023,
    number: 19,
    status: "published",
    primaryTopic: "几何",
    secondaryTopics: ["算术"],
    skills: ["相似图形", "面积比"],
    formats: ["几何图"],
    difficulty: 4,
    promptZh: "一个等边三角形位于一个更大的等边三角形内部，两者之间分成三个全等梯形。内三角形边长是外三角形的 2/3。一个梯形的面积与内三角形面积之比是多少？",
    promptEn: "An equilateral triangle lies inside a larger one, and the region between them is divided into three congruent trapezoids. The inner side length is 2/3 of the outer. What is the area ratio of one trapezoid to the inner triangle?",
    figure: {
      src: "/questions/2023/q19.png",
      altZh: "大等边三角形内有一个同向小等边三角形，间隙分成三个全等梯形，其中下方梯形涂色。",
      altEn: "A smaller equilateral triangle inside a larger one with the surrounding region split into three congruent trapezoids.",
    },
    options: numericOptions(["1:3", "3:8", "5:12", "7:16", "4:9"]),
    answer: "C",
    solutionZh: ["内三角形面积是外三角形的 (2/3)²=4/9。三个梯形总面积为外三角形的 5/9，所以一个梯形占 5/27。", "所求比为 (5/27):(4/9)=5:12。"],
    solutionEn: ["The inner triangle has 4/9 the outer area. The three trapezoids total 5/9, so one has 5/27.", "Thus (5/27):(4/9)=5:12."],
    sourceUrl,
  },
  {
    id: "2023-20",
    year: 2023,
    number: 20,
    status: "published",
    primaryTopic: "数据与统计",
    secondaryTopics: ["代数"],
    skills: ["极差", "中位数", "众数", "最值"],
    formats: ["数据题"],
    difficulty: 4,
    promptZh: "向数列 3、3、8、11、28 中插入两个整数，使极差加倍，而众数和中位数不变。这两个新增整数的和最大是多少？",
    promptEn: "Two integers are inserted into 3,3,8,11,28 to double its range while keeping the mode and median unchanged. What is the maximum possible sum of the added integers?",
    options: numericOptions(["56", "57", "58", "60", "61"]),
    answer: "D",
    solutionZh: ["原极差为 25，新极差须为 50。要保持中位数为 8，一个新增数小于 8，另一个大于 8。", "令较小数为 7、较大数为 53，可保持众数为 3、中位数为 8，极差为 50，和为 60；分类讨论其他新最小值或最大值的情形都不会超过 60。"],
    solutionEn: ["The new range must be 50, and preserving median 8 requires one added number below 8 and one above 8.", "Adding 7 and 53 preserves the mode and median and gives sum 60; the alternative range cases give smaller sums."],
    sourceUrl,
  },
  {
    id: "2023-21",
    year: 2023,
    number: 21,
    status: "published",
    primaryTopic: "计数与组合",
    secondaryTopics: ["算术"],
    skills: ["分类枚举", "分组"],
    formats: ["卡片题"],
    difficulty: 4,
    promptZh: "Alina 把 1 到 9 分别写在卡片上，想将它们分成三组，每组 3 张且每组数字和相等。共有多少种分法？",
    promptEn: "Alina divides cards numbered 1 through 9 into three groups of three so that each group has the same sum. In how many ways can this be done?",
    options: numericOptions(["0", "1", "2", "3", "4"]),
    answer: "C",
    solutionZh: ["总和为 45，所以每组和必须为 15。含 9 的组只能是 {1,5,9} 或 {2,4,9}。", "两种情况分别唯一补成 {3,4,8}、{2,6,7}，以及 {1,6,8}、{3,5,7}，所以共有 2 种。"],
    solutionEn: ["The total is 45, so each group sums to 15. The group containing 9 is either {1,5,9} or {2,4,9}.", "Each case uniquely completes the other two groups, giving 2 partitions."],
    sourceUrl,
  },
  {
    id: "2023-22",
    year: 2023,
    number: 22,
    status: "published",
    primaryTopic: "数论",
    secondaryTopics: ["代数"],
    skills: ["递推", "质因数分解", "指数"],
    formats: ["数列"],
    difficulty: 4,
    promptZh: "一个正整数数列从第三项起，每一项都是前两项的乘积。第六项是 4000，第一项是多少？",
    promptEn: "In a sequence of positive integers, each term after the second is the product of the previous two. If the sixth term is 4000, what is the first term?",
    options: numericOptions(["1", "2", "4", "5", "10"]),
    answer: "D",
    solutionZh: ["设前两项为 x、y，则前六项依次为 x、y、xy、xy²、x²y³、x³y⁵。", "所以 x³y⁵=4000=2⁵×5³，只能取 y=2、x=5。第一项是 5。"],
    solutionEn: ["With first terms x,y, the sixth term is x³y⁵.", "Since 4000=2⁵·5³, positive integers force y=2 and x=5."],
    sourceUrl,
  },
  {
    id: "2023-23",
    year: 2023,
    number: 23,
    status: "published",
    primaryTopic: "概率",
    secondaryTopics: ["计数与组合"],
    skills: ["计数", "互斥事件"],
    formats: ["方格拼图"],
    difficulty: 5,
    promptZh: "3×3 方格中的每一格独立、等可能地放入图示四种半阴影方砖之一。某个 2×2 小方格中出现一个大阴影菱形的概率是多少？",
    promptEn: "Each cell of a 3-by-3 grid is independently filled with one of four equally likely half-shaded tiles. What is the probability that some 2-by-2 subgrid contains a large shaded diamond?",
    figure: {
      src: "/questions/2023/q23.png",
      altZh: "空白 3×3 方格、四种方向的半阴影方砖，以及包含大阴影菱形的示例铺法。",
      altEn: "A blank 3-by-3 grid, four half-shaded tile orientations, and an example containing a large shaded diamond.",
    },
    options: numericOptions(["1/1024", "1/256", "1/64", "1/16", "1/4"]),
    answer: "C",
    solutionZh: ["全部铺法有 4⁹ 种。大菱形可位于 4 个 2×2 子方格之一；位置确定后其中 4 块方向被固定，其余 5 块任意，因此每个位置有 4⁵ 种。", "两个位置不能同时形成大菱形，所以有利铺法为 4×4⁵=4⁶，概率为 4⁶/4⁹=1/64。"],
    solutionEn: ["There are 4⁹ tilings. For each of four possible 2-by-2 locations, the four inner orientations are forced and the other five cells are free, giving 4⁵ tilings.", "The events cannot overlap, so the probability is 4·4⁵/4⁹=1/64."],
    sourceUrl,
  },
  {
    id: "2023-24",
    year: 2023,
    number: 24,
    status: "published",
    primaryTopic: "几何",
    secondaryTopics: ["代数"],
    skills: ["相似三角形", "面积建模"],
    formats: ["几何图"],
    difficulty: 5,
    promptZh: "等腰三角形 ABC 满足 AB=BC。两幅图中都画了平行于 AC 的线段，且两幅图的阴影面积相等。两个空白部分的高分别为 11 和 5。三角形 ABC 的高 h 是多少？",
    promptEn: "In isosceles triangle ABC with AB=BC, segments parallel to AC create equal shaded areas in the two diagrams. The unshaded heights are 11 and 5. What is the triangle's height h?",
    figure: {
      src: "/questions/2023/q24.png",
      altZh: "两个全等的等腰三角形：左图下方涂色、上方空白高 11；右图上方涂色、下方空白高 5；总高为 h。",
      altEn: "Two congruent isosceles triangles with complementary shaded regions, unshaded heights 11 and 5, and total height h.",
    },
    options: numericOptions(["14.6", "14.8", "15", "15.2", "15.4"]),
    answer: "A",
    solutionZh: ["设整三角形面积为 S。左图阴影面积为 S[1-(11/h)²]，右图阴影小三角形面积为 S[(h-5)/h]²。", "令二者相等，得 h²-121=(h-5)²=h²-10h+25，因此 10h=146，h=14.6。"],
    solutionEn: ["The shaded fractions are 1-(11/h)² on the left and ((h-5)/h)² on the right.", "Equating them gives h²-121=(h-5)², so 10h=146 and h=14.6."],
    sourceUrl,
  },
  {
    id: "2023-25",
    year: 2023,
    number: 25,
    status: "published",
    primaryTopic: "代数",
    secondaryTopics: ["数论"],
    skills: ["等差数列", "范围推理"],
    formats: ["数列"],
    difficulty: 5,
    promptZh: "15 个整数 a₁,a₂,…,a₁₅ 在数轴上依次等距排列，且 1≤a₁≤10，13≤a₂≤20，241≤a₁₅≤250。a₁₄ 的各位数字之和是多少？",
    promptEn: "Fifteen equally spaced integers a₁ through a₁₅ satisfy 1≤a₁≤10, 13≤a₂≤20, and 241≤a₁₅≤250. What is the sum of the digits of a₁₄?",
    options: numericOptions(["8", "9", "10", "11", "12"]),
    answer: "A",
    solutionZh: ["设公差为 d。由首末项范围可得 16.5≤d≤17.8，而 d 为整数，所以 d=17。", "为使 a₂≤20 且 a₁₅≥241，只能有 a₁=3。于是 a₁₄=3+13×17=224，数字和为 2+2+4=8。"],
    solutionEn: ["The endpoint bounds give 16.5≤d≤17.8, so the integer common difference is d=17.", "The remaining bounds force a₁=3. Thus a₁₄=3+13·17=224, whose digit sum is 8."],
    sourceUrl,
  },
];
