import type { Question, QuestionOption } from "./questions";

const numericOptions = (values: string[]): QuestionOption[] =>
  values.map((value, index) => ({
    label: String.fromCharCode(65 + index) as QuestionOption["label"],
    valueZh: value,
  }));

const sourceUrl = "https://live.poshenloh.com/past-contests/amc8/2019";

export const questions2019: Question[] = [
  {
    id: "2019-01",
    year: 2019,
    number: 1,
    status: "published",
    primaryTopic: "算术",
    skills: ["除法与余数", "消费计算"],
    formats: ["文字应用题"],
    difficulty: 1,
    promptZh: "Ike 和 Mike 一共有 30 美元。三明治每个 4.50 美元，饮料每杯 1 美元。他们先买尽可能多的三明治，再用剩余的钱买饮料。两种商品合计会买多少件？",
    promptEn: "Ike and Mike have $30. Sandwiches cost $4.50 each and soft drinks cost $1 each. They buy as many sandwiches as possible, then spend the remainder on drinks. How many items do they buy?",
    options: numericOptions(["6", "7", "8", "9", "10"]),
    answer: "D",
    solutionZh: ["最多可买 6 个三明治，花费 6×4.5=27 美元。", "剩下 3 美元可买 3 杯饮料，共 6+3=9 件。"],
    solutionEn: ["They can buy 6 sandwiches for $27.", "The remaining $3 buys 3 drinks, for 9 items total."],
    sourceUrl,
  },
  {
    id: "2019-02",
    year: 2019,
    number: 2,
    status: "published",
    primaryTopic: "几何",
    skills: ["长方形面积", "图形拼接"],
    formats: ["几何图"],
    difficulty: 1,
    promptZh: "三个全等的小长方形拼成图中的长方形 ABCD。每个小长方形的短边长 5 英尺，求 ABCD 的面积。",
    promptEn: "Three identical rectangles form rectangle ABCD as shown. The short side of each small rectangle is 5 feet. What is the area of ABCD?",
    figure: {
      src: "/questions/2019/q02.png",
      altZh: "两个横放的小长方形叠在左侧，一个竖放的小长方形位于右侧。",
      altEn: "Two horizontal rectangles stacked on the left and one vertical rectangle on the right.",
    },
    options: numericOptions(["45", "75", "100", "125", "150"]),
    answer: "E",
    solutionZh: ["竖放长方形的长边等于左侧两条短边之和，所以长边为 10。", "大长方形高 10、宽 10+5=15，面积为 10×15=150。"],
    solutionEn: ["The long side equals two short sides, so it is 10 feet.", "The large rectangle is 10 by 15, so its area is 150 square feet."],
    sourceUrl,
  },
  {
    id: "2019-03",
    year: 2019,
    number: 3,
    status: "published",
    primaryTopic: "算术",
    skills: ["分数比较", "带分数"],
    formats: ["算式"],
    difficulty: 2,
    promptZh: "把 15/11、19/15、17/13 按从小到大的顺序排列，哪一项正确？",
    promptEn: "Which ordering of 15/11, 19/15, and 17/13 is correct from least to greatest?",
    options: [
      { label: "A", valueZh: "15/11 < 17/13 < 19/15" },
      { label: "B", valueZh: "15/11 < 19/15 < 17/13" },
      { label: "C", valueZh: "17/13 < 19/15 < 15/11" },
      { label: "D", valueZh: "19/15 < 15/11 < 17/13" },
      { label: "E", valueZh: "19/15 < 17/13 < 15/11" },
    ],
    answer: "E",
    solutionZh: ["三者可分别写成 1+4/11、1+4/15、1+4/13。", "分子相同，分母越大分数越小，因此 19/15<17/13<15/11。"],
    solutionEn: ["Rewrite them as 1+4/11, 1+4/15, and 1+4/13.", "With equal numerators, a larger denominator gives a smaller fraction, so 19/15<17/13<15/11."],
    sourceUrl,
  },
  {
    id: "2019-04",
    year: 2019,
    number: 4,
    status: "published",
    primaryTopic: "几何",
    skills: ["菱形", "勾股定理", "面积计算"],
    formats: ["几何图"],
    difficulty: 2,
    promptZh: "菱形 ABCD 的周长为 52 米，对角线 AC 长 24 米。求菱形 ABCD 的面积。",
    promptEn: "Rhombus ABCD has perimeter 52 meters and diagonal AC has length 24 meters. What is its area?",
    figure: {
      src: "/questions/2019/q04.png",
      altZh: "标有 A、B、C、D 的菱形。",
      altEn: "A rhombus labeled A, B, C, and D.",
    },
    options: numericOptions(["60", "90", "105", "120", "144"]),
    answer: "D",
    solutionZh: ["菱形边长为 52÷4=13；对角线互相垂直平分，AC 的一半为 12。", "另一条半对角线为 √(13²-12²)=5，因此面积为 4×(12×5÷2)=120。"],
    solutionEn: ["Each side is 13. The diagonals bisect perpendicularly, and half of AC is 12.", "The other half-diagonal is √(13²-12²)=5, so the area is 4·(12·5/2)=120."],
    sourceUrl,
  },
  {
    id: "2019-05",
    year: 2019,
    number: 5,
    status: "published",
    primaryTopic: "数据与统计",
    skills: ["路程时间图", "图表辨析"],
    formats: ["折线图"],
    difficulty: 1,
    promptZh: "兔子与乌龟赛跑。兔子先快速领先，随后停下睡觉；乌龟全程以较慢的恒定速度前进；兔子醒来后跑向终点，却发现乌龟已经到达。哪种路程—时间图符合描述？",
    promptEn: "A hare runs ahead, stops for a nap, then resumes, but the steadily moving tortoise reaches the finish first. Which distance-versus-time graph matches?",
    options: [
      { label: "A", valueZh: "兔子的折线含水平段，但兔子先到终点" },
      { label: "B", valueZh: "乌龟为匀速直线且先到终点；兔子折线含水平段并后到" },
      { label: "C", valueZh: "兔子睡觉期间路程减少" },
      { label: "D", valueZh: "乌龟的速度中途改变" },
      { label: "E", valueZh: "兔子没有停止，且乌龟速度中途改变" },
    ],
    answer: "B",
    solutionZh: ["兔子睡觉时路程不变，所以兔子的图线必须含水平段。乌龟匀速前进，所以图线是直线。", "乌龟先到终点，兔子图线的终点时间应更晚，符合选项 B。"],
    solutionEn: ["The hare's graph must have a horizontal segment, while the tortoise's steady pace gives a straight line.", "The tortoise reaches the finish earlier, which is shown in B."],
    sourceUrl,
  },
  {
    id: "2019-06",
    year: 2019,
    number: 6,
    status: "published",
    primaryTopic: "概率",
    secondaryTopics: ["几何"],
    skills: ["几何概率", "轴对称", "计数"],
    formats: ["点阵图"],
    difficulty: 2,
    promptZh: "正方形点阵共有 81 个均匀分布的格点，中心点为 P。从其余 80 点中随机选点 Q，直线 PQ 恰为正方形对称轴的概率是多少？",
    promptEn: "A square contains 81 uniformly spaced grid points, with P at the center. Q is chosen from the other 80 points. What is the probability that PQ is a line of symmetry of the square?",
    figure: {
      src: "/questions/2019/q06.png",
      altZh: "9×9 正方形点阵，中心点标为 P。",
      altEn: "A 9-by-9 square grid of points with P at the center.",
    },
    options: numericOptions(["1/5", "1/4", "2/5", "9/20", "1/2"]),
    answer: "C",
    solutionZh: ["正方形有 4 条对称轴：两条对角线和两条中位线。", "每条轴上除 P 外有 8 个点，且这些点互不重复，所以有 4×8=32 个有利点；概率为 32/80=2/5。"],
    solutionEn: ["A square has four symmetry axes: two diagonals and two midpoint lines.", "Each contains 8 eligible points other than P, giving probability 32/80=2/5."],
    sourceUrl,
  },
  {
    id: "2019-07",
    year: 2019,
    number: 7,
    status: "published",
    primaryTopic: "数据与统计",
    skills: ["平均数", "极值"],
    formats: ["文字应用题"],
    difficulty: 2,
    promptZh: "Shauna 参加 5 次满分 100 分的考试，前三次成绩为 76、94、87。若 5 次平均分为 81，她在后两次考试中某一次可能得到的最低分是多少？",
    promptEn: "Shauna takes five 100-point tests and scores 76, 94, and 87 on the first three. To average 81, what is the lowest possible score on one of the other two tests?",
    options: numericOptions(["48", "52", "66", "70", "74"]),
    answer: "A",
    solutionZh: ["5 次总分应为 5×81=405。要使一次成绩最低，就让另一次取最高的 100 分。", "最低分为 405-(76+94+87+100)=48。"],
    solutionEn: ["The five scores must total 405. To minimize one remaining score, maximize the other at 100.", "The minimum is 405-(76+94+87+100)=48."],
    sourceUrl,
  },
  {
    id: "2019-08",
    year: 2019,
    number: 8,
    status: "published",
    primaryTopic: "算术",
    skills: ["连续百分比", "比例计算"],
    formats: ["文字应用题"],
    difficulty: 2,
    promptZh: "Gilda 先把弹珠的 20% 给 Pedro，再把剩余弹珠的 10% 给 Ebony，最后把当时剩余弹珠的 25% 给 Jimmy。她最后留下原来弹珠的百分之几？",
    promptEn: "Gilda gives away 20% of her marbles, then 10% of the remainder, then 25% of what remains. What percent of the original bag is left?",
    options: numericOptions(["20", "33 1/3", "38", "45", "54"]),
    answer: "E",
    solutionZh: ["每次给出后保留的比例依次为 80%、90%、75%。", "最终保留 0.8×0.9×0.75=0.54，即 54%。"],
    solutionEn: ["The retained fractions are 80%, 90%, and 75%.", "Their product is 0.8·0.9·0.75=0.54, or 54%."],
    sourceUrl,
  },
  {
    id: "2019-09",
    year: 2019,
    number: 9,
    status: "published",
    primaryTopic: "几何",
    skills: ["圆柱体积", "比例"],
    formats: ["文字应用题"],
    difficulty: 2,
    promptZh: "Alex 买的圆柱罐直径 6 厘米、高 12 厘米；Felicia 买的圆柱罐直径 12 厘米、高 6 厘米。Alex 的一罐与 Felicia 的一罐体积之比是多少？",
    promptEn: "Alex's cylindrical cans have diameter 6 cm and height 12 cm. Felicia's have diameter 12 cm and height 6 cm. What is the ratio of Alex's can volume to Felicia's?",
    options: numericOptions(["1:4", "1:2", "1:1", "2:1", "4:1"]),
    answer: "B",
    solutionZh: ["Felicia 的半径是 Alex 的 2 倍，底面积是 4 倍；但高度只有一半。", "因此 Felicia 的体积是 Alex 的 2 倍，所求比为 1:2。"],
    solutionEn: ["Felicia's radius is twice Alex's, so her base area is four times as large, while her height is half.", "Her volume is therefore twice Alex's, so the ratio is 1:2."],
    sourceUrl,
  },
  {
    id: "2019-10",
    year: 2019,
    number: 10,
    status: "published",
    primaryTopic: "数据与统计",
    skills: ["平均数", "中位数", "条形图"],
    formats: ["条形图"],
    difficulty: 2,
    promptZh: "条形图记录了周一到周五参加足球训练的学生数。教练后来发现周三实际有 21 人而不是图中的 16 人。更正后，平均数和中位数如何变化？",
    promptEn: "A bar chart shows soccer-practice attendance for five weekdays. Wednesday should be 21 rather than 16. How do the mean and median change after correction?",
    figure: {
      src: "/questions/2019/q10.png",
      altZh: "周一至周五足球训练人数条形图，原图中周三为 16 人。",
      altEn: "A weekday attendance bar chart with Wednesday originally shown as 16.",
    },
    options: [
      { label: "A", valueZh: "平均数增加 1，中位数不变" },
      { label: "B", valueZh: "平均数增加 1，中位数增加 1" },
      { label: "C", valueZh: "平均数增加 1，中位数增加 5" },
      { label: "D", valueZh: "平均数增加 5，中位数增加 1" },
      { label: "E", valueZh: "平均数增加 5，中位数增加 5" },
    ],
    answer: "B",
    solutionZh: ["周三增加 5 人，5 天的平均数增加 5÷5=1。", "原数据中位数为 20；把 16 改为 21 后中位数为 21，因此也增加 1。"],
    solutionEn: ["Increasing one day by 5 raises the five-day mean by 1.", "The median changes from 20 to 21, so it also rises by 1."],
    sourceUrl,
  },
  {
    id: "2019-11",
    year: 2019,
    number: 11,
    status: "published",
    primaryTopic: "计数与组合",
    skills: ["集合", "容斥原理"],
    formats: ["文字应用题"],
    difficulty: 2,
    promptZh: "Lincoln 中学八年级有 93 名学生，每人选修数学、外语或两者都选。70 人选数学，54 人选外语。只选数学而不选外语的有多少人？",
    promptEn: "There are 93 eighth graders; every student takes math, a foreign language, or both. If 70 take math and 54 take a foreign language, how many take only math?",
    options: numericOptions(["16", "23", "31", "39", "70"]),
    answer: "D",
    solutionZh: ["两门都选的人数为 70+54-93=31。", "只选数学的人数为 70-31=39。"],
    solutionEn: ["The overlap is 70+54-93=31.", "Thus 70-31=39 students take only math."],
    sourceUrl,
  },
  {
    id: "2019-12",
    year: 2019,
    number: 12,
    status: "published",
    primaryTopic: "几何",
    skills: ["空间想象", "立方体相对面"],
    formats: ["立体图"],
    difficulty: 2,
    promptZh: "一个立方体的六个面分别涂成红 R、白 W、绿 G、棕 B、水蓝 A、紫 P。根据图中的三个视图，水蓝色面的对面是什么颜色？",
    promptEn: "The six faces of a cube are colored red R, white W, green G, brown B, aqua A, and purple P. From the three views shown, which color is opposite aqua?",
    figure: {
      src: "/questions/2019/q12.png",
      altZh: "同一立方体的三个视图，显示各相邻面的颜色字母。",
      altEn: "Three views of the same cube showing labels on adjacent faces.",
    },
    options: [
      { label: "A", valueZh: "红色" },
      { label: "B", valueZh: "白色" },
      { label: "C", valueZh: "绿色" },
      { label: "D", valueZh: "棕色" },
      { label: "E", valueZh: "紫色" },
    ],
    answer: "A",
    solutionZh: ["由第一、第三个视图可知棕色与紫色相对；由第一、第二个视图可知绿色与白色相对。", "剩下的水蓝色只能与红色相对。"],
    solutionEn: ["The first and third views show brown opposite purple; the first and second show green opposite white.", "The remaining opposite pair is aqua and red."],
    sourceUrl,
  },
  {
    id: "2019-13",
    year: 2019,
    number: 13,
    status: "published",
    primaryTopic: "数论",
    skills: ["回文数", "倍数", "最小值"],
    formats: ["整数题"],
    difficulty: 3,
    promptZh: "回文数从左到右和从右到左读都相同。设 N 是最小的三位非回文数，并且 N 能表示成三个互不相同的两位回文数之和。N 的各位数字之和是多少？",
    promptEn: "Let N be the least three-digit non-palindrome that is the sum of three distinct two-digit palindromes. What is the sum of the digits of N?",
    options: numericOptions(["2", "3", "4", "5", "6"]),
    answer: "A",
    solutionZh: ["两位回文数都是 11 的倍数，所以 N 也必须是 11 的倍数。", "最小的三位非回文 11 的倍数是 110，并且 110=11+22+77；数字和为 1+1+0=2。"],
    solutionEn: ["Every two-digit palindrome is a multiple of 11, so N is a multiple of 11.", "The least three-digit non-palindromic multiple is 110=11+22+77, whose digit sum is 2."],
    sourceUrl,
  },
  {
    id: "2019-14",
    year: 2019,
    number: 14,
    status: "published",
    primaryTopic: "数论",
    secondaryTopics: ["计数与组合"],
    skills: ["星期循环", "模运算", "逻辑排除"],
    formats: ["日历题"],
    difficulty: 3,
    promptZh: "Isabella 有 6 张冰淇淋券，每隔 10 天用一张。店铺周日关门，而她圈出的 6 个日期都不是周日。她第一次用券是星期几？",
    promptEn: "Isabella redeems one of 6 coupons every 10 days. The shop is closed Sundays, yet none of the six dates falls on Sunday. On what weekday is the first redemption?",
    options: [
      { label: "A", valueZh: "星期一" },
      { label: "B", valueZh: "星期二" },
      { label: "C", valueZh: "星期三" },
      { label: "D", valueZh: "星期四" },
      { label: "E", valueZh: "星期五" },
    ],
    answer: "C",
    solutionZh: ["每隔 10 天相当于星期向后移动 3 天。若首次为第 x 天，六次分别是 x、x+3、x+6、x+2、x+5、x+1（模 7）。", "唯一没出现的是 x+4，它必须是周日，所以 x 是周三。"],
    solutionEn: ["Ten days advances the weekday by 3. Relative to the first day x, the six days are x, x+3, x+6, x+2, x+5, and x+1 modulo 7.", "The only missing weekday is x+4, which must be Sunday, so x is Wednesday."],
    sourceUrl,
  },
  {
    id: "2019-15",
    year: 2019,
    number: 15,
    status: "published",
    primaryTopic: "概率",
    secondaryTopics: ["计数与组合"],
    skills: ["条件概率", "集合交集"],
    formats: ["文字应用题"],
    difficulty: 3,
    promptZh: "海滩上有 50 人戴太阳镜、35 人戴帽子。随机选一名戴帽子的人，他也戴太阳镜的概率是 2/5。若改为随机选一名戴太阳镜的人，他也戴帽子的概率是多少？",
    promptEn: "At a beach, 50 people wear sunglasses and 35 wear caps. Given that 2/5 of cap-wearers also wear sunglasses, what fraction of sunglasses-wearers also wear caps?",
    options: numericOptions(["14/85", "7/25", "2/5", "4/7", "7/10"]),
    answer: "B",
    solutionZh: ["同时戴帽子和太阳镜的人数为 35×2/5=14。", "在 50 名戴太阳镜者中，这一比例为 14/50=7/25。"],
    solutionEn: ["The intersection contains 35·2/5=14 people.", "Among 50 sunglasses-wearers, the desired probability is 14/50=7/25."],
    sourceUrl,
  },
  {
    id: "2019-16",
    year: 2019,
    number: 16,
    status: "published",
    primaryTopic: "代数",
    secondaryTopics: ["算术"],
    skills: ["平均速度", "列方程"],
    formats: ["文字应用题"],
    difficulty: 3,
    promptZh: "Qiang 先以平均每小时 30 英里行驶 15 英里。之后还要以每小时 55 英里的速度行驶多少英里，才能使全程平均速度为每小时 50 英里？",
    promptEn: "Qiang drives 15 miles at 30 mph. How many additional miles must he drive at 55 mph to average 50 mph for the entire trip?",
    options: numericOptions(["45", "62", "90", "110", "135"]),
    answer: "D",
    solutionZh: ["前 15 英里用时 15/30=1/2 小时。设之后行驶 x 英里，用时 x/55。", "由 1/2+x/55=(15+x)/50，解得 x=110。"],
    solutionEn: ["The first leg takes 1/2 hour. Let the second distance be x, taking x/55 hours.", "Solving 1/2+x/55=(15+x)/50 gives x=110."],
    sourceUrl,
  },
  {
    id: "2019-17",
    year: 2019,
    number: 17,
    status: "published",
    primaryTopic: "算术",
    secondaryTopics: ["代数"],
    skills: ["连乘约分", "裂项消去"],
    formats: ["算式"],
    difficulty: 3,
    promptZh: "求下列连乘式的值。",
    promptEn: "What is the value of the following product?",
    expression: ["(1·3)/(2·2) · (2·4)/(3·3) · (3·5)/(4·4) · … · (98·100)/(99·99)"],
    options: numericOptions(["1/2", "50/99", "9800/9801", "100/99", "50"]),
    answer: "B",
    solutionZh: ["把每项拆成相邻比值后，中间因子全部消去。", "剩下 (1/2)×(100/99)=50/99。"],
    solutionEn: ["Rewrite each factor as adjacent ratios; all interior factors cancel.", "The remaining product is (1/2)·(100/99)=50/99."],
    sourceUrl,
  },
  {
    id: "2019-18",
    year: 2019,
    number: 18,
    status: "published",
    primaryTopic: "概率",
    secondaryTopics: ["数论"],
    skills: ["奇偶性", "独立事件"],
    formats: ["骰子题"],
    difficulty: 2,
    promptZh: "两个公平骰子的六个面都标有 1、2、3、5、7、8。掷两个骰子，点数和为偶数的概率是多少？",
    promptEn: "Two fair dice have faces numbered 1, 2, 3, 5, 7, and 8. What is the probability that their sum is even?",
    options: numericOptions(["4/9", "1/2", "5/9", "3/5", "2/3"]),
    answer: "C",
    solutionZh: ["每个骰子有 2 个偶数面、4 个奇数面，所以 P(偶)=1/3，P(奇)=2/3。", "和为偶数要求同奇偶，概率为 (1/3)²+(2/3)²=5/9。"],
    solutionEn: ["Each die is even with probability 1/3 and odd with probability 2/3.", "An even sum requires matching parity, so the probability is (1/3)²+(2/3)²=5/9."],
    sourceUrl,
  },
  {
    id: "2019-19",
    year: 2019,
    number: 19,
    status: "published",
    primaryTopic: "计数与组合",
    secondaryTopics: ["代数"],
    skills: ["极值", "赛事计分", "构造验证"],
    formats: ["竞赛计分题"],
    difficulty: 4,
    promptZh: "6 支队伍进行双循环赛，每对队伍交手两次。胜得 3 分、平得 1 分、负得 0 分。比赛结束时前三名同分。前三名每队最多可能得到多少分？",
    promptEn: "Six teams play each other twice. A win earns 3 points, a draw 1, and a loss 0. The top three teams finish tied. What is the greatest possible score for each?",
    options: numericOptions(["22", "23", "24", "26", "30"]),
    answer: "C",
    solutionZh: ["每支强队对后三队共 6 场，最多得 18 分。前三队内部共 6 场，每场最多产生 3 分，总计最多 18 分；若三队同分，每队内部最多平均得到 6 分。", "所以每队最多 18+6=24 分；让强队全胜弱队，并在强队两两交锋中各胜一场即可达到。"],
    solutionEn: ["Each top team can earn at most 18 points against the bottom three. The six games among the top three award at most 18 total points, or 6 per team when tied.", "Thus the maximum is 24, achieved when each top team sweeps the bottom teams and splits its two games against each other top team."],
    sourceUrl,
  },
  {
    id: "2019-20",
    year: 2019,
    number: 20,
    status: "published",
    primaryTopic: "代数",
    skills: ["平方方程", "因式分解", "解的个数"],
    formats: ["方程"],
    difficulty: 3,
    promptZh: "有多少个不同的实数 x 满足 (x²-5)²=16？",
    promptEn: "How many distinct real numbers x satisfy (x²-5)²=16?",
    expression: ["(x² − 5)² = 16"],
    options: numericOptions(["0", "1", "2", "4", "8"]),
    answer: "D",
    solutionZh: ["移项并作平方差分解：(x²-5)²-4²=0，得到 (x²-1)(x²-9)=0。", "所以 x=±1、±3，共 4 个实数。"],
    solutionEn: ["Factor the difference of squares: (x²-5)²-4²=(x²-1)(x²-9)=0.", "Thus x=±1 or ±3, giving four real solutions."],
    sourceUrl,
  },
  {
    id: "2019-21",
    year: 2019,
    number: 21,
    status: "published",
    primaryTopic: "代数",
    secondaryTopics: ["几何"],
    skills: ["直线交点", "坐标几何", "三角形面积"],
    formats: ["方程"],
    difficulty: 3,
    promptZh: "直线 y=5、y=1+x、y=1-x 围成的三角形面积是多少？",
    promptEn: "What is the area of the triangle formed by y=5, y=1+x, and y=1-x?",
    expression: ["y = 5", "y = 1 + x", "y = 1 − x"],
    options: numericOptions(["4", "8", "10", "12", "16"]),
    answer: "E",
    solutionZh: ["y=5 与另外两条直线分别交于 (4,5)、(-4,5)；两斜线交于 (0,1)。", "三角形底为 8、高为 4，面积为 8×4÷2=16。"],
    solutionEn: ["The intersections are (4,5), (-4,5), and (0,1).", "The triangle has base 8 and height 4, so its area is 16."],
    sourceUrl,
  },
  {
    id: "2019-22",
    year: 2019,
    number: 22,
    status: "published",
    primaryTopic: "代数",
    secondaryTopics: ["算术"],
    skills: ["连续百分比", "列方程"],
    formats: ["文字应用题"],
    difficulty: 3,
    promptZh: "商店先把衬衫原价提高某个百分比，再把新价格降低相同的百分比。最终价格是原价的 84%。这个百分比是多少？",
    promptEn: "A store raises a shirt's price by a certain percent and then lowers the new price by the same percent. The result is 84% of the original. What is the percent?",
    options: numericOptions(["16", "20", "28", "36", "40"]),
    answer: "E",
    solutionZh: ["设百分比写成小数为 x，则最终倍率为 (1+x)(1-x)=1-x²。", "由 1-x²=0.84 得 x²=0.16，所以 x=0.4，即 40%。"],
    solutionEn: ["Let the rate be x. The combined multiplier is (1+x)(1-x)=1-x².", "From 1-x²=0.84, x=0.4, so the rate is 40%."],
    sourceUrl,
  },
  {
    id: "2019-23",
    year: 2019,
    number: 23,
    status: "published",
    primaryTopic: "代数",
    secondaryTopics: ["数论"],
    skills: ["分数建模", "整数约束", "范围排除"],
    formats: ["文字应用题"],
    difficulty: 4,
    promptZh: "一场篮球赛中，Alexa 得全队总分的 1/4，Brittany 得 2/7，Chelsea 得 15 分。其余 7 名队员每人不超过 2 分。其余 7 人一共得多少分？",
    promptEn: "Alexa scored 1/4 of a team's points, Brittany 2/7, and Chelsea 15. Each of the other 7 players scored at most 2. What was their combined score?",
    options: numericOptions(["10", "11", "12", "13", "14"]),
    answer: "B",
    solutionZh: ["设总分为 x，其余 7 人合计 y，则 x/4+2x/7+15+y=x，即 y+15=13x/28。", "x 必须是 28 的倍数且 y≤14。x=28 时 y=-2 不合；x=56 时 y=11 合法；下一倍数已使 y>14，所以答案为 11。"],
    solutionEn: ["Let x be the team total and y the other players' total. Then x/4+2x/7+15+y=x, so y+15=13x/28.", "x is a multiple of 28 and y≤14. x=28 fails, x=56 gives y=11, and larger multiples exceed the bound."],
    sourceUrl,
  },
  {
    id: "2019-24",
    year: 2019,
    number: 24,
    status: "published",
    primaryTopic: "几何",
    secondaryTopics: ["代数"],
    skills: ["面积比", "中点", "共高三角形"],
    formats: ["几何图"],
    difficulty: 4,
    promptZh: "在三角形 ABC 中，D 在 AC 上且 AD:DC=1:2；E 是 BD 的中点；直线 AE 与 BC 交于 F。若三角形 ABC 面积为 360，求三角形 EBF 的面积。",
    promptEn: "In triangle ABC, D divides AC with AD:DC=1:2. E is the midpoint of BD, and line AE meets BC at F. If area(ABC)=360, what is area(EBF)?",
    figure: {
      src: "/questions/2019/q24.png",
      altZh: "三角形 ABC 中，D 位于 AC，E 位于 BD，AE 延长交 BC 于 F。",
      altEn: "Triangle ABC with D on AC, E on BD, and AE meeting BC at F.",
    },
    options: numericOptions(["24", "30", "32", "36", "40"]),
    answer: "B",
    solutionZh: ["由 AD:DC=1:2，面积 [ABD]=120、[DBC]=240。E 为 BD 中点，所以 [ABE]=[AED]=60。", "设 [EBF]=x，则 [DEF]=x，故 [ADF]=60+x、[DFC]=240-2x。它们同高且底 AD:DC=1:2，所以 (60+x)/(240-2x)=1/2，解得 x=30。"],
    solutionEn: ["AD:DC=1:2 gives [ABD]=120 and [DBC]=240. Since E is the midpoint of BD, [ABE]=[AED]=60.", "Let [EBF]=x; then [DEF]=x. Thus [ADF]=60+x and [DFC]=240-2x. Their base ratio is 1:2, so (60+x)/(240-2x)=1/2, giving x=30."],
    sourceUrl,
  },
  {
    id: "2019-25",
    year: 2019,
    number: 25,
    status: "published",
    primaryTopic: "计数与组合",
    skills: ["隔板法", "整数解", "分配计数"],
    formats: ["分配题"],
    difficulty: 4,
    promptZh: "Alice 有 24 个苹果，要与 Becky、Chris 分享，使三个人每人至少有 2 个苹果。共有多少种分配方法？",
    promptEn: "Alice has 24 apples. In how many ways can she share them with Becky and Chris so that each of the three people has at least two apples?",
    options: numericOptions(["105", "114", "190", "210", "380"]),
    answer: "C",
    solutionZh: ["先给每人 2 个，剩下 18 个。设三人额外得到 a、b、c 个，则 a+b+c=18，且均为非负整数。", "由隔板法，解数为 C(18+3-1,3-1)=C(20,2)=190。"],
    solutionEn: ["Give each person 2 apples, leaving 18. Let the additional amounts be nonnegative a, b, and c with a+b+c=18.", "Stars and bars gives C(20,2)=190 distributions."],
    sourceUrl,
  },
];
