import type { Question, QuestionOption } from "./questions";

const numericOptions = (values: string[]): QuestionOption[] =>
  values.map((value, index) => ({
    label: String.fromCharCode(65 + index) as QuestionOption["label"],
    valueZh: value,
  }));

const sourceUrl = "https://live.poshenloh.com/past-contests/amc8/2022";

export const questions2022: Question[] = [
  {
    id: "2022-01",
    year: 2022,
    number: 1,
    status: "published",
    primaryTopic: "几何",
    secondaryTopics: ["算术"],
    skills: ["面积计算", "图形分割"],
    formats: ["方格图"],
    difficulty: 1,
    promptZh: "数学队设计了一个乘号形标志，画在边长为 1 英寸的方格纸上。这个标志的面积是多少平方英寸？",
    promptEn: "The Math Team designed a multiplication-sign logo on a grid of 1-inch squares. What is its area in square inches?",
    figure: {
      src: "/questions/2022/q01.png",
      altZh: "边长为 1 的方格纸上画有一个阴影乘号形标志。",
      altEn: "A shaded multiplication-sign logo drawn on a grid of unit squares.",
    },
    options: numericOptions(["10", "12", "13", "14", "15"]),
    answer: "A",
    solutionZh: ["标志可分成 5 个全等的倾斜正方形，每个正方形的两条对角线都长 2。", "每个面积为 2×2÷2=2，所以总面积为 5×2=10。"],
    solutionEn: ["The logo consists of five congruent tilted squares, each with two diagonals of length 2.", "Each has area 2·2/2=2, so the total area is 10."],
    sourceUrl,
  },
  {
    id: "2022-02",
    year: 2022,
    number: 2,
    status: "published",
    primaryTopic: "代数",
    secondaryTopics: ["算术"],
    skills: ["运算定义", "代入计算"],
    formats: ["算式"],
    difficulty: 1,
    promptZh: "定义 a◇b=a²-b²，a★b=(a-b)²。求 (5◇3)★6 的值。",
    promptEn: "Define a◇b=a²-b² and a★b=(a-b)². Compute (5◇3)★6.",
    expression: ["a ◇ b = a² − b²", "a ★ b = (a − b)²", "(5 ◇ 3) ★ 6"],
    options: numericOptions(["−20", "4", "16", "100", "220"]),
    answer: "D",
    solutionZh: ["先算 5◇3=5²-3²=16。", "再算 16★6=(16-6)²=100。"],
    solutionEn: ["First, 5◇3=25-9=16.", "Then 16★6=(16-6)²=100."],
    sourceUrl,
  },
  {
    id: "2022-03",
    year: 2022,
    number: 3,
    status: "published",
    primaryTopic: "数论",
    secondaryTopics: ["计数与组合"],
    skills: ["因数分解", "分类枚举"],
    formats: ["整数题"],
    difficulty: 2,
    promptZh: "三个正整数 a、b、c 的乘积是 100，且 a<b<c。共有多少种选法？",
    promptEn: "Three positive integers a,b,c have product 100 and satisfy a<b<c. In how many ways can they be chosen?",
    options: numericOptions(["0", "1", "2", "3", "4"]),
    answer: "E",
    solutionZh: ["a³<100 且 a 是 100 的因数，所以 a 只能是 1、2、4。", "a=1 时有 (b,c)=(2,50),(4,25),(5,20)；a=2 时有 (5,10)；a=4 时没有可行解，共 4 种。"],
    solutionEn: ["Because a³<100 and a divides 100, a is 1, 2, or 4.", "These give three triples for a=1, one for a=2, and none for a=4, for a total of 4."],
    sourceUrl,
  },
  {
    id: "2022-04",
    year: 2022,
    number: 4,
    status: "published",
    primaryTopic: "几何",
    skills: ["轴对称", "空间想象"],
    formats: ["几何图"],
    difficulty: 2,
    promptZh: "图中的字母 M 先关于斜线 q 对称，再关于水平线 p 对称。最终图像是哪一个？",
    promptEn: "The letter M is reflected first over line q and then over line p. Which option is the resulting image?",
    figure: {
      src: "/questions/2022/q04.png",
      altZh: "水平线 p、斜线 q 和位于交点右上方的字母 M。",
      altEn: "A horizontal line p, diagonal line q, and the letter M above and to the right of their intersection.",
    },
    options: [
      { label: "A", valueZh: "位于右下方，字形横置向左" },
      { label: "B", valueZh: "位于左上方，字形横置" },
      { label: "C", valueZh: "位于左上方靠近 p，字形横置向右" },
      { label: "D", valueZh: "位于左下方，字母倒置" },
      { label: "E", valueZh: "位于右下方，字形横置向右" },
    ],
    answer: "E",
    solutionZh: ["先关于 q 镜像，再关于 p 镜像，相当于把位置和字形方向依次翻转。", "最终字母位于 p 下方、竖线右侧，方向与选项 E 一致。"],
    solutionEn: ["Reflect the position and orientation across q, then reflect that image across p.", "The result lies below p and to the right of the vertical line with the orientation shown in E."],
    sourceUrl,
  },
  {
    id: "2022-05",
    year: 2022,
    number: 5,
    status: "published",
    primaryTopic: "算术",
    skills: ["年龄问题", "建模"],
    formats: ["文字应用题"],
    difficulty: 1,
    promptZh: "五年前 Bella 满 6 岁时收到一只刚出生的小猫。今天 Anna、Bella 和小猫的年龄和是 30。Anna 比 Bella 大几岁？",
    promptEn: "Five years ago, when Bella turned 6, she received a newborn kitten. Today Anna, Bella, and the kitten have a combined age of 30. How much older is Anna than Bella?",
    options: numericOptions(["1", "2", "3", "4", "5"]),
    answer: "C",
    solutionZh: ["Bella 现在 11 岁，小猫现在 5 岁，所以 Anna 为 30-11-5=14 岁。", "Anna 比 Bella 大 14-11=3 岁。"],
    solutionEn: ["Bella is 11 and the kitten is 5, so Anna is 30-11-5=14.", "Anna is 14-11=3 years older."],
    sourceUrl,
  },
  {
    id: "2022-06",
    year: 2022,
    number: 6,
    status: "published",
    primaryTopic: "代数",
    skills: ["等差数列", "列方程"],
    formats: ["数轴题"],
    difficulty: 2,
    promptZh: "三个正整数在数轴上等距排列，中间的数是 15，最大的数是最小数的 4 倍。最小数是多少？",
    promptEn: "Three positive integers are equally spaced. The middle number is 15 and the largest is four times the smallest. What is the smallest number?",
    options: numericOptions(["4", "5", "6", "7", "8"]),
    answer: "C",
    solutionZh: ["设最小数为 x，最大数为 4x。等距排列时中间数等于两端平均数。", "因此 (x+4x)/2=15，解得 x=6。"],
    solutionEn: ["Let the smallest number be x, so the largest is 4x. The middle is their average.", "Thus (x+4x)/2=15, giving x=6."],
    sourceUrl,
  },
  {
    id: "2022-07",
    year: 2022,
    number: 7,
    status: "published",
    primaryTopic: "算术",
    skills: ["单位换算", "速度计算"],
    formats: ["文字应用题"],
    difficulty: 2,
    promptZh: "下载速度为每秒 56 千比特时，下载一首 4.2 兆字节的歌曲大约需要多少分钟？已知 1 兆字节等于 8000 千比特。",
    promptEn: "At 56 kilobits per second, approximately how many minutes would it take to download a 4.2-megabyte song, using 8000 kilobits per megabyte?",
    options: numericOptions(["0.6", "10", "1800", "7200", "36000"]),
    answer: "B",
    solutionZh: ["文件大小为 4.2×8000=33,600 千比特。", "下载时间为 33,600÷56=600 秒，也就是 10 分钟。"],
    solutionEn: ["The file contains 4.2·8000=33,600 kilobits.", "At 56 kilobits per second, this takes 600 seconds, or 10 minutes."],
    sourceUrl,
  },
  {
    id: "2022-08",
    year: 2022,
    number: 8,
    status: "published",
    primaryTopic: "算术",
    secondaryTopics: ["代数"],
    skills: ["连乘约分", "找规律"],
    formats: ["算式"],
    difficulty: 2,
    promptZh: "下面连乘式的值是多少？",
    promptEn: "What is the value of the following product?",
    expression: ["(1/3)·(2/4)·(3/5)·⋯·(18/20)·(19/21)·(20/22)"],
    options: numericOptions(["1/462", "1/231", "1/132", "2/213", "1/22"]),
    answer: "B",
    solutionZh: ["分子中的 3 到 20 与分母中的 3 到 20 全部约掉。", "剩下 1×2/(21×22)=2/462=1/231。"],
    solutionEn: ["The factors 3 through 20 cancel between numerator and denominator.", "The product becomes 1·2/(21·22)=1/231."],
    sourceUrl,
  },
  {
    id: "2022-09",
    year: 2022,
    number: 9,
    status: "published",
    primaryTopic: "算术",
    secondaryTopics: ["代数"],
    skills: ["指数衰减", "连续变化"],
    formats: ["文字应用题"],
    difficulty: 2,
    promptZh: "一杯 212°F 的沸水放在恒温 68°F 的房间里。水温与室温之差每 5 分钟减半。15 分钟后水温是多少华氏度？",
    promptEn: "Water at 212°F cools in a 68°F room. The difference between water and room temperature halves every 5 minutes. What is the water temperature after 15 minutes?",
    options: numericOptions(["77", "86", "92", "98", "104"]),
    answer: "B",
    solutionZh: ["初始温差为 212-68=144°F。15 分钟经历三次减半，温差变为 144÷8=18°F。", "水温为 68+18=86°F。"],
    solutionEn: ["The initial temperature difference is 144°F. After three halvings it is 18°F.", "The water temperature is 68+18=86°F."],
    sourceUrl,
  },
  {
    id: "2022-10",
    year: 2022,
    number: 10,
    status: "published",
    primaryTopic: "数据与统计",
    secondaryTopics: ["算术"],
    skills: ["函数图像", "速度建模"],
    formats: ["统计图"],
    difficulty: 2,
    promptZh: "Ling 上午 8 点从家以每小时 45 英里驾车，上午 10 点到达徒步起点；徒步 3 小时后，以每小时 60 英里驾车回家。哪幅图正确表示汽车与家的距离随时间变化？",
    promptEn: "Ling drives from 8 to 10 AM at 45 mph, hikes for 3 hours, then drives home at 60 mph. Which graph correctly shows the car's distance from home over time?",
    options: [
      { label: "A", valueZh: "10 点到 90 英里，1 点返程，3 点到家" },
      { label: "B", valueZh: "10 点到 45 英里，1 点返程，3 点到家" },
      { label: "C", valueZh: "10 点到 45 英里，1 点返程，2:30 到家" },
      { label: "D", valueZh: "10 点到 120 英里，1 点返程，4 点到家" },
      { label: "E", valueZh: "10 点到 90 英里，1 点返程，2:30 到家" },
    ],
    answer: "E",
    solutionZh: ["去程 2 小时共行 45×2=90 英里，所以图像在 10 点到达 90，并在徒步的 3 小时内保持不变。", "返程需要 90÷60=1.5 小时，从下午 1 点到 2:30；符合选项 E。"],
    solutionEn: ["The trail is 45·2=90 miles away, and the graph stays flat during the 3-hour hike.", "The return takes 90/60=1.5 hours, from 1 PM to 2:30 PM, matching E."],
    sourceUrl,
  },
  {
    id: "2022-11",
    year: 2022,
    number: 11,
    status: "published",
    primaryTopic: "算术",
    skills: ["逆向推理", "计数"],
    formats: ["文字应用题"],
    difficulty: 2,
    promptZh: "Henry 每次从一段意大利面中间咬掉 3 英寸。最后共有 10 段，总长度为 17 英寸。最初的意大利面长多少英寸？",
    promptEn: "Henry removes 3 inches from the middle of one pasta piece per bite. He ends with 10 pieces totaling 17 inches. How long was the original piece?",
    options: numericOptions(["34", "38", "41", "44", "47"]),
    answer: "D",
    solutionZh: ["每咬一次，段数增加 1；从 1 段变成 10 段，需要 9 次。", "共吃掉 9×3=27 英寸，所以原长为 27+17=44 英寸。"],
    solutionEn: ["Each bite increases the number of pieces by one, so 9 bites create 10 pieces.", "The removed length is 27 inches, making the original length 27+17=44."],
    sourceUrl,
  },
  {
    id: "2022-12",
    year: 2022,
    number: 12,
    status: "published",
    primaryTopic: "概率",
    secondaryTopics: ["数论"],
    skills: ["样本空间", "完全平方数"],
    formats: ["转盘图"],
    difficulty: 3,
    promptZh: "两个等分转盘各转一次。令 N 等于转盘 A 上的数乘 10，再加上转盘 B 上的数。N 是完全平方数的概率是多少？",
    promptEn: "Spin both four-section spinners. Let N be ten times the number on Spinner A plus the number on Spinner B. What is the probability that N is a perfect square?",
    figure: {
      src: "/questions/2022/q12.png",
      altZh: "转盘 A 的四格为 5、6、7、8；转盘 B 的四格为 1、2、3、4。",
      altEn: "Spinner A has 5,6,7,8 and Spinner B has 1,2,3,4 in four equal sectors.",
    },
    options: numericOptions(["1/16", "1/8", "1/4", "3/8", "1/2"]),
    answer: "B",
    solutionZh: ["共有 4×4=16 个等可能的两位数。51 到 84 之间可形成的完全平方数只有 64 和 81。", "所以概率为 2/16=1/8。"],
    solutionEn: ["There are 16 equally likely two-digit numbers.", "The only possible squares are 64 and 81, so the probability is 2/16=1/8."],
    sourceUrl,
  },
  {
    id: "2022-13",
    year: 2022,
    number: 13,
    status: "published",
    primaryTopic: "代数",
    secondaryTopics: ["数论"],
    skills: ["列方程", "整数范围"],
    formats: ["文字应用题"],
    difficulty: 3,
    promptZh: "句子“一个正整数比另一个正整数的两倍多 ___，且两数之和为 28”中的空格可以填多少个不同的正整数？",
    promptEn: "How many positive integers can fill the blank: one positive integer is ___ more than twice another, and the two numbers sum to 28?",
    options: numericOptions(["6", "7", "8", "9", "10"]),
    answer: "D",
    solutionZh: ["设较小数为 x，空格为 c，则另一个数为 2x+c，且 3x+c=28。", "所以 c=28-3x>0，正整数 x 可取 1 到 9，对应 9 个不同的正整数 c。"],
    solutionEn: ["Let the smaller integer be x and the blank be c. Then 3x+c=28.", "The condition c=28-3x>0 allows x=1 through 9, giving 9 possible values."],
    sourceUrl,
  },
  {
    id: "2022-14",
    year: 2022,
    number: 14,
    status: "published",
    primaryTopic: "计数与组合",
    skills: ["排列", "插空法"],
    formats: ["字母排列题"],
    difficulty: 3,
    promptZh: "单词 BEEKEEPER 的字母有多少种重排方式，使任意两个 E 都不相邻？",
    promptEn: "In how many rearrangements of BEEKEEPER are no two E's adjacent?",
    options: numericOptions(["1", "4", "12", "24", "120"]),
    answer: "D",
    solutionZh: ["共有 5 个 E 和 4 个互不相同的其他字母 B、K、P、R。为使 E 不相邻，只能排成 E_E_E_E_E。", "四个其他字母填入四个空位，有 4!=24 种。"],
    solutionEn: ["The five E's must occupy the pattern E_E_E_E_E.", "The distinct letters B,K,P,R fill the four gaps in 4!=24 ways."],
    sourceUrl,
  },
  {
    id: "2022-15",
    year: 2022,
    number: 15,
    status: "published",
    primaryTopic: "数据与统计",
    secondaryTopics: ["算术"],
    skills: ["散点图", "单位价格"],
    formats: ["统计图"],
    difficulty: 3,
    promptZh: "散点图给出 30 种黑胡椒的重量和价格。哪一种重量（盎司）的胡椒每盎司价格最低？",
    promptEn: "The scatter plot shows weights and prices of thirty black pepper options. What weight in ounces has the lowest price per ounce?",
    figure: {
      src: "/questions/2022/q15.png",
      altZh: "横轴为 1 到 5 盎司、纵轴为价格的黑胡椒散点图。",
      altEn: "A scatter plot of pepper price versus weight from 1 to 5 ounces.",
    },
    options: numericOptions(["1", "2", "3", "4", "5"]),
    answer: "C",
    solutionZh: ["对每个重量只需比较该列最低价格点的“价格÷重量”。", "3 盎司的最低价格约为 2.5 美元，每盎司约 0.83 美元，比 1、2、4、5 盎司各自的最低单位价格都小。"],
    solutionEn: ["For each weight, compare the lowest plotted price divided by that weight.", "The 3-ounce option is about $2.50, or about $0.83 per ounce, the smallest ratio."],
    sourceUrl,
  },
  {
    id: "2022-16",
    year: 2022,
    number: 16,
    status: "published",
    primaryTopic: "代数",
    secondaryTopics: ["算术"],
    skills: ["平均数", "消元"],
    formats: ["数据题"],
    difficulty: 3,
    promptZh: "四个数依次排成一行。前两个数的平均数是 21，中间两个数的平均数是 26，后两个数的平均数是 30。第一个数和最后一个数的平均数是多少？",
    promptEn: "Four numbers are in a row. The averages of the first two, middle two, and last two are 21, 26, and 30. What is the average of the first and last numbers?",
    options: numericOptions(["24", "25", "26", "27", "28"]),
    answer: "B",
    solutionZh: ["设四个数为 a,b,c,d，则 a+b=42，b+c=52，c+d=60。", "由 (a+b+c+d)-(b+c)=102-52=50 得 a+d=50，所以平均数是 25。"],
    solutionEn: ["Let the numbers be a,b,c,d. Then a+b=42, b+c=52, and c+d=60.", "Thus a+d=(42+60)-52=50, so their average is 25."],
    sourceUrl,
  },
  {
    id: "2022-17",
    year: 2022,
    number: 17,
    status: "published",
    primaryTopic: "数论",
    skills: ["个位数", "阶乘", "模运算"],
    formats: ["算式"],
    difficulty: 4,
    promptZh: "偶数 n 的双阶乘 n!! 是 2 到 n 的所有偶数之积。求 2!!+4!!+⋯+2022!! 的个位数字。",
    promptEn: "For even n, n!! is the product of all even integers from 2 to n. What is the units digit of 2!!+4!!+⋯+2022!!?",
    options: numericOptions(["0", "2", "4", "6", "8"]),
    answer: "B",
    solutionZh: ["当 n≥10 时，n!! 含因子 10，所以这些项个位都是 0。", "只需算 2!!+4!!+6!!+8!!=2+8+48+384=442，个位是 2。"],
    solutionEn: ["For every even n≥10, n!! contains a factor of 10 and ends in 0.", "The first four terms sum to 442, whose units digit is 2."],
    sourceUrl,
  },
  {
    id: "2022-18",
    year: 2022,
    number: 18,
    status: "published",
    primaryTopic: "几何",
    secondaryTopics: ["代数"],
    skills: ["坐标几何", "中点四边形", "面积计算"],
    formats: ["坐标题"],
    difficulty: 4,
    promptZh: "一个长方形四条边的中点分别是 (−3,0)、(2,0)、(5,4)、(0,4)。这个长方形的面积是多少？",
    promptEn: "The side midpoints of a rectangle are (−3,0), (2,0), (5,4), and (0,4). What is the rectangle's area?",
    options: numericOptions(["20", "25", "40", "50", "80"]),
    answer: "C",
    solutionZh: ["四个中点形成平行四边形，水平底长 5，高为 4，面积为 20。", "长方形的中点四边形面积是原长方形的一半，所以原面积为 40。"],
    solutionEn: ["The midpoint parallelogram has base 5, height 4, and area 20.", "A rectangle's midpoint parallelogram has half its area, so the rectangle's area is 40."],
    sourceUrl,
  },
  {
    id: "2022-19",
    year: 2022,
    number: 19,
    status: "published",
    primaryTopic: "数据与统计",
    skills: ["点图", "中位数", "最值"],
    formats: ["统计图"],
    difficulty: 4,
    promptZh: "点图表示 20 名学生的考试成绩。老师给部分学生加 5 分后，中位数升到 85。最少有多少名学生得到加分？",
    promptEn: "A dot plot shows 20 test scores. After some students receive 5 extra points, the median becomes 85. What is the minimum number of students receiving points?",
    figure: {
      src: "/questions/2022/q19.png",
      altZh: "成绩 65、70、75、80、85、90、95、100 的点图，共 20 个数据点。",
      altEn: "A dot plot of 20 scores at multiples of five from 65 through 100.",
    },
    options: numericOptions(["2", "3", "4", "5", "6"]),
    answer: "C",
    solutionZh: ["要使 20 个成绩的中位数为 85，第 10、11 个成绩都必须达到 85；否则需要至少 10 个成绩达到 90，但图中做不到。", "原来只有 7 个成绩至少为 85，把 4 个 80 分提高到 85 后恰有至少 11 个，因此最少 4 人。"],
    solutionEn: ["The 10th and 11th scores must both become 85; an average of unequal middle scores would require too many scores of at least 90.", "There are initially 7 scores of at least 85, so four 80s must be raised to 85."],
    sourceUrl,
  },
  {
    id: "2022-20",
    year: 2022,
    number: 20,
    status: "published",
    primaryTopic: "代数",
    secondaryTopics: ["数论"],
    skills: ["方阵和", "不等式", "最值"],
    formats: ["方格图"],
    difficulty: 4,
    promptZh: "在 3×3 方格中填整数，使每行与每列的和都相同。四个数缺失，左下角的 x 大于另外三个缺失数。x 的最小可能值是多少？",
    promptEn: "Fill the 3-by-3 grid with integers so every row and column has the same sum. The lower-left x exceeds the other three missing entries. What is the least possible x?",
    figure: {
      src: "/questions/2022/q20.png",
      altZh: "3×3 方格，第一行为 −2、9、5，中右为 −1，右下为 8，左下为 x，其余三格空白。",
      altEn: "A 3-by-3 grid containing -2, 9, 5, -1, 8, and x, with three other blanks.",
    },
    options: numericOptions(["−1", "5", "6", "8", "9"]),
    answer: "D",
    solutionZh: ["第一行和为 12，所以每行每列都和为 12。其余三个缺失数可表示为 14-x、4-x、x-1。", "要求 x 大于它们，最强条件为 x>14-x，即 x>7；最小整数是 8。"],
    solutionEn: ["Every row and column sums to 12. The other missing entries are 14-x, 4-x, and x-1.", "The strongest inequality is x>14-x, so x>7 and the least integer is 8."],
    sourceUrl,
  },
  {
    id: "2022-21",
    year: 2022,
    number: 21,
    status: "published",
    primaryTopic: "代数",
    secondaryTopics: ["数据与统计"],
    skills: ["百分比", "整数约束", "逻辑推理"],
    formats: ["表格"],
    difficulty: 4,
    promptZh: "Steph 上半场 20 投 15 中、下半场 10 投 10 中。Candace 上半场投 12 次、下半场投 18 次；每半场命中率都低于 Steph，但全场总命中率与 Steph 相同。Candace 下半场比上半场多进多少球？",
    promptEn: "Steph makes 15 of 20 and then 10 of 10. Candace attempts 12 and 18, has a lower percentage in each half, but the same overall percentage. How many more baskets does Candace make in the second half?",
    figure: {
      src: "/questions/2022/q21.png",
      altZh: "Steph 与 Candace 上、下半场命中数和出手数的对照表，Candace 的命中数留空。",
      altEn: "A first-half and second-half shooting table for Steph and Candace, with Candace's makes blank.",
    },
    options: numericOptions(["7", "8", "9", "10", "11"]),
    answer: "C",
    solutionZh: ["Steph 全场 30 投 25 中；Candace 也是 30 次出手且总命中率相同，所以也进 25 球。", "设 Candace 上、下半场命中 f、s 球。f<9、s<18 且 f+s=25，只能是 f=8、s=17，因此相差 9。"],
    solutionEn: ["Steph makes 25 of 30, so Candace also makes 25 of her 30 attempts.", "The half-by-half inequalities give f≤8 and s≤17; with f+s=25, they are 8 and 17, a difference of 9."],
    sourceUrl,
  },
  {
    id: "2022-22",
    year: 2022,
    number: 22,
    status: "published",
    primaryTopic: "算术",
    secondaryTopics: ["代数"],
    skills: ["时间线", "追及问题", "逻辑推理"],
    formats: ["路径图"],
    difficulty: 4,
    promptZh: "公交车站间行驶 2 分钟，每站停 1 分钟；Zia 步行一站需 5 分钟。她到站时，若公交车已在前一站或已离开前一站，她就等车，否则继续走。两者同时出发，公交车落后 3 站。多少分钟后 Zia 上车？",
    promptEn: "A bus drives 2 minutes between stops and waits 1 minute at each. Zia walks 5 minutes per stop and follows the stated waiting rule. Starting together with the bus 3 stops behind, when does she board?",
    figure: {
      src: "/questions/2022/q22.png",
      altZh: "通往图书馆的一列等距公交站，公交车位于 Zia 身后三站。",
      altEn: "Equally spaced stops leading to a library, with the bus three stops behind Zia.",
    },
    options: numericOptions(["17", "19", "20", "21", "23"]),
    answer: "A",
    solutionZh: ["公交车每 3 分钟完成“行驶一站并停靠”的循环；Zia 每 5 分钟到一个站。", "第 5、10 分钟她继续走；第 15 分钟她到第 6 站时，公交车已在前一站，于是等待。公交车再用 2 分钟到达，她在第 17 分钟上车。"],
    solutionEn: ["The bus completes each travel-and-wait cycle in 3 minutes, while Zia reaches stops every 5 minutes.", "At minute 15 the bus is at the previous stop, so she waits; it reaches her 2 minutes later, at minute 17."],
    sourceUrl,
  },
  {
    id: "2022-23",
    year: 2022,
    number: 23,
    status: "published",
    primaryTopic: "计数与组合",
    skills: ["分类枚举", "对称", "棋盘计数"],
    formats: ["方格图"],
    difficulty: 5,
    promptZh: "3×3 方格的每格放一个三角形或圆形。既有三个三角形连成一线，又有三个圆形连成一线的配置共有多少种？",
    promptEn: "Each cell of a 3-by-3 grid contains a triangle or circle. How many configurations have a line of three triangles and a line of three circles?",
    figure: {
      src: "/questions/2022/q23.png",
      altZh: "一个 3×3 示例方格，格内放有三角形和圆形。",
      altEn: "A sample 3-by-3 grid filled with triangles and circles.",
    },
    options: numericOptions(["39", "42", "78", "84", "96"]),
    answer: "D",
    solutionZh: ["设三角形个数为 k，则必须有 3≤k≤6。k=3 时三角形只能占一整行或一整列，共 6 种；由对称性 k=6 也有 6 种。", "k=4 时先选一条三角形行或列，再在剩余 6 格放额外三角形，共 6×6=36 种；k=5 同样有 36 种。总数 6+36+36+6=84。"],
    solutionEn: ["Let k be the number of triangles. For k=3 and k=6, there are 6 valid configurations each.", "For k=4 and k=5, there are 36 each, giving 6+36+36+6=84."],
    sourceUrl,
  },
  {
    id: "2022-24",
    year: 2022,
    number: 24,
    status: "published",
    primaryTopic: "几何",
    skills: ["展开图", "勾股关系", "体积计算"],
    formats: ["几何图"],
    difficulty: 5,
    promptZh: "多边形 ABCDEFGH 由长方形和直角三角形组成，沿虚线折叠后成为三棱柱。已知 AH=EF=8、GH=14，求三棱柱体积。",
    promptEn: "The polygon ABCDEFGH folds along the dotted lines into a triangular prism. Given AH=EF=8 and GH=14, what is the prism's volume?",
    figure: {
      src: "/questions/2022/q24.png",
      altZh: "由三个长方形和两个直角三角形组成的三棱柱展开图，顶点标为 A 到 J。",
      altEn: "A triangular-prism net of rectangles and right triangles with labeled vertices A through J.",
    },
    options: numericOptions(["112", "128", "192", "240", "288"]),
    answer: "C",
    solutionZh: ["折叠对应边可得 GF=EF=8、AB=BC=8、HJ=8、BJ=AH=8。又 GH=14，所以 GJ=6。", "底面直角三角形 BJG 面积为 6×8÷2=24，棱柱长 GF=8，体积为 24×8=192。"],
    solutionEn: ["Matching folded edges give BJ=8, GF=8, and GJ=GH-HJ=14-8=6.", "The triangular base area is 6·8/2=24, and multiplying by prism length 8 gives 192."],
    sourceUrl,
  },
  {
    id: "2022-25",
    year: 2022,
    number: 25,
    status: "published",
    primaryTopic: "概率",
    secondaryTopics: ["代数"],
    skills: ["递推", "条件概率", "状态转移"],
    formats: ["过程题"],
    difficulty: 5,
    promptZh: "一只蟋蟀在 4 片叶子之间随机跳跃，每次等可能地跳到另外 3 片叶子中的一片。跳 4 次后，它回到起始叶子的概率是多少？",
    promptEn: "A cricket hops among four leaves, each time choosing one of the other three uniformly. What is the probability it is back on its starting leaf after four hops?",
    options: numericOptions(["2/9", "19/80", "20/81", "1/4", "7/27"]),
    answer: "E",
    solutionZh: ["设 pₙ 为跳 n 次后在起点的概率。从起点下一步必离开；不在起点时，下一步以 1/3 概率回到起点，所以 pₙ₊₁=(1-pₙ)/3。", "由 p₀=1 得 p₁=0、p₂=1/3、p₃=2/9、p₄=(1-2/9)/3=7/27。"],
    solutionEn: ["Let pₙ be the probability of being at the start after n hops. Then pₙ₊₁=(1-pₙ)/3.", "Starting from p₀=1 gives p₃=2/9 and p₄=(1-2/9)/3=7/27."],
    sourceUrl,
  },
];
