import type { Question, QuestionOption } from "./questions";

const numericOptions = (values: string[]): QuestionOption[] =>
  values.map((value, index) => ({
    label: String.fromCharCode(65 + index) as QuestionOption["label"],
    valueZh: value,
  }));

const sourceUrl = "https://live.poshenloh.com/past-contests/amc8/2024";

export const questions2024: Question[] = [
  {
    id: "2024-01",
    year: 2024,
    number: 1,
    status: "published",
    primaryTopic: "数论",
    secondaryTopics: ["算术"],
    skills: ["个位数", "模运算"],
    formats: ["算式"],
    difficulty: 1,
    promptZh: "下面算式的个位数字是多少？",
    promptEn: "What is the ones digit of the following expression?",
    expression: ["222,222 - 22,222 - 2,222", "- 222 - 22 - 2"],
    options: numericOptions(["0", "2", "4", "6", "8"]),
    answer: "B",
    solutionZh: ["只看个位，原式与 2-2-2-2-2-2=-8 同余。", "-8 除以 10 的余数为 2，所以个位是 2。"],
    solutionEn: ["Only the ones digits matter: 2-2-2-2-2-2 = -8.", "Since -8 is congruent to 2 modulo 10, the ones digit is 2."],
    sourceUrl,
  },
  {
    id: "2024-02",
    year: 2024,
    number: 2,
    status: "published",
    primaryTopic: "算术",
    skills: ["分数化简", "小数计算"],
    formats: ["算式"],
    difficulty: 1,
    promptZh: "下面算式写成小数是多少？",
    promptEn: "What is the value of this expression in decimal form?",
    expression: ["44/11 + 110/44 + 44/1100"],
    options: numericOptions(["6.4", "6.504", "6.54", "6.9", "6.94"]),
    answer: "C",
    solutionZh: ["三项分别为 4、2.5 和 0.04。", "相加得 4+2.5+0.04=6.54。"],
    solutionEn: ["The three terms simplify to 4, 2.5, and 0.04.", "Their sum is 6.54."],
    sourceUrl,
  },
  {
    id: "2024-03",
    year: 2024,
    number: 3,
    status: "published",
    primaryTopic: "几何",
    skills: ["面积计算", "图形分割"],
    formats: ["几何图"],
    difficulty: 2,
    promptZh: "边长为 4、7、9、10 的四个正方形按从小到大叠放，左边和下边对齐，并交替涂色。可见阴影部分的面积是多少？",
    promptEn: "Squares of side lengths 4, 7, 9, and 10 are aligned at their left and bottom edges and alternate shaded and unshaded. What is the visible shaded area?",
    figure: {
      src: "/questions/2024/q03.png",
      altZh: "四个左下角对齐、边长为 4、7、9、10 的嵌套正方形，区域交替涂色。",
      altEn: "Four nested squares of side lengths 4, 7, 9, and 10 aligned at the lower-left corner with alternating shading.",
    },
    options: numericOptions(["42", "45", "49", "50", "52"]),
    answer: "E",
    solutionZh: ["可见阴影由边长 10 与 9 的面积差，以及边长 7 与 4 的面积差组成。", "面积为 10²-9²+7²-4²=19+33=52。"],
    solutionEn: ["The shaded area is the 10-by-10 square minus the 9-by-9 square, plus the 7-by-7 square minus the 4-by-4 square.", "This is 100-81+49-16=52."],
    sourceUrl,
  },
  {
    id: "2024-04",
    year: 2024,
    number: 4,
    status: "published",
    primaryTopic: "算术",
    skills: ["求和", "完全平方数"],
    formats: ["文字应用题"],
    difficulty: 1,
    promptZh: "Yunji 把 1 到 9 的整数相加时漏掉了一个数，错误总和恰好是完全平方数。她漏掉了哪个数？",
    promptEn: "When Yunji added the integers from 1 to 9, she left out one number and obtained a square number. Which number did she leave out?",
    options: numericOptions(["5", "6", "7", "8", "9"]),
    answer: "E",
    solutionZh: ["1 到 9 的和是 45。", "小于 45 的最大完全平方数是 36，因此漏掉的数是 45-36=9。"],
    solutionEn: ["The sum from 1 to 9 is 45.", "The largest square below 45 is 36, so the missing number is 9."],
    sourceUrl,
  },
  {
    id: "2024-05",
    year: 2024,
    number: 5,
    status: "published",
    primaryTopic: "数论",
    secondaryTopics: ["计数与组合"],
    skills: ["整除", "分类枚举"],
    formats: ["骰子题"],
    difficulty: 2,
    promptZh: "Aaliyah 掷两个标准六面骰子，所得两数的乘积是 6 的倍数。下列哪个整数不可能是两数之和？",
    promptEn: "Two standard dice are rolled and their product is a multiple of 6. Which integer cannot be their sum?",
    options: numericOptions(["5", "6", "7", "8", "9"]),
    answer: "B",
    solutionZh: ["和为 5、7、8、9 可分别由 (2,3)、(1,6)、(2,6)、(3,6) 得到，乘积都是 6 的倍数。", "和为 6 的各对是 (1,5)、(2,4)、(3,3) 及其顺序交换，乘积都不是 6 的倍数。"],
    solutionEn: ["Sums 5, 7, 8, and 9 are possible using (2,3), (1,6), (2,6), and (3,6).", "No pair summing to 6 has product divisible by 6."],
    sourceUrl,
  },
  {
    id: "2024-06",
    year: 2024,
    number: 6,
    status: "published",
    primaryTopic: "几何",
    skills: ["弧与弦", "长度比较"],
    formats: ["路径图"],
    difficulty: 2,
    promptZh: "Sergei 沿图中的 P、Q、R、S 四条路线滑冰。把四条路线从最短到最长排序。",
    promptEn: "Sergei skates along paths P, Q, R, and S shown below. What is their order from shortest to longest?",
    figure: {
      src: "/questions/2024/q06.png",
      altZh: "同一胶囊形冰场中的四条路径 P、Q、R、S，分别由弧线、边线和交叉对角线组成。",
      altEn: "Four paths P, Q, R, and S drawn on identical capsule-shaped rinks using arcs, sides, and diagonals.",
    },
    options: [
      { label: "A", valueZh: "P，Q，R，S" },
      { label: "B", valueZh: "P，R，S，Q" },
      { label: "C", valueZh: "Q，S，P，R" },
      { label: "D", valueZh: "R，P，S，Q" },
      { label: "E", valueZh: "R，S，P，Q" },
    ],
    answer: "D",
    solutionZh: ["R 用弦替代了部分圆弧，因此最短；Q 包含最多内部交叉段且仍使用两端圆弧，因此最长。", "比较 P 与 S 时，S 含有对应直角三角形的斜边，而 P 含直角边，所以 P 比 S 短。排序为 R、P、S、Q。"],
    solutionEn: ["R is shortest because chords replace curved arcs; Q is longest because it includes the most interior crossing distance while retaining the curved ends.", "The relevant segment in S is a diagonal longer than the corresponding side in P, so the order is R, P, S, Q."],
    sourceUrl,
  },
  {
    id: "2024-07",
    year: 2024,
    number: 7,
    status: "published",
    primaryTopic: "计数与组合",
    secondaryTopics: ["数论", "几何"],
    skills: ["铺砌", "奇偶性", "模运算"],
    formats: ["方格拼图"],
    difficulty: 3,
    promptZh: "用 2×2、1×4、1×1 三种砖无重叠地铺满 3×7 长方形，最少需要多少块 1×1 砖？",
    promptEn: "A 3-by-7 rectangle is tiled using 2-by-2, 1-by-4, and 1-by-1 tiles. What is the minimum possible number of 1-by-1 tiles?",
    figure: {
      src: "/questions/2024/q07.png",
      altZh: "2×2、1×4、1×1 三种砖以及待铺满的 3×7 方格。",
      altEn: "The three tile shapes 2-by-2, 1-by-4, and 1-by-1, together with a 3-by-7 board.",
    },
    options: numericOptions(["1", "2", "3", "4", "5"]),
    answer: "E",
    solutionZh: ["两种大砖面积都是 4，而总面积为 21，所以 1×1 砖数量除以 4 余 1；选项中只可能是 1 或 5。", "若只用 1 块单位砖，至少两行会由大砖覆盖全部 7 格，但每种大砖在任一行覆盖的格数都是偶数，不可能覆盖 7 格。", "5 块单位砖可以构造出铺法，因此最少为 5。"],
    solutionEn: ["The large tiles have area 4, so the number of unit tiles is 1 modulo 4; only 1 or 5 is possible.", "One unit tile is impossible because two rows would need an odd 7 cells covered by tiles that cover an even number per row.", "A tiling with five unit tiles exists, so the minimum is 5."],
    sourceUrl,
  },
  {
    id: "2024-08",
    year: 2024,
    number: 8,
    status: "published",
    primaryTopic: "计数与组合",
    secondaryTopics: ["算术"],
    skills: ["状态枚举", "去重"],
    formats: ["过程题"],
    difficulty: 2,
    promptZh: "星期一 Taye 有 2 美元。之后每天，他要么增加 3 美元，要么把前一天的钱翻倍。3 天后的星期四，他可能有多少种不同的金额？",
    promptEn: "On Monday Taye has $2. Each day he either gains $3 or doubles the previous amount. How many different amounts could he have on Thursday?",
    options: numericOptions(["3", "4", "5", "6", "7"]),
    answer: "D",
    solutionZh: ["星期二可能为 4、5；星期三去重后可能为 7、8、10。", "星期四可能为 10、14、11、16、13、20，共 6 种。"],
    solutionEn: ["The distinct Wednesday amounts are 7, 8, and 10.", "On Thursday these produce 10, 14, 11, 16, 13, and 20, for six distinct amounts."],
    sourceUrl,
  },
  {
    id: "2024-09",
    year: 2024,
    number: 9,
    status: "published",
    primaryTopic: "算术",
    secondaryTopics: ["代数"],
    skills: ["比例", "倍数"],
    formats: ["文字应用题"],
    difficulty: 2,
    promptZh: "Maria 的弹珠只有红、绿、蓝三色。红色数量是绿色的一半，蓝色数量是绿色的 2 倍。下列哪一个可能是弹珠总数？",
    promptEn: "Maria has red, green, and blue marbles. She has half as many red as green and twice as many blue as green. Which could be the total?",
    options: numericOptions(["24", "25", "26", "27", "28"]),
    answer: "E",
    solutionZh: ["设红色有 r 个，则绿色有 2r 个，蓝色有 4r 个。", "总数为 7r，必须是 7 的倍数；选项中只有 28。"],
    solutionEn: ["If red is r, then green is 2r and blue is 4r.", "The total is 7r, and only 28 is a multiple of 7."],
    sourceUrl,
  },
  {
    id: "2024-10",
    year: 2024,
    number: 10,
    status: "published",
    primaryTopic: "算术",
    skills: ["线性变化", "四舍五入"],
    formats: ["数据应用题"],
    difficulty: 1,
    promptZh: "1980 年 1 月，Mauna Loa 天文台记录的二氧化碳浓度为 338 ppm，之后平均每年增加约 1.515 ppm。预计 2030 年 1 月是多少 ppm？结果取最接近的整数。",
    promptEn: "CO₂ was 338 ppm in January 1980 and increased by about 1.515 ppm per year. What is the expected January 2030 level, rounded to the nearest integer?",
    options: numericOptions(["399", "414", "420", "444", "459"]),
    answer: "B",
    solutionZh: ["1980 到 2030 相隔 50 年，增加量为 50×1.515=75.75，约为 76。", "预计浓度为 338+76=414 ppm。"],
    solutionEn: ["Over 50 years the increase is 50·1.515 = 75.75, about 76.", "The expected level is 338 + 76 = 414 ppm."],
    sourceUrl,
  },
  {
    id: "2024-11",
    year: 2024,
    number: 11,
    status: "published",
    primaryTopic: "几何",
    secondaryTopics: ["代数"],
    skills: ["坐标几何", "三角形面积"],
    formats: ["坐标图"],
    difficulty: 2,
    promptZh: "三角形 ABC 的顶点为 A(5,7)、B(11,7)、C(3,y)，且 y>7。若面积为 12，y 等于多少？",
    promptEn: "Triangle ABC has A(5,7), B(11,7), and C(3,y), with y>7. Its area is 12. What is y?",
    figure: {
      src: "/questions/2024/q11.png",
      altZh: "坐标三角形 ABC，其中 AB 为水平底边，A(5,7)、B(11,7)、C(3,y)。",
      altEn: "Triangle ABC with horizontal base AB, labeled A(5,7), B(11,7), and C(3,y).",
    },
    options: numericOptions(["8", "9", "10", "11", "12"]),
    answer: "D",
    solutionZh: ["底边 AB 长 11-5=6。由 12=(1/2)×6×高，得高为 4。", "因为 y>7，顶点 C 在直线 y=7 上方，所以 y=7+4=11。"],
    solutionEn: ["Base AB has length 6. From 12=(1/2)·6·h, the height is 4.", "Since y>7, y=7+4=11."],
    sourceUrl,
  },
  {
    id: "2024-12",
    year: 2024,
    number: 12,
    status: "published",
    primaryTopic: "代数",
    secondaryTopics: ["算术"],
    skills: ["列方程", "等差关系"],
    formats: ["条件列表"],
    difficulty: 2,
    promptZh: "Rohan 在 4 个鱼缸中共养了 90 条孔雀鱼。第 2 缸比第 1 缸多 1 条，第 3 缸比第 2 缸多 2 条，第 4 缸比第 3 缸多 3 条。第 4 缸有多少条？",
    promptEn: "Rohan has 90 guppies in four tanks. Tank 2 has 1 more than tank 1, tank 3 has 2 more than tank 2, and tank 4 has 3 more than tank 3. How many are in tank 4?",
    options: numericOptions(["20", "21", "23", "24", "26"]),
    answer: "E",
    solutionZh: ["设第 1 缸有 x 条，则四缸依次为 x、x+1、x+3、x+6。", "4x+10=90，得 x=20，所以第 4 缸有 26 条。"],
    solutionEn: ["The tank counts are x, x+1, x+3, and x+6.", "Their sum gives 4x+10=90, so x=20 and tank 4 has 26."],
    sourceUrl,
  },
  {
    id: "2024-13",
    year: 2024,
    number: 13,
    status: "published",
    primaryTopic: "计数与组合",
    skills: ["合法路径", "分类枚举"],
    formats: ["过程题"],
    difficulty: 3,
    promptZh: "Buzz 从地面开始，每次在楼梯上向上或向下跳一级。连续跳 6 次后回到地面，共有多少种跳法？途中不能跳到地面以下。",
    promptEn: "Buzz starts on the ground, makes 6 one-step up or down hops, and returns to the ground without going below it. How many sequences are possible?",
    options: numericOptions(["4", "5", "6", "8", "12"]),
    answer: "B",
    solutionZh: ["合法序列必须有 3 次上、3 次下，且任意前缀中向下次数不能多于向上次数。", "逐一列出可得 UUU DDD、UU DU DD、UU DD U D、U D U D U D、U D UU DD，共 5 种。"],
    solutionEn: ["A valid sequence has three up and three down hops, with no prefix containing more downs than ups.", "The five valid sequences are UUUDDD, UUDUDD, UUDDUD, UDUDUD, and UDUUDD."],
    sourceUrl,
  },
  {
    id: "2024-14",
    year: 2024,
    number: 14,
    status: "published",
    primaryTopic: "计数与组合",
    skills: ["最短路径", "动态规划"],
    formats: ["有向加权图"],
    difficulty: 3,
    promptZh: "图中给出 A、M、C、X、Y、Z 六座城镇之间的单向路线及距离。沿这些路线从 A 到 Z 的最短距离是多少千米？",
    promptEn: "The directed routes among towns A, M, C, X, Y, and Z are labeled with distances. What is the shortest distance from A to Z?",
    figure: {
      src: "/questions/2024/q14.png",
      altZh: "六个城镇构成的单向加权图，边上标有 2、5、6、8、10、14、17、25 等距离。",
      altEn: "A directed weighted graph on six towns with route distances labeled.",
    },
    options: numericOptions(["28", "29", "30", "31", "32"]),
    answer: "A",
    solutionZh: ["从 A 出发的最短距离依次可更新为：X=5，M=7，Y=13，C=18。", "到 Z 可从 Y、C、M 到达，对应总距离为 30、28、32，所以最短为 28。"],
    solutionEn: ["The shortest distances from A are X=5, M=7, Y=13, and C=18.", "Reaching Z through Y, C, or M gives 30, 28, or 32, so the minimum is 28."],
    sourceUrl,
  },
  {
    id: "2024-15",
    year: 2024,
    number: 15,
    status: "published",
    primaryTopic: "数论",
    secondaryTopics: ["代数"],
    skills: ["字母算式", "位值", "分类枚举"],
    formats: ["字母算式"],
    difficulty: 3,
    promptZh: "字母 F、L、Y、B、U、G 表示互不相同的数字。若最大的 FLYFLY 满足 8×FLYFLY=BUGBUG，求 FLY+BUG。",
    promptEn: "Distinct digits F, L, Y, B, U, G satisfy 8·FLYFLY = BUGBUG, with FLYFLY as large as possible. What is FLY+BUG?",
    expression: ["8 · FLYFLY = BUGBUG"],
    options: numericOptions(["1089", "1098", "1107", "1116", "1125"]),
    answer: "C",
    solutionZh: ["FLYFLY=1001×FLY，BUGBUG=1001×BUG，所以只需满足 8×FLY=BUG。", "BUG 为三位数，故 FLY≤124。124 不合要求，因为 8×124=992 有重复数字且复用 2；下一候选 123 满足 8×123=984，六个数字互异。", "因此 FLY+BUG=123+984=1107。"],
    solutionEn: ["Canceling the repeated block factor 1001 gives 8·FLY = BUG.", "FLY≤124. The candidate 124 fails, while 123 gives 984 and all six digits are distinct.", "Thus FLY+BUG=123+984=1107."],
    sourceUrl,
  },
  {
    id: "2024-16",
    year: 2024,
    number: 16,
    status: "published",
    primaryTopic: "数论",
    secondaryTopics: ["计数与组合"],
    skills: ["整除", "极值", "构造"],
    formats: ["方格题"],
    difficulty: 4,
    promptZh: "Minh 把 1 到 81 填入 9×9 方格，并计算每行、每列所有数的乘积。乘积能被 3 整除的行和列合计最少可能有多少条？",
    promptEn: "The numbers 1 through 81 are placed in a 9-by-9 grid. What is the least total number of rows and columns whose product is divisible by 3?",
    options: numericOptions(["8", "9", "10", "11", "12"]),
    answer: "D",
    solutionZh: ["1 到 81 有 27 个 3 的倍数。若有 r 行和 c 列的乘积能被 3 整除，这 27 个数必须全部位于这 r 行与 c 列的 rc 个交点中。", "若 r+c≤10，则 rc≤25，不够放 27 个数，所以至少需要 11 条。", "把 25 个倍数放在 5×5 块中，再把余下 2 个放在同 5 行中的第 6 列，可实现 5+6=11。"],
    solutionEn: ["There are 27 multiples of 3. If r rows and c columns are marked, all 27 must lie in their rc intersections.", "When r+c≤10, rc≤25, so at least 11 lines are required.", "A construction using 5 rows and 6 columns shows 11 is attainable."],
    sourceUrl,
  },
  {
    id: "2024-17",
    year: 2024,
    number: 17,
    status: "published",
    primaryTopic: "计数与组合",
    skills: ["分类计数", "有序排列"],
    formats: ["棋盘图"],
    difficulty: 3,
    promptZh: "在 3×3 棋盘的不同格中放一枚白王和一枚黑王，使它们互不攻击，共有多少种放法？王可攻击水平、竖直或对角方向一步内的格子。",
    promptEn: "A white king and a black king are placed on different squares of a 3-by-3 grid so that they do not attack each other. How many ordered placements are possible?",
    figure: {
      src: "/questions/2024/q17.png",
      altZh: "3×3 棋盘中央放一枚王，八个方向箭头标出其攻击范围。",
      altEn: "A king in the center of a 3-by-3 board with arrows to all eight attacked squares.",
    },
    options: numericOptions(["20", "24", "27", "28", "32"]),
    answer: "E",
    solutionZh: ["白王在中央时无安全位置。白王在角上时，黑王有 5 个安全格，共 4×5=20 种。", "白王在非角边格时，黑王有 3 个安全格，共 4×3=12 种。总数为 32。"],
    solutionEn: ["A central white king leaves no safe square. From a corner, the black king has 5 safe squares, giving 20 placements.", "From a non-corner edge square it has 3 safe squares, giving 12 more. Total: 32."],
    sourceUrl,
  },
  {
    id: "2024-18",
    year: 2024,
    number: 18,
    status: "published",
    primaryTopic: "几何",
    secondaryTopics: ["代数"],
    skills: ["圆环面积", "扇形面积", "列方程"],
    formats: ["几何图"],
    difficulty: 4,
    promptZh: "三个同心圆半径分别为 1、2、3。半径 1 与 2 间的整个圆环被涂色，半径 2 与 3 间由圆心角 BOC 截出的扇环也被涂色。若涂色与未涂色面积相等，∠BOC 是多少度？",
    promptEn: "Three concentric circles have radii 1, 2, and 3. The middle annulus and a sector of the outer annulus are shaded. If shaded and unshaded areas are equal, what is angle BOC?",
    figure: {
      src: "/questions/2024/q18.png",
      altZh: "半径为 1、2、3 的三个同心圆，中间圆环全部涂色，外层圆环有一块扇形涂色。",
      altEn: "Three concentric circles with the middle annulus fully shaded and one sector of the outer annulus shaded.",
    },
    options: numericOptions(["108", "120", "135", "144", "150"]),
    answer: "A",
    solutionZh: ["设圆心角为 θ。涂色面积为 3π+(θ/360)·5π，未涂色面积为 π+((360-θ)/360)·5π。", "令两者相等，约去 π 后解得 θ=108°。"],
    solutionEn: ["Let the angle be θ. The shaded area is 3π+(θ/360)·5π, and the unshaded area is π+((360-θ)/360)·5π.", "Equating them gives θ=108°."],
    sourceUrl,
  },
  {
    id: "2024-19",
    year: 2024,
    number: 19,
    status: "published",
    primaryTopic: "计数与组合",
    secondaryTopics: ["概率"],
    skills: ["集合交集", "极值"],
    formats: ["文字应用题"],
    difficulty: 3,
    promptZh: "Jordan 有 15 双运动鞋，其中 3/5 是红色，其余是白色；2/3 是高帮，其余是低帮。红色高帮鞋占全部鞋的比例最小可能是多少？",
    promptEn: "Among 15 pairs of sneakers, 3/5 are red and 2/3 are high-top. What is the least possible fraction that are both red and high-top?",
    options: numericOptions(["0", "1/5", "4/15", "1/3", "2/5"]),
    answer: "C",
    solutionZh: ["共有 9 双红鞋、6 双白鞋，以及 10 双高帮鞋。", "要尽量减少红色高帮，先让全部 6 双白鞋都是高帮，仍需 4 双红鞋为高帮。比例为 4/15。"],
    solutionEn: ["There are 9 red pairs, 6 white pairs, and 10 high-top pairs.", "Making all 6 white pairs high-top still requires 4 red high-top pairs, so the minimum fraction is 4/15."],
    sourceUrl,
  },
  {
    id: "2024-20",
    year: 2024,
    number: 20,
    status: "published",
    primaryTopic: "几何",
    secondaryTopics: ["计数与组合"],
    skills: ["空间想象", "分类枚举"],
    formats: ["立体几何图"],
    difficulty: 4,
    promptZh: "从立方体 PQRSTUVW 的任意三个顶点可组成三角形。含顶点 P 的等边三角形共有多少个？",
    promptEn: "Any three vertices of cube PQRSTUVW form a triangle. How many equilateral triangles contain P?",
    figure: {
      src: "/questions/2024/q20.png",
      altZh: "顶点标为 P、Q、R、S、T、U、V、W 的立方体线框图。",
      altEn: "A wireframe cube with vertices labeled P, Q, R, S, T, U, V, and W.",
    },
    options: numericOptions(["0", "1", "2", "3", "6"]),
    answer: "D",
    solutionZh: ["等边三角形的边必须沿立方体各面的面对角线连接。", "含 P 的可行三角形为 △PVT、△PRT、△PRV，共 3 个。"],
    solutionEn: ["The sides of such an equilateral triangle must be face diagonals of the cube.", "The possibilities containing P are PVT, PRT, and PRV, for a total of 3."],
    sourceUrl,
  },
  {
    id: "2024-21",
    year: 2024,
    number: 21,
    status: "published",
    primaryTopic: "代数",
    secondaryTopics: ["算术"],
    skills: ["比例方程", "数量变化"],
    formats: ["文字应用题"],
    difficulty: 4,
    promptZh: "树上的青蛙在阴影中变绿、在阳光下变黄。起初绿蛙与黄蛙之比为 3:1。随后 3 只绿蛙移到阳光下，5 只黄蛙移到阴影中，新比为 4:1。现在绿蛙与黄蛙数量相差多少？",
    promptEn: "The initial green-to-yellow frog ratio is 3:1. Three green frogs move into sun and five yellow frogs into shade, making the ratio 4:1. What is the current difference?",
    options: numericOptions(["10", "12", "16", "20", "24"]),
    answer: "E",
    solutionZh: ["设起初黄蛙为 y 只，则绿蛙为 3y 只。移动后绿蛙为 3y+2，黄蛙为 y-2。", "由 (3y+2)/(y-2)=4 得 y=10。现在绿蛙 32 只、黄蛙 8 只，相差 24。"],
    solutionEn: ["Let the original yellow count be y, so green is 3y. After the moves the counts are 3y+2 and y-2.", "Solving (3y+2)/(y-2)=4 gives y=10; the current counts are 32 and 8, differing by 24."],
    sourceUrl,
  },
  {
    id: "2024-22",
    year: 2024,
    number: 22,
    status: "published",
    primaryTopic: "几何",
    secondaryTopics: ["算术"],
    skills: ["圆环面积", "等积建模"],
    formats: ["截面图"],
    difficulty: 4,
    promptZh: "一卷胶带外径 4 英寸，缠在直径 2 英寸的圆环上，胶带厚 0.015 英寸。若全部展开，长度约是多少英寸？结果取最接近的 100 英寸。",
    promptEn: "A tape roll has outer diameter 4 inches, inner diameter 2 inches, and tape thickness 0.015 inches. Approximately how long is the unrolled tape, rounded to the nearest 100 inches?",
    figure: {
      src: "/questions/2024/q22.png",
      altZh: "胶带卷横截面为圆环，外径 4 英寸，内径 2 英寸。",
      altEn: "An annular tape-roll cross section with outer diameter 4 inches and inner diameter 2 inches.",
    },
    options: numericOptions(["300", "600", "1200", "1500", "1800"]),
    answer: "B",
    solutionZh: ["胶带横截面面积为 π(2²-1²)=3π。展开后是厚 0.015、长 L 的长方形，所以 0.015L=3π。", "L=200π≈628，取最接近的 100 得 600 英寸。"],
    solutionEn: ["The annular cross-sectional area is π(2²-1²)=3π. Unrolled, it is a rectangle of thickness 0.015 and length L.", "Thus L=3π/0.015=200π≈628, which rounds to 600 inches."],
    sourceUrl,
  },
  {
    id: "2024-23",
    year: 2024,
    number: 23,
    status: "published",
    primaryTopic: "数论",
    secondaryTopics: ["几何"],
    skills: ["最大公因数", "格点计数"],
    formats: ["坐标方格图"],
    difficulty: 5,
    promptZh: "在方格纸上，连接 (0,4) 与 (2,0) 的线段穿过 4 个单位格内部。若连接 (2000,3000) 与 (5000,8000)，线段会穿过多少个单位格内部？",
    promptEn: "A segment from (0,4) to (2,0) crosses 4 grid cells. How many cells are crossed by the segment from (2000,3000) to (5000,8000)?",
    figure: {
      src: "/questions/2024/q23.png",
      altZh: "坐标方格中从 (0,4) 到 (2,0) 的线段及其穿过的 4 个涂色单位格。",
      altEn: "A grid segment from (0,4) to (2,0) with its four crossed unit cells shaded.",
    },
    options: numericOptions(["6000", "6500", "7000", "7500", "8000"]),
    answer: "C",
    solutionZh: ["横向变化 a、纵向变化 b 的格点线段穿过 a+b-gcd(a,b) 个单位格。", "这里 a=3000、b=5000，最大公因数为 1000，所以格数为 3000+5000-1000=7000。"],
    solutionEn: ["A grid segment with horizontal and vertical changes a,b crosses a+b-gcd(a,b) cells.", "Here that is 3000+5000-1000=7000."],
    sourceUrl,
  },
  {
    id: "2024-24",
    year: 2024,
    number: 24,
    status: "published",
    primaryTopic: "几何",
    skills: ["等腰直角三角形", "容斥原理", "面积计算"],
    formats: ["几何图"],
    difficulty: 4,
    promptZh: "彩色玻璃作品由两座山的轮廓并成，高分别为 8、12 英尺。每个山峰为 90°，山坡与地面成 45°，总面积为 183 平方英尺。两山相交点离地 h 英尺，求 h。",
    promptEn: "Two overlapping 45-45-90 mountain shapes have heights 8 and 12 and union area 183. Their sides meet h feet above the ground. What is h?",
    figure: {
      src: "/questions/2024/q24.png",
      altZh: "两个重叠的等腰直角三角形山峰，高分别为 8 和 12，交点高度标为 h。",
      altEn: "Two overlapping isosceles right-triangle mountains of heights 8 and 12 with intersection height h.",
    },
    options: numericOptions(["4", "5", "4√2", "6", "5√2"]),
    answer: "B",
    solutionZh: ["高为 x 的 45°-45°-90°三角形面积为 x²。两座山面积分别为 64、144，重叠部分面积为 h²。", "由 64+144-h²=183，得 h²=25，所以 h=5。"],
    solutionEn: ["A 45-45-90 mountain of height x has area x². The two areas are 64 and 144, and the overlap has area h².", "Thus 64+144-h²=183, giving h=5."],
    sourceUrl,
  },
  {
    id: "2024-25",
    year: 2024,
    number: 25,
    status: "published",
    primaryTopic: "概率",
    secondaryTopics: ["计数与组合"],
    skills: ["补集", "生成函数", "组合计数"],
    formats: ["座位图"],
    difficulty: 5,
    promptZh: "一架小飞机有 4 排座位，每排 3 个。已有 8 名乘客随机坐入 12 个座位，一对夫妻接着登机。剩余座位中存在同排相邻两个座位供夫妻就座的概率是多少？",
    promptEn: "A plane has four rows of three seats. After eight passengers occupy random seats, what is the probability that two adjacent seats in one row remain for a couple?",
    figure: {
      src: "/questions/2024/q25.png",
      altZh: "四排、每排三个座位的示意图。",
      altEn: "A seating diagram with four rows of three seats.",
    },
    options: numericOptions(["8/15", "32/55", "20/33", "34/55", "8/11"]),
    answer: "C",
    solutionZh: ["4 个空座的集合共有 C(12,4)=495 种。计算补集：每排都没有相邻空座。", "一排三个座位中，选 0、1、2 个互不相邻空座分别有 1、3、1 种，故补集数量是 (1+3x+x²)⁴ 中 x⁴ 的系数，即 195。", "所求概率为 (495-195)/495=20/33。"],
    solutionEn: ["There are C(12,4)=495 equally likely sets of four empty seats.", "For one row, nonadjacent empty-seat patterns contribute 1+3x+x². The coefficient of x⁴ in its fourth power is 195.", "The desired probability is (495-195)/495=20/33."],
    sourceUrl,
  },
];
